<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pendiente Autorizacin</name>
   <tag></tag>
   <elementGuidId>8f1544de-6a1a-4b58-90e5-bcd8dc0ecc1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar' and @title = 'Autorizar / Rechazar SPR']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, '_UCAccionesBuscadorSPR_imgAutorizarRechazar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c440fe89-4df4-4df0-8734-6916aa78711e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>4abfba1d-7464-4ee4-b92b-43fcf98c3569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$gridResultado$cell0_5$UCAccionesBuscadorSPR$imgAutorizarRechazar</value>
      <webElementGuid>3b6c246e-eaaf-46f8-97f0-f80bab8c105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar</value>
      <webElementGuid>603f4328-60d6-4d78-8a4d-0a1d306f1e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Autorizar / Rechazar SPR</value>
      <webElementGuid>0b1002bd-d614-4b84-a2f3-844c2822e2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_autoriza_circular.gif</value>
      <webElementGuid>976c6df4-5a38-4386-b272-2d1b42360ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Autorizar / Rechazar SPR</value>
      <webElementGuid>0dfd594f-a4f4-4afa-9127-44dd0328f57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$gridResultado$cell0_5$UCAccionesBuscadorSPR$imgAutorizarRechazar&quot;, &quot;&quot;, false, &quot;&quot;, &quot;AutorizarRechazarSPR.aspx?qs=KsMTtNTFwt31VHql457THiq9UoeviUHOD67f8k9s58gfOr/BAfQNvUsezEHqZ5E3LW6T56GjeUg=&quot;, false, false))</value>
      <webElementGuid>2b0032ac-11ff-4b2d-bb92-a417da3d42bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar&quot;)</value>
      <webElementGuid>26c37ccc-69a4-4c61-aee2-8a801e7654de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar']</value>
      <webElementGuid>7310af77-c92d-4416-8abc-44b6714bce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_gridResultado_tccell0_5']/input[2]</value>
      <webElementGuid>fa946396-577d-4b29-a5ae-a374a6142440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input[2]</value>
      <webElementGuid>d1a6c43e-f6ff-4ead-9cf8-f040734c75f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$gridResultado$cell0_5$UCAccionesBuscadorSPR$imgAutorizarRechazar' and @id = 'ctl00_CPH1_gridResultado_cell0_5_UCAccionesBuscadorSPR_imgAutorizarRechazar' and @title = 'Autorizar / Rechazar SPR' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_autoriza_circular.gif' and @alt = 'Autorizar / Rechazar SPR']</value>
      <webElementGuid>fe332896-db7e-4e05-bddf-f713981556ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
