<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_msjSprAutorizacionExitosa</name>
   <tag></tag>
   <elementGuidId>f7677f17-75b4-4e1c-9a53-dac676222139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@id = 'ctl00_CPH1_msjExitoStrong' and (text() = 'La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.' or . = 'La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_msjExitoStrong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='ctl00_CPH1_msjExitoStrong']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>45a42474-9f2f-4e71-9e5b-a660a0211dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_msjExitoStrong</value>
      <webElementGuid>be51ea32-b2b8-47dd-903a-61e716e9b5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.</value>
      <webElementGuid>cb1e16d3-1082-4ea1-b9b3-48a21eaadbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_msjExitoStrong&quot;)</value>
      <webElementGuid>2a4d4119-e8a8-4591-8b42-9640d424c658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='ctl00_CPH1_msjExitoStrong']</value>
      <webElementGuid>0c44c46b-a326-49d8-9824-0b73985a6667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_divExito']/strong</value>
      <webElementGuid>98af03cf-2758-4805-a201-3240be8b7650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/following::strong[1]</value>
      <webElementGuid>561ec1ba-9e5b-4c98-83c7-2b2e095280e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='acá'])[1]/preceding::strong[2]</value>
      <webElementGuid>4b346888-cbf2-45db-9b7c-e01666c5df53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.']/parent::*</value>
      <webElementGuid>3caa444c-4e7d-4c7a-8488-09cbd674804e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/strong</value>
      <webElementGuid>85ad78ba-e231-431e-822e-7ca39111a9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'ctl00_CPH1_msjExitoStrong' and (text() = 'La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.' or . = 'La solicitud de provisión ha sido autorizada con éxito. Se notificará al proveedor.')]</value>
      <webElementGuid>b6a4dc04-6aaf-439f-ab9c-cdd6d576927c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
