<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Completar detalle</name>
   <tag></tag>
   <elementGuidId>d8167151-7b03-42d7-9985-87bc32c51d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1755fa3-053d-468d-b612-990287565d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle</value>
      <webElementGuid>b70ef25b-a43c-431c-8ee5-5a2b8697a31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_azul_ch</value>
      <webElementGuid>f0f4ec6a-005b-49ff-9c65-203acb493fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>cf5d27d2-8abe-499e-82c6-44689558c1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$UCDetalleEntrega$lnkCompletarDetalle','')</value>
      <webElementGuid>b8f6107b-84ee-444f-a721-a48fd5b4139f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar detalle</value>
      <webElementGuid>b0c2aecb-8a6e-42b5-9a8a-efd298bd51b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle&quot;)</value>
      <webElementGuid>f87a66a8-7e6b-40b7-ace8-1d0d5efa7a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle']</value>
      <webElementGuid>3733d2c3-afb6-458d-84aa-7ee6b48f9b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/a</value>
      <webElementGuid>261015e9-f60c-465e-9487-ee0bcc54c2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Completar detalle')]</value>
      <webElementGuid>a38b73f1-2672-4c83-9a31-290354c343a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[1]/following::a[1]</value>
      <webElementGuid>e9a4ef30-3ffc-4530-8505-9d44ef207864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No existen entregas'])[1]/following::a[1]</value>
      <webElementGuid>b4caf889-5e01-426c-ad58-9be26b4fc33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar y Volver'])[1]/preceding::a[1]</value>
      <webElementGuid>ee932457-263a-49db-a056-49ef30784a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::a[2]</value>
      <webElementGuid>7970ade3-a84b-4c72-8273-e3545ff4721d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completar detalle']/parent::*</value>
      <webElementGuid>780cf5e7-e407-437c-890c-d90465676871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$UCDetalleEntrega$lnkCompletarDetalle','')&quot;)]</value>
      <webElementGuid>fb301fc9-ba3f-4315-a2a4-73577b6b76ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>b1c1a4a7-b7e1-4118-b333-cbb6cbd030d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UCDetalleEntrega_lnkCompletarDetalle' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$UCDetalleEntrega$lnkCompletarDetalle&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Completar detalle' or . = 'Completar detalle')]</value>
      <webElementGuid>eec31dc7-1ca0-4eac-85b6-f071b54fa66a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
