<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkVerifiqueIingresadoDetallesCantidad</name>
   <tag></tag>
   <elementGuidId>fc92ffe3-13c1-47bf-8239-c7d0f01f8816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>003cefc6-b891-4fe2-90e4-269d8502eb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle</value>
      <webElementGuid>903c288a-048b-4c60-8a80-78dfc2d5fc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e73808bf-6506-4507-9cb0-550f78163836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCDetalleEntrega$rptRenglones$ctl01$cbModificarDetalle</value>
      <webElementGuid>08b56786-c2e0-4e1c-819c-a44b977e76f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle&quot;)</value>
      <webElementGuid>6154d8e3-fc6f-4169-83bc-093b8b26829e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle']</value>
      <webElementGuid>b5f3590a-b217-4908-ae1d-db7f24f329aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-accordion-renglon_1_1-header-0']/table/tbody/tr/td[7]/center/span/input</value>
      <webElementGuid>1a74b19a-2272-43a1-a8a7-840d5274971d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ca2f22b0-d6ca-4065-b158-4896bc88a295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCDetalleEntrega_rptRenglones_ctl01_cbModificarDetalle' and @type = 'checkbox' and @name = 'ctl00$CPH1$UCDetalleEntrega$rptRenglones$ctl01$cbModificarDetalle']</value>
      <webElementGuid>132c6de9-8807-4bff-8f3d-af7321192aaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
