<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CantidadEntregar1</name>
   <tag></tag>
   <elementGuidId>6562b14d-81a3-4f97-a2c7-84b9dd3ade5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43a447fb-adb3-45a3-b6a5-9c619d82f019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>f34e0556-2b4c-40bb-b707-ed7986cb73ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$gvRenglones$cell0_6$txtCantidadEntregar</value>
      <webElementGuid>9a50edf1-1c2a-4520-9b6e-86f568c04511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar', event)</value>
      <webElementGuid>df1fee62-03dc-47c5-a350-0775025fbf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e3273487-e560-447a-b81c-4d622bdf2de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I</value>
      <webElementGuid>8b6466ea-9421-41ee-aa5a-dad7608f2798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar')</value>
      <webElementGuid>98116039-a526-433a-8d84-4d92c7a38357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar')</value>
      <webElementGuid>029f93e0-b9b0-4f0b-b8d2-1bce16f1bcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar')</value>
      <webElementGuid>3caa30c9-cf27-4be1-aa31-d1e0ffedbf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81180a4d-551c-417c-af10-485202206c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>aspxEKeyPress('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar', event)</value>
      <webElementGuid>117c3c10-70ed-4bdb-8fe8-64f4146be400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar', event)</value>
      <webElementGuid>8291faaf-0d22-4b9e-a509-2f43a51ae823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>87853168-3a37-4821-9271-91fec62c99ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66f0dcc7-657c-49d1-8345-74507ad6a6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I&quot;)</value>
      <webElementGuid>ef246adb-7b42-4efd-935c-640427e6f514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I']</value>
      <webElementGuid>baeeb8db-c374-470f-94a0-e6dbc74c9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar']/tbody/tr/td/input</value>
      <webElementGuid>25331b58-4d97-4af0-8f15-a9a6a2e27a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>feb3dbb2-e355-4afe-b8bb-bcbd4c628522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$gvRenglones$cell0_6$txtCantidadEntregar' and @id = 'ctl00_CPH1_gvRenglones_cell0_6_txtCantidadEntregar_I' and @type = 'text']</value>
      <webElementGuid>9c6588c6-12db-414f-910e-31572d3b2977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
