<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CantidadEntregar2</name>
   <tag></tag>
   <elementGuidId>91f78a97-dca6-42e2-8314-a3ea291fae22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a05e10fc-0e8f-4bd0-ba30-c128b2745f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea  dxeFocused dxh0</value>
      <webElementGuid>aa381034-4180-440e-9c2e-83b4e393e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$gvRenglones$cell1_6$txtCantidadEntregar</value>
      <webElementGuid>ce270e83-7bda-49c6-bdf3-3be2f1123c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar', event)</value>
      <webElementGuid>f790430d-afe8-4614-b873-1da7079d1258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>df02d74d-2b59-4140-b31a-7ed0df476832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I</value>
      <webElementGuid>b4924db3-898e-4a68-a8f0-3f1b47d6de33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar')</value>
      <webElementGuid>c87d915a-393c-4ba0-9da6-7fc010e44476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar')</value>
      <webElementGuid>24a9278c-f456-4bf7-bb24-e9906cced85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar')</value>
      <webElementGuid>c69cec83-033e-4852-9801-1ef525f06240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7202a35e-0fe1-456b-9a86-70da403971b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>aspxEKeyPress('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar', event)</value>
      <webElementGuid>9a45a1ce-d77c-45c5-8085-dce164bcef5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar', event)</value>
      <webElementGuid>fba5cb29-8c2a-4c80-922f-5307d01ce8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0cf2e640-0d4d-459d-bb7d-75f878b041af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7a48e8ef-2da1-4e0d-9307-9ee6de4563bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I&quot;)</value>
      <webElementGuid>9ea280f6-f227-4187-9afc-4353dadf63d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I']</value>
      <webElementGuid>8132bf1e-d231-439b-ae6f-e381c291377b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar']/tbody/tr/td/input</value>
      <webElementGuid>1c4d87f0-246e-4de2-bf88-84ad72343171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>6c77a0e3-c5b0-40ab-a1d4-d3e8e0c2c55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$gvRenglones$cell1_6$txtCantidadEntregar' and @id = 'ctl00_CPH1_gvRenglones_cell1_6_txtCantidadEntregar_I' and @type = 'text']</value>
      <webElementGuid>6da7d045-4dd0-4a8d-b77d-1f124a2580e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
