<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_checkValidoInformacionBasica</name>
   <tag></tag>
   <elementGuidId>56da65f2-4648-4819-a369-ec4022372ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionInfoBasica_imEstado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_CPH1_seccionInfoBasica_imEstado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c4bac52-e23f-466f-bcfd-011a06b44e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionInfoBasica_imEstado</value>
      <webElementGuid>4f1b2bce-0bb6-46c6-b36a-d5d87080e10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_alerta_exito.gif</value>
      <webElementGuid>4f7e22e4-3c9b-499e-8636-77887c4aa430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Alerta Exito</value>
      <webElementGuid>88543c0c-7483-45d4-a5e2-93431af71ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionInfoBasica_imEstado&quot;)</value>
      <webElementGuid>c07c1ed3-a508-40cd-a18a-d044a8bb5dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_CPH1_seccionInfoBasica_imEstado']</value>
      <webElementGuid>dd437f5f-1a54-4d08-81d8-88005b9dc438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[3]/table/tbody/tr/td/img</value>
      <webElementGuid>45a590df-b535-4e87-9ffe-26b34830d64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Alerta Exito']</value>
      <webElementGuid>a44760fb-6d70-4282-af80-23abbdcef34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>e6204576-e115-44c1-b973-aa19669e6817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_CPH1_seccionInfoBasica_imEstado' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_alerta_exito.gif' and @alt = 'Alerta Exito']</value>
      <webElementGuid>3da605bc-42cc-4e14-bd16-a80c2df461ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
