<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CompletarDatos</name>
   <tag></tag>
   <elementGuidId>11384816-aa62-4f16-b8f4-665373b1710b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionIndiceAutorizacion_hlDatos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_seccionIndiceAutorizacion_hlDatos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d67a46ba-6a2a-467a-ad70-bca1ffe7a30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionIndiceAutorizacion_hlDatos</value>
      <webElementGuid>f7b23ba5-dc22-4554-b997-7b48062c5aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>0775452d-5796-4baf-926e-ee98e0a40a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2Hdt0UkLPSyWOA==</value>
      <webElementGuid>60cae6aa-e329-44d9-9597-d3c0306951fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar datos</value>
      <webElementGuid>773e298b-4c74-44c4-bedd-baac96b7fb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionIndiceAutorizacion_hlDatos&quot;)</value>
      <webElementGuid>57091a90-f958-4a82-bbb5-7bee1c2bb954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_seccionIndiceAutorizacion_hlDatos']</value>
      <webElementGuid>fe80ebbe-3e76-4703-8e6a-12b4d9bbe219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr[15]/td[2]/span[2]/a</value>
      <webElementGuid>8075a87d-9cce-44fd-8550-c1f27872cbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Completar datos')])[3]</value>
      <webElementGuid>76553611-000d-4f99-a62f-660a0833a949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos obligatorios'])[3]/following::a[1]</value>
      <webElementGuid>8ebc8d2c-322e-46a3-9421-87e22fa463c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[15]/preceding::a[1]</value>
      <webElementGuid>070bb79f-9938-4022-a02b-0d8ed7d2f22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2Hdt0UkLPSyWOA==')]</value>
      <webElementGuid>2117f498-32fd-499d-882d-bfae468f0179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/span[2]/a</value>
      <webElementGuid>955a4669-11b5-4778-a310-a5da235dfc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_seccionIndiceAutorizacion_hlDatos' and @href = 'IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2Hdt0UkLPSyWOA==' and (text() = 'Completar datos' or . = 'Completar datos')]</value>
      <webElementGuid>c5b0ebce-4e82-42de-94f6-3299569f57e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
