<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Anio</name>
   <tag></tag>
   <elementGuidId>8c7d524e-05c7-49b0-8aaa-13dd0b86e57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_ucIngresarActo_DropDownAnio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36ac9650-0d07-48f5-8a38-166253b09381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$DropDownAnio</value>
      <webElementGuid>a82a0428-28d6-448a-ab27-acd2eedd6955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      <webElementGuid>ac3f8aac-af7c-4435-9308-75ec7d950d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80855ee8-e09e-4c94-b5c2-ce17b125cea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	</value>
      <webElementGuid>e1477eb9-a75e-43a3-a55e-a5c5a060c051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_DropDownAnio&quot;)</value>
      <webElementGuid>6fb481b9-452a-4eb0-b7e5-0faa7aa9d64a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_ucIngresarActo_DropDownAnio']</value>
      <webElementGuid>23f51196-7284-402c-9164-a00fa71da525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaAnioDocumento']/select</value>
      <webElementGuid>6e43e0c2-8a64-440c-ae1a-9d3963145958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[1]</value>
      <webElementGuid>93a8a446-0520-4778-82d9-4f1ccf0b7a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>2d9f9615-51fa-46a7-905a-356497ffe288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifique que el año haya sido ingresado.'])[1]/preceding::select[1]</value>
      <webElementGuid>1c974c5c-d048-4634-b3c5-cc99a5c622fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>fc4d3e9d-cd83-4ebf-a783-9f06dd51662d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>30789f69-dbb0-4974-bcce-0e4c79c94150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$ucIngresarActo$DropDownAnio' and @id = 'ctl00_CPH1_ucIngresarActo_DropDownAnio' and (text() = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	' or . = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	')]</value>
      <webElementGuid>ab8233ad-c273-4e05-98da-96b51953fa83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
