<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N Telfono_nTelefono</name>
   <tag></tag>
   <elementGuidId>8b043103-8a18-4a1b-ac86-ff834137b859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nTelefono</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nTelefono' and @name = 'nTelefono' and @type = 'tel']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nTelefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ef48b39-0e2d-4dc9-b6e4-8e4af8c0b928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e781640-ef5d-40a9-b670-2c503584c6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>f99af805-e1ef-4184-b8f2-36acfeb15d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>7c6df3b8-3a1b-4306-a944-6dee394b39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>4174ca28-3cb2-4b10-9dd5-3c9f5c3c6848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>31a66add-95da-471b-b687-8f4790c1a873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>52b28bf9-72c9-4401-94fa-5e7a0c308d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>6cb87549-7e09-4c2f-926f-2f5b18196a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nTelefono&quot;)</value>
      <webElementGuid>17ecc61d-1df5-4fed-a2c4-702cc2f85b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nTelefono']</value>
      <webElementGuid>bcb6e8e2-b47f-4189-aacb-b9459f3ba271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/form/div/div[7]/div/div/input</value>
      <webElementGuid>eb091b24-7b7e-41eb-a228-9b4a75562c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>617bfd3b-561e-4f02-9d8e-8e2a44e43813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nTelefono' and @name = 'nTelefono' and @type = 'tel']</value>
      <webElementGuid>543195eb-8e41-4d75-961d-630d5b84331b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
