<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_msjContraseasNoCoinciden</name>
   <tag></tag>
   <elementGuidId>758aa7ae-8e4d-4f53-b0c6-8df69fe8d508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='newPassword-helper-text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//p[(text() = 'Las contraseñas no coinciden' or . = 'Las contraseñas no coinciden')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newPassword-helper-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ffdd488e-248f-4836-947a-068b07c6d698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root MuiFormHelperText-contained Mui-error MuiFormHelperText-filled Mui-required</value>
      <webElementGuid>dc71d0d8-a980-4803-adbd-5aafe571650d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPassword-helper-text</value>
      <webElementGuid>0ecc23f8-d1ec-4b83-a2ef-8c790cec0acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Las contraseñas no coinciden</value>
      <webElementGuid>5b085e36-9770-4876-be03-fddd1a336749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPassword-helper-text&quot;)</value>
      <webElementGuid>16424e96-d201-474b-95c0-ea649890dc58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='newPassword-helper-text']</value>
      <webElementGuid>c3709540-a0a0-4798-b43b-c0484d7a947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/form/div/div[14]/div/p</value>
      <webElementGuid>25ed9909-b7f9-4564-aa86-8ce6be27937b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Las contraseñas no coinciden']/parent::*</value>
      <webElementGuid>d1847fc5-b1fb-45aa-aad4-0e1dc8c59178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/p</value>
      <webElementGuid>2dd97673-2d7d-4829-b0c4-4b92618db02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'newPassword-helper-text' and (text() = 'Las contraseñas no coinciden' or . = 'Las contraseñas no coinciden')]</value>
      <webElementGuid>04714f39-d785-4cec-b850-957140f8cc45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
