<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Agregar</name>
   <tag></tag>
   <elementGuidId>bb2ef0c8-b3dc-4b6b-82ce-ff6c00528c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa8c998a-e60e-491f-bdf8-64fb546a45ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: return ValidarSeccion(this);</value>
      <webElementGuid>43b645a4-5a9f-45f3-9c7d-239a5eb726eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona</value>
      <webElementGuid>a1f3d86f-7d1f-4894-94f3-dc8f2357436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>c506c5ea-5510-491a-84b4-08e1ef60a84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$datosAdministradorLegitimado$lnkAgregarPersona','')</value>
      <webElementGuid>16761fab-1c97-4fa2-b931-0ab4241b8b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>460de2e5-8461-4aaf-a68d-f2e58497d456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona&quot;)</value>
      <webElementGuid>d7839422-7853-4991-96b2-17eeed383828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona']</value>
      <webElementGuid>fa715205-774f-4bed-b1e7-1099f1ec97d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_div2']/div/div[7]/div/div/div/a</value>
      <webElementGuid>ec34ac60-f5e4-479a-b101-d385ed551ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agregar')]</value>
      <webElementGuid>739703b7-2d9d-45a8-b3be-221a81e77fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto límite por oferta:'])[1]/following::a[1]</value>
      <webElementGuid>2741dafa-9195-4c55-bd17-093d352b2de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrador legitimado'])[2]/preceding::a[1]</value>
      <webElementGuid>24361d45-e853-426d-8992-0d11e1017f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar']/parent::*</value>
      <webElementGuid>c00dd611-f3d8-47bb-9080-67e0c64f67b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$datosAdministradorLegitimado$lnkAgregarPersona','')&quot;)]</value>
      <webElementGuid>030319eb-c048-4365-8fc9-37b7635c2d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]/div/div/div/a</value>
      <webElementGuid>e774afaa-d180-4143-a8dc-60e67c96fb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_datosAdministradorLegitimado_lnkAgregarPersona' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$datosAdministradorLegitimado$lnkAgregarPersona&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Agregar' or . = 'Agregar')]</value>
      <webElementGuid>ec02f490-e635-4797-89d8-e1e59ebe7c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
