<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNombre</name>
   <tag></tag>
   <elementGuidId>815a26a7-05fb-424e-880c-d4997ee6b781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_txtNombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@id,'Nombre')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dce376c1-cbf1-4281-9f80-c6aea0b0b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosAdministradorLegitimado$txtNombre</value>
      <webElementGuid>6ab80f43-50b3-4349-9b16-4d17407de3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93e89403-dae4-4fc6-bc02-32beb085479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>25a3d606-2306-4b02-9f09-5f8f5c8d9757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_txtNombre</value>
      <webElementGuid>c73582c2-57f1-40b9-bb6a-4b6bc5a9ccee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef46548f-d54a-4fdb-ae6a-a8b3cea8d0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_txtNombre&quot;)</value>
      <webElementGuid>7135a1bd-72ad-49be-b7de-f90b8ac8b487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosAdministradorLegitimado_txtNombre']</value>
      <webElementGuid>b12ce956-c2dc-4ef3-b66e-aff488c0698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_DivNombre']/input</value>
      <webElementGuid>d29a949d-09db-4f71-81f8-b480a319b4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e187fdfe-01f0-4208-95ec-705393ea9b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosAdministradorLegitimado$txtNombre' and @type = 'text' and @id = 'ctl00_CPH1_datosAdministradorLegitimado_txtNombre']</value>
      <webElementGuid>c23a594f-01cf-4a01-982e-028851404a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
