<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputMontoLimiteOfertar</name>
   <tag></tag>
   <elementGuidId>f5857d82-f20c-46ca-b447-26b7e75d6c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'rbLimiteOfertarNo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bade4a6a-6327-4092-93fb-aafc222b6ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarNo</value>
      <webElementGuid>8da98a4c-2626-4d18-9b00-357c76d336fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ac9b0d1c-9e03-4eef-8f17-83e2fce5d6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosAdministradorLegitimado$rbLimiteOfertar</value>
      <webElementGuid>067aacd3-eee0-44f4-a081-dd7e1a14e790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbLimiteOfertarNo</value>
      <webElementGuid>63cdd034-1e0f-4640-a62d-f096bcb4d300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: HabilitarMontoLimiteOferta('ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarSi');</value>
      <webElementGuid>0acfd07b-d404-4f29-b577-c33a1cfb03eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarNo&quot;)</value>
      <webElementGuid>c5bb849e-3966-42b0-b7ab-61b88d2d307b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarNo']</value>
      <webElementGuid>c5afce26-53bc-41ae-a237-2c597c8860cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_DivCheckLimiteOfertar']/input[2]</value>
      <webElementGuid>42d2241d-4914-49c3-9364-c8d6f1521e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input[2]</value>
      <webElementGuid>aacfa1e7-e7d2-4a3e-98d3-f8d06ebf17bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_datosAdministradorLegitimado_rbLimiteOfertarNo' and @type = 'radio' and @name = 'ctl00$CPH1$datosAdministradorLegitimado$rbLimiteOfertar']</value>
      <webElementGuid>92d04d33-45e1-47d2-97e3-4190548b6750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
