<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCodigoPostal</name>
   <tag></tag>
   <elementGuidId>c7a96d73-17a4-413e-8fdb-02d32bb12571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_txtCodigoPostal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'CodigoPostal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51782007-8f5a-414c-a595-c6ebe853ab8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosAdministradorLegitimado$DireccionLegal$txtCodigoPostal</value>
      <webElementGuid>504e8e70-f56d-47d5-80c7-2fea7ae7197c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64c5b89b-9652-4776-a29f-1ad1bf9c7897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>d63807bd-6633-47d4-b179-d5c2d46b1f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_txtCodigoPostal</value>
      <webElementGuid>3e63fb9b-9d37-4d2c-8bd1-c0429f92f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c75023f-8842-4b7c-9cc2-c099f6a57344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_txtCodigoPostal&quot;)</value>
      <webElementGuid>e5d37bc1-cccc-4190-b125-b286833d6707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_txtCodigoPostal']</value>
      <webElementGuid>0389864e-c73e-49f7-8681-301083979ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_DivCodigoPostal']/input</value>
      <webElementGuid>7ee5844d-a304-4483-9150-6931223ddbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>36059a93-920a-4c01-be0f-03d2d4029d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosAdministradorLegitimado$DireccionLegal$txtCodigoPostal' and @type = 'text' and @id = 'ctl00_CPH1_datosAdministradorLegitimado_DireccionLegal_txtCodigoPostal']</value>
      <webElementGuid>5bd0108e-0553-4542-885b-7f98dcfd2166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
