<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNumeroDocumento</name>
   <tag></tag>
   <elementGuidId>90dce130-a6c2-4755-b39c-a00e568a13d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c44899a-19b6-41bd-b998-f21d30ba3d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosAdministradorLegitimado$txtNumeroDocumento</value>
      <webElementGuid>fe299a15-2d01-41f0-a260-429599778641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02a7ee7d-f6ab-42a3-8065-d7c6d22330ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e8956d42-6ace-44cc-8c09-19e4d7f884aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento</value>
      <webElementGuid>1b3cf47e-75c5-4d71-8ff0-c64c8169d9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7fb5be4d-b927-42f9-aa84-cae270db2094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento&quot;)</value>
      <webElementGuid>12039df3-c2a0-4d18-9554-79056deea5a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento']</value>
      <webElementGuid>4e1bde56-b2a2-406f-929a-be0261d2313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_DivNumeroDocumento']/input</value>
      <webElementGuid>1eb000d8-a2f5-409c-884f-251746007a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>c43ca0b3-2b6e-425e-9dee-10568e98ff30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosAdministradorLegitimado$txtNumeroDocumento' and @type = 'text' and @id = 'ctl00_CPH1_datosAdministradorLegitimado_txtNumeroDocumento']</value>
      <webElementGuid>a53e28cc-556c-48a8-87a4-3cf1d631b801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
