<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccionarCIDNILCLEPasaporte</name>
   <tag></tag>
   <elementGuidId>d8be0c31-109b-410a-aad9-ba9f55165f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08f809c9-8613-4bd6-a1dd-bd624fb44937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosAdministradorLegitimado$ddlTipoDocumento</value>
      <webElementGuid>88df9a10-9a26-48ca-be2e-a6d27f18ebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento</value>
      <webElementGuid>47a7237e-ee70-4294-a2d6-cba7eafa5dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd7a4bde-8937-4b63-bf8f-b6993f75296a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	</value>
      <webElementGuid>89b505c6-8b79-45b4-9df8-e37d760ccf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento&quot;)</value>
      <webElementGuid>74ffd797-b03f-4cb7-9de0-1f092d7cb8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento']</value>
      <webElementGuid>3133a147-3912-4730-b912-72590d388985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosAdministradorLegitimado_DivTipoDocumento']/select</value>
      <webElementGuid>4ae4ab14-1c3f-46f8-a42f-4d91f0b829af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo documento:'])[1]/following::select[1]</value>
      <webElementGuid>a14cdd6f-0fd7-4b36-8b47-cfd436cd2e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completar'])[6]/preceding::select[1]</value>
      <webElementGuid>c1faf429-04a2-4dde-972e-5b553dd8091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>441d96fa-82e6-4342-9809-776d2ab8041c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$datosAdministradorLegitimado$ddlTipoDocumento' and @id = 'ctl00_CPH1_datosAdministradorLegitimado_ddlTipoDocumento' and (text() = '
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	' or . = '
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	')]</value>
      <webElementGuid>7a714a5c-9528-4e38-82fb-1229c3288fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
