<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CompletarDatos</name>
   <tag></tag>
   <elementGuidId>85ad9077-4f9d-49f9-a872-c07ed377b93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionIndice15_hlDatos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_seccionIndice15_hlDatos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33ebcf33-b8a2-43c2-991a-eae10ae228f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionIndice15_hlDatos</value>
      <webElementGuid>b8193fc4-a171-4b4c-a820-70cec954254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>ccbf4ba7-9859-40ee-993e-2fa61917ac13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>IngresarItemConvenioMarco.aspx?qs=gNmSk4OV4EWw59Naj0s3PiOhO0HRF5HtMkdmNDoYnl/igyFqQR|snoIZaHGxgs9aiHM24ksI3H34DydyRt6oh5YwDrnG2Tdof7v9KGLQuIzRFvMQwqmfP7UiQPrzaCpMB0gwf|O4J5V1Wgkqp5Ri20lEJRiaBZqbX|0lmZIbRHUpqfsGO|Oq7VifNp0hMWun8KEB7POyl2Y=</value>
      <webElementGuid>b65b4d42-3a72-4d22-8230-9d9b6f0c22d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar datos</value>
      <webElementGuid>40f59a46-6054-46af-870a-0937ddacdcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionIndice15_hlDatos&quot;)</value>
      <webElementGuid>006759a4-beb1-40ef-9f24-9e9be4b291fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_seccionIndice15_hlDatos']</value>
      <webElementGuid>ef14a8b2-ea6c-439a-81f9-100034fae2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr[2]/td[2]/span[2]/a</value>
      <webElementGuid>c5062b48-b0fd-4412-bb20-53e7fe8ae7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Completar datos')]</value>
      <webElementGuid>a55b9064-f9e5-4683-aec1-543872a93d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos obligatorios'])[1]/following::a[1]</value>
      <webElementGuid>6e16180f-1507-49e7-b403-c594c5279b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta completar índice Nº 1'])[1]/preceding::a[1]</value>
      <webElementGuid>c863d46d-6c1f-4e5f-9adc-9e97bdb4362c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[2]/preceding::a[1]</value>
      <webElementGuid>858fc685-95b3-44c8-8860-85137959c423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completar datos']/parent::*</value>
      <webElementGuid>9f636803-1d4e-44e3-b870-ab8f714db761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'IngresarItemConvenioMarco.aspx?qs=gNmSk4OV4EWw59Naj0s3PiOhO0HRF5HtMkdmNDoYnl/igyFqQR|snoIZaHGxgs9aiHM24ksI3H34DydyRt6oh5YwDrnG2Tdof7v9KGLQuIzRFvMQwqmfP7UiQPrzaCpMB0gwf|O4J5V1Wgkqp5Ri20lEJRiaBZqbX|0lmZIbRHUpqfsGO|Oq7VifNp0hMWun8KEB7POyl2Y=')]</value>
      <webElementGuid>0e860f51-1a0c-499e-b468-84fe6b0dd0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span[2]/a</value>
      <webElementGuid>161ba7a4-e699-48ad-a2b0-35e6b6d7e61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_seccionIndice15_hlDatos' and @href = 'IngresarItemConvenioMarco.aspx?qs=gNmSk4OV4EWw59Naj0s3PiOhO0HRF5HtMkdmNDoYnl/igyFqQR|snoIZaHGxgs9aiHM24ksI3H34DydyRt6oh5YwDrnG2Tdof7v9KGLQuIzRFvMQwqmfP7UiQPrzaCpMB0gwf|O4J5V1Wgkqp5Ri20lEJRiaBZqbX|0lmZIbRHUpqfsGO|Oq7VifNp0hMWun8KEB7POyl2Y=' and (text() = 'Completar datos' or . = 'Completar datos')]</value>
      <webElementGuid>bfb5c5eb-7d4c-4688-82ea-193744049f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
