<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AcondicionamientoEmbalaje</name>
   <tag></tag>
   <elementGuidId>bce758e9-27f8-4834-af92-78d7e079961f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtAcondicionamiento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtAcondicionamiento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>84c2d56b-d753-489a-b0c4-9718200d0c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtAcondicionamiento</value>
      <webElementGuid>da803de1-8edc-462e-9289-65af5d7443ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dae516d9-e89d-4173-b3c3-0fce9a144dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>489f6ad0-f5e7-45f9-89b8-8f87492d2f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtAcondicionamiento</value>
      <webElementGuid>ee6c0263-2138-4d09-80db-0822eb475781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:cortaLargoMaximo('ctl00_CPH1_txtAcondicionamiento',255);</value>
      <webElementGuid>3a633b4c-6970-437e-a809-98c164f3858f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtAcondicionamiento&quot;)</value>
      <webElementGuid>babdf17b-ab26-4b87-bb6a-21bdeebeccd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtAcondicionamiento']</value>
      <webElementGuid>7ed3e384-7a3c-4824-8712-700eba8f401a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[11]/table/tbody/tr[10]/td[2]/textarea</value>
      <webElementGuid>25c6264a-6033-491c-af60-0d6a8a544620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/textarea</value>
      <webElementGuid>33f40933-d208-4e21-a3dd-19fd1722cfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtAcondicionamiento' and @id = 'ctl00_CPH1_txtAcondicionamiento']</value>
      <webElementGuid>84cc2d6f-1ee7-4430-a96b-067d2f42e029</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
