<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Atencin</name>
   <tag></tag>
   <elementGuidId>6a571655-594e-4b1e-894a-b6647eb72bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='transition-modal-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h2[(text() = '¡Atención!' or . = '¡Atención!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b4c71f70-bd4b-4cd2-8b6b-90e1736fdd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h6</value>
      <webElementGuid>14aaf59f-4429-4d52-adcc-dd422f0f88a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-title</value>
      <webElementGuid>1b7dfd83-404f-47c6-9ef5-cb3d2fd48d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Atención!</value>
      <webElementGuid>5effcff8-1d76-469d-beef-b975e04aea1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-title&quot;)</value>
      <webElementGuid>a6aac5de-b0c5-4822-8d32-419907225335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='transition-modal-title']</value>
      <webElementGuid>5dfde9f8-bfeb-4485-b5aa-e7bdd9ad8580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalObsba']/h2</value>
      <webElementGuid>bdcec87c-d9b0-487c-9197-77aabadae5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'transition-modal-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>18377454-0a6b-4ac2-9bd7-dd090d19e6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h2[1]</value>
      <webElementGuid>e7fe01d1-8284-4015-98fc-6771eb97d647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Atención!']/parent::*</value>
      <webElementGuid>5ae96722-7a0e-4e7d-8564-dd591f1c4b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>0d870a44-a214-426f-838a-4546d1ddd020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'transition-modal-title' and (text() = '¡Atención!' or . = '¡Atención!')]</value>
      <webElementGuid>2fcb5965-3732-4a5b-9618-bae39fd7b77d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
