<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Autorizar</name>
   <tag></tag>
   <elementGuidId>2e6be876-2c10-4712-a437-43f315cd541e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal_ctl08_lnkAccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Autorizar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>216fe27e-2e82-4722-ade9-f852ca47c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal_ctl08_lnkAccion</value>
      <webElementGuid>d2a5f8ae-8586-47c9-a1a8-9ae08624caa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>765a1ee4-4121-4830-8c37-20e94cad85db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UC_BandejaTareasPersonal$TablaTareaProcesoCompra$gvTareasBandejaPersonal$ctl08$lnkAccion&quot;, &quot;&quot;, false, &quot;&quot;, &quot;/EVALUACIONOFERTA/PreAdjudicarAutorizarDictamen.aspx?qs=Gbut9cInK76mTwJi4qWAbM929DgTuX6Lf8KSux8v1aSj2wUX1o1KNlRo6yzisCUi4dW20MN0L1q60TgfBCBJqNjNFCZ|SI33&quot;, false, true))</value>
      <webElementGuid>818dd275-677e-4de2-8036-066bb86ea14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autorizar</value>
      <webElementGuid>36e1f3ed-49bf-4d05-a681-d8e835c99ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal_ctl08_lnkAccion&quot;)</value>
      <webElementGuid>ad961484-a609-4543-9726-59ccb5b661f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal_ctl08_lnkAccion']</value>
      <webElementGuid>c3389500-f942-4abc-a76b-48d7ffca13ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal']/tbody/tr[8]/td[7]/a</value>
      <webElementGuid>f8570b77-8222-4e18-b7fc-d2e8eb2e5d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Autorizar')]</value>
      <webElementGuid>311b1469-4af5-4d2d-8489-628583fe3872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorización de dictamen'])[1]/following::a[1]</value>
      <webElementGuid>0f5c809c-64dc-448e-86c2-349a32e0ba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Test 20220831'])[3]/following::a[1]</value>
      <webElementGuid>ae215bf9-a9c1-4439-a024-c24cdac06839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Test 20220830'])[6]/preceding::a[3]</value>
      <webElementGuid>e1276c94-7f5a-4083-a9c6-5ea84d85dc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar pliego'])[4]/preceding::a[3]</value>
      <webElementGuid>bc3e27a4-835a-42cd-9dad-1e4edbe397e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autorizar']/parent::*</value>
      <webElementGuid>1cde3acc-1af7-4ffc-a54d-a197f31437b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UC_BandejaTareasPersonal$TablaTareaProcesoCompra$gvTareasBandejaPersonal$ctl08$lnkAccion&quot;, &quot;&quot;, false, &quot;&quot;, &quot;/EVALUACIONOFERTA/PreAdjudicarAutorizarDictamen.aspx?qs=Gbut9cInK76mTwJi4qWAbM929DgTuX6Lf8KSux8v1aSj2wUX1o1KNlRo6yzisCUi4dW20MN0L1q60TgfBCBJqNjNFCZ|SI33&quot;, false, true))')]</value>
      <webElementGuid>a6171308-215e-4d9e-85a1-022090a84e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[2]/div/div/div/table/tbody/tr[8]/td[7]/a</value>
      <webElementGuid>817fd7f1-57bf-4480-a397-5f7a215e4977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UC_BandejaTareasPersonal_TablaTareaProcesoCompra_gvTareasBandejaPersonal_ctl08_lnkAccion' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UC_BandejaTareasPersonal$TablaTareaProcesoCompra$gvTareasBandejaPersonal$ctl08$lnkAccion&quot;, &quot;&quot;, false, &quot;&quot;, &quot;/EVALUACIONOFERTA/PreAdjudicarAutorizarDictamen.aspx?qs=Gbut9cInK76mTwJi4qWAbM929DgTuX6Lf8KSux8v1aSj2wUX1o1KNlRo6yzisCUi4dW20MN0L1q60TgfBCBJqNjNFCZ|SI33&quot;, false, true))' and (text() = 'Autorizar' or . = 'Autorizar')]</value>
      <webElementGuid>ca03816e-8047-497b-9aa1-06a5281c58c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
