<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Justificacion</name>
   <tag></tag>
   <elementGuidId>5d9bf4df-8277-4e01-9547-14786a3b5ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtJustificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtJustificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>87f01ea2-6c15-447f-99dc-06eadb030efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtJustificacion</value>
      <webElementGuid>0a3269fa-bdfa-410e-b9fb-120182ea121f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtJustificacion</value>
      <webElementGuid>8da1eb1f-5609-4fa2-98b3-561119ebb6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>33f6f758-6096-40c5-a84c-41475e8e4324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3000</value>
      <webElementGuid>3d3b40b7-d06b-4b94-b9c0-ff9dad2993d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ada72898-ad7f-4cb6-96c1-ece93563adb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtJustificacion&quot;)</value>
      <webElementGuid>4e6bf726-8a42-4210-8365-cfd081e2e720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtJustificacion']</value>
      <webElementGuid>c1cc6e55-da73-4ac9-ba0d-0d2c41f5b5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivJustificacion']/textarea</value>
      <webElementGuid>314aef63-921e-4494-ae54-80daf6be2c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>22b9fe96-e517-4d1f-aa6e-bdf541bb8fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtJustificacion' and @id = 'ctl00_CPH1_txtJustificacion']</value>
      <webElementGuid>a677e500-4100-4e34-bc4a-d5caf06cc42c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
