<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Completar Datos2</name>
   <tag></tag>
   <elementGuidId>c15c9535-5e73-4387-8a62-1428a17f0cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_SeccionItems_hlDatos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_SeccionItems_hlDatos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a091720-a38f-4c20-915c-f76c7fc17878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_SeccionItems_hlDatos</value>
      <webElementGuid>98d5694c-7020-47bf-98fc-e09f6269a931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>93092f62-77a4-476d-a6d9-d7d06fbb00c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>aceefb9d-feca-4dec-ab5b-cba7e81ba0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar Datos</value>
      <webElementGuid>2d6a4721-89fd-4743-8a2d-7769774efd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_SeccionItems_hlDatos&quot;)</value>
      <webElementGuid>94e57e65-54be-400e-8ec3-1c0cafe06666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_SeccionItems_hlDatos']</value>
      <webElementGuid>563d8153-64a5-4704-ac2b-2c2010250285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[3]/table/tbody/tr[2]/td[2]/span[2]/a</value>
      <webElementGuid>75f8c5b0-04d8-47ad-b0cb-87caf62aa82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Completar Datos')])[2]</value>
      <webElementGuid>6b21155a-a5b5-46ce-befd-c6ef6750faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta completar índice 1'])[1]/following::a[1]</value>
      <webElementGuid>3cd0ebd2-0beb-4909-a278-ec756e4ade84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='**Productos y Servicios**'])[1]/preceding::a[1]</value>
      <webElementGuid>8ce02bd5-55f4-4df4-9166-30abee152167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span[2]/a</value>
      <webElementGuid>e65a1ae9-f641-42ad-b72f-1253513682bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_SeccionItems_hlDatos' and (text() = 'Completar Datos' or . = 'Completar Datos')]</value>
      <webElementGuid>0ab00cd5-6817-43f3-ab95-ccf431d6714f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
