<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Completar Datos3</name>
   <tag></tag>
   <elementGuidId>00965c89-4263-405f-bd4b-c45461d815b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_SeccionDetalleEntrega_hlDatos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_SeccionDetalleEntrega_hlDatos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c35626ab-92a5-40d6-8a00-9eb7729211b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_SeccionDetalleEntrega_hlDatos</value>
      <webElementGuid>5cb0a44d-419b-4a61-a3e2-753873bcb892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>5da0c809-20ef-4239-881d-a1636750c3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>09dcba7b-04df-4b91-8055-dd49fb8961d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar Datos</value>
      <webElementGuid>91ac4e70-0747-4eab-b94d-114106e5a07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_SeccionDetalleEntrega_hlDatos&quot;)</value>
      <webElementGuid>4db53b59-0e36-4307-8b15-d147ae8986af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_SeccionDetalleEntrega_hlDatos']</value>
      <webElementGuid>b3c37efe-a9d9-4d4c-992f-d3a8e313a407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[3]/table/tbody/tr[3]/td[2]/span[2]/a</value>
      <webElementGuid>3a7fa74f-8d0a-414f-97a0-0221d453b82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Completar Datos')])[3]</value>
      <webElementGuid>cbb7bcfd-43c9-48cd-8b68-bab2978a81c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta completar índice 2'])[1]/following::a[1]</value>
      <webElementGuid>4543c87c-e175-481f-a48e-78fb27ba2ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='**Lugar y fecha de entrega**'])[1]/preceding::a[1]</value>
      <webElementGuid>815eb205-c4a0-4689-b0e8-a24365ccc7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span[2]/a</value>
      <webElementGuid>a7efb679-811c-44ea-b3ee-f80e566a7347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_SeccionDetalleEntrega_hlDatos' and (text() = 'Completar Datos' or . = 'Completar Datos')]</value>
      <webElementGuid>31253168-9c41-4ae9-b89d-b26b7aa5f229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
