<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuarios AutorizadoresAgregarButton</name>
   <tag></tag>
   <elementGuidId>318253df-a810-4db5-892f-74129f690dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCAutorizadorSG_btnAgregar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCAutorizadorSG_btnAgregar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8063009d-a832-40e6-8075-9f802d974c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c5d06d59-80fb-4af4-bc02-3fe9348f9bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCAutorizadorSG$btnAgregar</value>
      <webElementGuid>bf0edcbe-f9cb-4336-9682-962f77c42a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCAutorizadorSG_btnAgregar</value>
      <webElementGuid>dd175ef9-4014-4dbe-9ad7-678144f9773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/botones/b_int_agregar.gif</value>
      <webElementGuid>33e6f194-37cb-41f9-95ae-9febd5e98e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCAutorizadorSG_btnAgregar&quot;)</value>
      <webElementGuid>2067bdd3-66e0-4445-adf6-6284930df08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCAutorizadorSG_btnAgregar']</value>
      <webElementGuid>64f4f4f7-f9fa-430c-a35c-4cf5d8a9f6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_UCAutorizadorSG_uplSelectorUsuario']/div[2]/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>b3ae4760-5099-4b71-995c-f1ce3d501dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>49a0cb26-0c1f-4a2f-861b-14de296f4d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$UCAutorizadorSG$btnAgregar' and @id = 'ctl00_CPH1_UCAutorizadorSG_btnAgregar' and @src = '/App_Themes/styles-viejo/imagenes/botones/b_int_agregar.gif']</value>
      <webElementGuid>fc3cdc05-c7a0-4a51-b075-4519b39e1ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
