<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_usuario</name>
   <tag></tag>
   <elementGuidId>f81eadfe-bfa0-4e30-be2d-9631924bf481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;1583&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='1583']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>592b70df-2224-4d27-b2f1-b3f11661d4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1583</value>
      <webElementGuid>3cf2058b-2ac7-4d7c-ab2d-1350f7654df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emilse Carmen Filippo</value>
      <webElementGuid>0961ebd3-8b49-4165-a641-29802014c132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCAutorizadorSG_lsbUsuarios&quot;)/option[3]</value>
      <webElementGuid>e80ffb99-f245-44c4-8eb1-17cca0d688bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='1583']</value>
      <webElementGuid>714e9459-c0b8-42ee-903a-2cad535f98bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_UCAutorizadorSG_lsbUsuarios']/option[3]</value>
      <webElementGuid>af4f5822-5220-430a-87e9-e9472c5f5108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios Autorizadores SG'])[1]/following::option[3]</value>
      <webElementGuid>d3efed6f-d182-403b-8119-1d23dc1c49c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios con rol Autorizador SG'])[1]/following::option[3]</value>
      <webElementGuid>daa92419-32cf-48f9-90e4-a99bd2ac85ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::option[46]</value>
      <webElementGuid>444612e2-914e-4b1b-93cc-534bb3176e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorizador SG seleccionado'])[1]/preceding::option[46]</value>
      <webElementGuid>ec74c77e-2a3d-48bd-9b27-fbee7ef52c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Emilse Carmen Filippo']/parent::*</value>
      <webElementGuid>e5f57056-b06d-45a5-80f9-fb9ed96e5dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option[3]</value>
      <webElementGuid>293f683b-ee10-492d-a219-4cbf8b7ca538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Emilse Carmen Filippo' or . = 'Emilse Carmen Filippo')]</value>
      <webElementGuid>9deb194a-9a58-4882-8d02-59addedbc2f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
