<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_itemPrecio1</name>
   <tag></tag>
   <elementGuidId>3d415a15-a9e4-41d1-b09e-1f0ceba44685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>519d762a-238d-44cf-a19e-210b7a441b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario</value>
      <webElementGuid>74ec9e02-f333-4e26-9a4e-fee0c11049b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1,00</value>
      <webElementGuid>2721463d-8725-455f-9ef3-660a5c32c84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario&quot;)</value>
      <webElementGuid>c2f06af9-c930-4700-83c1-1fa3be505d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario']</value>
      <webElementGuid>e6818dfd-ffa3-4e63-96a1-c6f252baca75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_gvIngresarItems_tccell0_10']/span[2]</value>
      <webElementGuid>ceb8bbd6-a966-4395-869d-6323cfe09916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[1]/following::span[1]</value>
      <webElementGuid>21b14e7d-fffa-4549-87eb-289f369c0049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[2]/preceding::span[1]</value>
      <webElementGuid>eb872423-160c-467b-b722-3681a8ac3902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAMILLA PARA CLINICA PEDIATRICA Estructura portante de caño de ac...'])[1]/preceding::span[5]</value>
      <webElementGuid>dacf03b5-5137-4f9c-8f0f-e2534673ffc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1,00']/parent::*</value>
      <webElementGuid>5f2f1065-c122-4c48-ae2a-4cf9933d0d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/span[2]</value>
      <webElementGuid>50c1b9ef-4d93-408b-968b-fe77b14155c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_gvIngresarItems_cell0_10_lblPrecioUnitario' and (text() = '1,00' or . = '1,00')]</value>
      <webElementGuid>403e10b8-82dd-493b-8ea2-7d11b6c69aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
