<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_itemMoneda2</name>
   <tag></tag>
   <elementGuidId>82d981c1-2ad5-4801-90fb-ae39697e9be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>896bba18-182f-4031-b7d5-50b1d1412f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario</value>
      <webElementGuid>38460570-ed22-4e3b-b0b7-8ccab9c90d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARS</value>
      <webElementGuid>ae2dcb42-9d70-4dbd-be7f-638a87f75dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario&quot;)</value>
      <webElementGuid>ded53467-91f5-4566-950a-7f01fb7bc60c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario']</value>
      <webElementGuid>b0411dd2-eef9-48cb-b4d4-34479b9d80f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_gvIngresarItems_tccell1_10']/span</value>
      <webElementGuid>faafc227-d8e9-42c8-be70-675b06a1914f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::span[2]</value>
      <webElementGuid>79877652-ec1f-425c-bb67-99f8170d7c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[4]/preceding::span[2]</value>
      <webElementGuid>d8dfca23-af18-477c-8090-1b6c0448935c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando'])[1]/preceding::span[4]</value>
      <webElementGuid>1ab80a4d-5f2d-4b27-8db1-8216ab71291b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/span</value>
      <webElementGuid>fd1dbc86-0fd0-4624-8e23-f2db966cf73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_gvIngresarItems_cell1_10_lblMonedaPrecioUnitario' and (text() = 'ARS' or . = 'ARS')]</value>
      <webElementGuid>f154e747-6cef-445a-90b6-cefcf48d2581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
