<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numero de solicitud de provisinVer</name>
   <tag></tag>
   <elementGuidId>978fce26-6a54-4297-ba8e-07189b29b5f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_btnVer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_btnVer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>265d4edc-842d-48dd-a32c-3e875e0f8831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ce02d5f3-e23b-41b0-a4b3-a2ec4553745d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$btnVer</value>
      <webElementGuid>78c7556e-da39-4d72-9f05-d7417a589858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_btnVer</value>
      <webElementGuid>c93f1fcf-2c6c-4460-896b-bf6142e2d44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/botones/b_int_ver.gif</value>
      <webElementGuid>42d40269-775e-448d-93a5-2151b9af070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>8aff8123-d319-4824-a884-e47035dbdf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:ValidarVer();return false;</value>
      <webElementGuid>77993dcb-0fdd-4077-afaf-2e42c0bc0b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_btnVer&quot;)</value>
      <webElementGuid>88389d10-eb54-4f38-8cd4-1c373cc38923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_btnVer']</value>
      <webElementGuid>1878cac9-d96d-4132-a260-7e5968aa2fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div/div[2]/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>20615059-5a97-4c0e-a290-ee3d538d97f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>88d27628-26e1-4c1d-af86-5c9c7b9a94b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$btnVer' and @id = 'ctl00_CPH1_btnVer' and @src = '/App_Themes/styles-viejo/imagenes/botones/b_int_ver.gif']</value>
      <webElementGuid>374752dc-e6a9-4629-ae79-1b4434ffcf50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
