<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_linkOca</name>
   <tag></tag>
   <elementGuidId>f5120bfa-3a33-4cb2-9b5d-bd3ffe351979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f51bd52-013c-4efd-b019-0abe033e640e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA</value>
      <webElementGuid>7d9c9e32-2971-42b5-986c-77c44ee632a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>08ace468-7c24-44ab-9df0-7eb57288c11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$gridResultado$cell0_0$lnkNumeroOCA&quot;, &quot;&quot;, false, &quot;&quot;, &quot;VistaPreviaOrdenCompraAbierta.aspx?qs=BQoBkoMoEhxECWJBLDS0q9gTwmFPRkhzdMmN0C/t3E45eztMNIb0d3MyAZc10VXtGAHgR|lxg2pPZSFSZ8ywBGc673NOKpHIjRXGxmBDVKSyGMJ7tISfPUkAQtiPHb2s8I0FkHhxiGTo3DHsbwd4J29terQcAer3hQsJlnsXXpP3aOUSfyn0TYqg38DA4VIeJlzHHznXlVT9q8c/lut3N9B49lkJ5DOso|HaWKiRq|ebfUfbqlnhQhMvW|OibjE4H0MSuhuBq5|5ak1AO8Zc8mctcaj|wWPEbonwd9ifh7q49hI6UyuHmvVIE5LWdgGI7JYpUETNGc|Odea2Y34R7cr1zdn8rMkEC3jOIFL1p3C1xlcw0yDk5JmQOXdGjEpTS8MxWWi/gFJeazLFcDHJ9|2LFO|7U129GQHFdcUNRZfNr3saqHd3VL3p7EQWSc49nfscNzM9CPp8UJKVGNClPfVSt8MnnPXwwgjQJwsebWquqsyW9iowYi|HcsAQ1ySfRr|QRgK8TCkqgkcTTGOiniVdFQf5khVXrS8P9vm6BpFSMsYMpDKSvkO|hIFoLTca9lBn16zpVrPcRSv7w5k7WeluVbiy/FaK/xJOpy9KDQ3/C3CpFEyc5loYBrih|d2SMdp2aB9NvJ4=&quot;, false, true))</value>
      <webElementGuid>7cb7170f-4592-4f2c-b5d2-a5f5db71c85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>401-0272-OCA25</value>
      <webElementGuid>4fd39b34-2a2e-4455-8548-b77b11514f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA&quot;)</value>
      <webElementGuid>2fec4f41-a0c5-442e-be62-088971aade17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA']</value>
      <webElementGuid>6efd99a1-51b6-4750-bc48-5358503a335c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_gridResultado_tccell0_0']/a</value>
      <webElementGuid>53d6bd4d-9066-4a8a-a76e-4a27f74d3064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'401-0272-OCA25')]</value>
      <webElementGuid>eb00aa1f-4087-4397-9920-ca2316b0162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acciones'])[1]/following::a[1]</value>
      <webElementGuid>e306ae4c-0100-4ab2-8e45-76299cdc956a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre del proceso de compra'])[1]/following::a[1]</value>
      <webElementGuid>de11deec-7051-4b74-af8a-4ef41f622481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original'])[2]/preceding::a[1]</value>
      <webElementGuid>5dbb13df-2c49-494f-91fb-bedba5d62547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfeccionado'])[2]/preceding::a[1]</value>
      <webElementGuid>7a1c9c5a-034d-4f86-b61b-fc71130e54c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='401-0272-OCA25']/parent::*</value>
      <webElementGuid>e33b6399-76ee-4898-ba14-cfb76e9f3ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$gridResultado$cell0_0$lnkNumeroOCA&quot;, &quot;&quot;, false, &quot;&quot;, &quot;VistaPreviaOrdenCompraAbierta.aspx?qs=BQoBkoMoEhxECWJBLDS0q9gTwmFPRkhzdMmN0C/t3E45eztMNIb0d3MyAZc10VXtGAHgR|lxg2pPZSFSZ8ywBGc673NOKpHIjRXGxmBDVKSyGMJ7tISfPUkAQtiPHb2s8I0FkHhxiGTo3DHsbwd4J29terQcAer3hQsJlnsXXpP3aOUSfyn0TYqg38DA4VIeJlzHHznXlVT9q8c/lut3N9B49lkJ5DOso|HaWKiRq|ebfUfbqlnhQhMvW|OibjE4H0MSuhuBq5|5ak1AO8Zc8mctcaj|wWPEbonwd9ifh7q49hI6UyuHmvVIE5LWdgGI7JYpUETNGc|Odea2Y34R7cr1zdn8rMkEC3jOIFL1p3C1xlcw0yDk5JmQOXdGjEpTS8MxWWi/gFJeazLFcDHJ9|2LFO|7U129GQHFdcUNRZfNr3saqHd3VL3p7EQWSc49nfscNzM9CPp8UJKVGNClPfVSt8MnnPXwwgjQJwsebWquqsyW9iowYi|HcsAQ1ySfRr|QRgK8TCkqgkcTTGOiniVdFQf5khVXrS8P9vm6BpFSMsYMpDKSvkO|hIFoLTca9lBn16zpVrPcRSv7w5k7WeluVbiy/FaK/xJOpy9KDQ3/C3CpFEyc5loYBrih|d2SMdp2aB9NvJ4=&quot;, false, true))')]</value>
      <webElementGuid>1ca69745-09ca-4108-b3f7-7c3d5d37954d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>196ab2ce-b93f-440c-8454-a8b0962b105f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_gridResultado_cell0_0_lnkNumeroOCA' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$gridResultado$cell0_0$lnkNumeroOCA&quot;, &quot;&quot;, false, &quot;&quot;, &quot;VistaPreviaOrdenCompraAbierta.aspx?qs=BQoBkoMoEhxECWJBLDS0q9gTwmFPRkhzdMmN0C/t3E45eztMNIb0d3MyAZc10VXtGAHgR|lxg2pPZSFSZ8ywBGc673NOKpHIjRXGxmBDVKSyGMJ7tISfPUkAQtiPHb2s8I0FkHhxiGTo3DHsbwd4J29terQcAer3hQsJlnsXXpP3aOUSfyn0TYqg38DA4VIeJlzHHznXlVT9q8c/lut3N9B49lkJ5DOso|HaWKiRq|ebfUfbqlnhQhMvW|OibjE4H0MSuhuBq5|5ak1AO8Zc8mctcaj|wWPEbonwd9ifh7q49hI6UyuHmvVIE5LWdgGI7JYpUETNGc|Odea2Y34R7cr1zdn8rMkEC3jOIFL1p3C1xlcw0yDk5JmQOXdGjEpTS8MxWWi/gFJeazLFcDHJ9|2LFO|7U129GQHFdcUNRZfNr3saqHd3VL3p7EQWSc49nfscNzM9CPp8UJKVGNClPfVSt8MnnPXwwgjQJwsebWquqsyW9iowYi|HcsAQ1ySfRr|QRgK8TCkqgkcTTGOiniVdFQf5khVXrS8P9vm6BpFSMsYMpDKSvkO|hIFoLTca9lBn16zpVrPcRSv7w5k7WeluVbiy/FaK/xJOpy9KDQ3/C3CpFEyc5loYBrih|d2SMdp2aB9NvJ4=&quot;, false, true))' and (text() = '401-0272-OCA25' or . = '401-0272-OCA25')]</value>
      <webElementGuid>528f7532-a8f0-43f8-8eea-75a512c00f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
