<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Plus2</name>
   <tag></tag>
   <elementGuidId>438b7b37-8602-4927-b023-d5a18ffc972e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54596242-7d3e-4332-ae1e-a600eba74138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito</value>
      <webElementGuid>22fc8682-39d1-4d7e-ae03-0235a14a4ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-plus</value>
      <webElementGuid>fa6cb103-c6bb-422c-a65c-0b0a8b5358b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito&quot;)</value>
      <webElementGuid>c8070ea0-0036-4c54-bfb2-5c3126585e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito']</value>
      <webElementGuid>db5d2f88-fff9-46dc-9815-5861af246779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_rptRenglonesCabecera_ctl01_aAcordion']/div/div/span</value>
      <webElementGuid>887ec463-edfc-449a-9b01-1077be74c277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/div/span</value>
      <webElementGuid>076dccf4-5e4f-4495-ab96-103080233fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_rptRenglonesCabecera_ctl01_spnSimbolito']</value>
      <webElementGuid>7d51b4bc-97d4-4671-ab64-b482984a57a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
