<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnIngresarCantidadParametrizado</name>
   <tag></tag>
   <elementGuidId>42e85f03-564e-4cf9-b200-4c3324911b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptRenglonPliego_ctl00_UCRenglon_lnkIngresarCantidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@id,'IngresarCantidad')])[${renglon}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ead57d1f-2800-4bba-a187-af6a05441a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b18e9cae-0f9e-4b0f-968b-054b6e200c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptRenglonPliego$ctl00$UCRenglon$lnkIngresarCantidad</value>
      <webElementGuid>8c735a0b-3e2b-4457-aa60-ef488102d469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptRenglonPliego_ctl00_UCRenglon_lnkIngresarCantidad</value>
      <webElementGuid>789003b3-8567-4ec7-8feb-d7103202bbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingresar Cantidad</value>
      <webElementGuid>b52e4f6c-2bd4-42ce-9bcf-b59e5f674661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_ingre_solic_modif_plieg.gif</value>
      <webElementGuid>7918ec6c-70e0-47d0-8dfb-633aa47e04a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:IngresarCantidad(this);return false;</value>
      <webElementGuid>a248fe11-7d56-49ae-90e4-7265ad73f12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptRenglonPliego_ctl00_UCRenglon_lnkIngresarCantidad&quot;)</value>
      <webElementGuid>7af3a71b-6229-4591-b50c-776907f64950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptRenglonPliego_ctl00_UCRenglon_lnkIngresarCantidad']</value>
      <webElementGuid>c1b610d5-6490-4499-a0bb-023e100c84c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/table/thead/tr[2]/td[6]/input</value>
      <webElementGuid>6dede3ad-b5b2-4ec5-8273-fe62e8b4fc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>504127b3-2eb4-4153-bd6a-a424f7b9d0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$rptRenglonPliego$ctl00$UCRenglon$lnkIngresarCantidad' and @id = 'ctl00_CPH1_rptRenglonPliego_ctl00_UCRenglon_lnkIngresarCantidad' and @title = 'Ingresar Cantidad' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_ingre_solic_modif_plieg.gif']</value>
      <webElementGuid>b77853b5-04a8-44d4-ab68-b1781cfe11d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
