<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkRecomendarParametrizado</name>
   <tag></tag>
   <elementGuidId>53c70689-a598-41eb-8fbd-e7c2c73d4538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptOfertas_ctl00_UCOferta_OfertaSeleccionada</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@id,'OfertaSeleccionada')])[${oferta}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5db62393-07a8-415b-baf2-54a7a3fc345e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptOfertas_ctl00_UCOferta_OfertaSeleccionada</value>
      <webElementGuid>cf45de1e-9442-4b81-bb0a-b541b19a92bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>921ac09b-9257-470e-b9ca-11c59848db17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptOfertas$ctl00$UCOferta$OfertaSeleccionada</value>
      <webElementGuid>8f344375-d604-429e-b703-f5fc35f3b6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckClickOfertaSeleccionada(this);</value>
      <webElementGuid>b1c09f6a-7235-40aa-acfb-c6328666f91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptOfertas_ctl00_UCOferta_OfertaSeleccionada&quot;)</value>
      <webElementGuid>2cc45e63-9892-46dd-8402-4778402eb7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptOfertas_ctl00_UCOferta_OfertaSeleccionada']</value>
      <webElementGuid>4ca860e5-837c-4666-96b0-cd075e66952a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_rptOfertas_ctl00_UCOferta_DivCuerpo']/div/div/span/input</value>
      <webElementGuid>82169cc0-e817-48c7-b09d-0b0b991f43c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7a66cb2c-6c0b-4a91-add2-6fe670e104c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rptOfertas_ctl00_UCOferta_OfertaSeleccionada' and @type = 'checkbox' and @name = 'ctl00$CPH1$rptOfertas$ctl00$UCOferta$OfertaSeleccionada']</value>
      <webElementGuid>6dc29050-d12b-4214-8b4c-c2b0130ae560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
