<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_AceptaActualizacionPreciosNo</name>
   <tag></tag>
   <elementGuidId>86c1b18b-84e8-4369-90d0-3cc496765f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblAceptaProrroga_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rblAceptaActualizacionDePrecios_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblAceptaProrroga_0']</value>
      <webElementGuid>242fa07d-1bac-4355-8a3a-c264e7995166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblAceptaProrroga']/tbody/tr/td/input</value>
      <webElementGuid>e932c875-c8f9-414f-8911-96dd4ba490d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>194e51c4-ede3-4a7a-aff9-76290325c4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblAceptaProrroga_0' and @type = 'radio' and @name = 'ctl00$CPH1$rblAceptaProrroga']</value>
      <webElementGuid>852248fb-3a2a-4770-baf3-dd00974040b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblAceptaProrroga_1']</value>
      <webElementGuid>5982a679-a3ba-4b46-a2fd-0c693b69fe80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblAceptaProrroga']/tbody/tr[2]/td/input</value>
      <webElementGuid>f5ccdc1e-e7fa-4dc1-bb95-4c3d6f785281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>fe6be088-45d6-49f4-9ea8-470ace61c119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblAceptaProrroga_1' and @type = 'radio' and @name = 'ctl00$CPH1$rblAceptaProrroga']</value>
      <webElementGuid>9882fcd1-e95b-4328-8876-50083a8ff587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
