<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_AceptaRedeterminacionPreciosNo</name>
   <tag></tag>
   <elementGuidId>ed1dda3f-3cba-4e76-b2ce-4e01080c7dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_CPH1_rblAceptaRedeterminacionPrecios_0' and @type = 'radio' and @name = 'ctl00$CPH1$rblAceptaRedeterminacionPrecios']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rblAceptaRedeterminacionPrecios_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblAceptaRedeterminacionPrecios_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblAceptaRedeterminacionPrecios_0']</value>
      <webElementGuid>685788f6-a5e7-41c5-8194-f56599dbad85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblAceptaRedeterminacionPrecios']/tbody/tr/td/input</value>
      <webElementGuid>15a7a377-5125-45f5-ae84-8e68d8ffd5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>774b7aa4-e71f-42f6-b670-494e9a958c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblAceptaRedeterminacionPrecios_0' and @type = 'radio' and @name = 'ctl00$CPH1$rblAceptaRedeterminacionPrecios']</value>
      <webElementGuid>9c71c8ed-de02-4284-988e-cc8a04abeca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblAceptaRedeterminacionPrecios_1']</value>
      <webElementGuid>80c02329-8fcc-4d35-9fb7-eccbdb5e4f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblAceptaRedeterminacionPrecios']/tbody/tr[2]/td/input</value>
      <webElementGuid>4f7d2350-1c4b-43bf-b842-c2b0ab5ecf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>9fc9e084-d867-4cd2-9b7c-d289f16c4f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblAceptaRedeterminacionPrecios_1' and @type = 'radio' and @name = 'ctl00$CPH1$rblAceptaRedeterminacionPrecios']</value>
      <webElementGuid>29a8e469-8686-4034-af64-afef0f200cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
