<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_InvitacionProveedor</name>
   <tag></tag>
   <elementGuidId>e3bc516f-e8ca-4452-ae26-42da7032ccd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblInvitacionProveedor_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rblInvitacionProveedor_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59506202-3711-4216-a1ab-4db128f9f0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rblInvitacionProveedor_0</value>
      <webElementGuid>46f6a406-e5b4-49bf-b57b-fa07b56b5f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9f085025-a5a7-4370-9523-136cdecb9f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rblInvitacionProveedor</value>
      <webElementGuid>445bb797-fe52-4ffc-b029-6d4e2d65535e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5092aaf5-b0b0-41d3-9492-71844f91fa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rblInvitacionProveedor_0&quot;)</value>
      <webElementGuid>2ebae5b3-84e6-4788-be64-f4b1732f5334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblInvitacionProveedor_0']</value>
      <webElementGuid>ec68a13d-2f6b-4396-9027-8196b7afa180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblInvitacionProveedor']/tbody/tr/td/input</value>
      <webElementGuid>57d5409f-1bd2-40f0-a925-8093dd9179d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>1b6dca53-afa0-4d34-9dff-f1b9000c29ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblInvitacionProveedor_0' and @type = 'radio' and @name = 'ctl00$CPH1$rblInvitacionProveedor']</value>
      <webElementGuid>0c40b787-6d46-46c2-9f6b-e51629ea02a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
