<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_TelefonoContactoUOA</name>
   <tag></tag>
   <elementGuidId>457bde0f-549e-476b-b5c0-9aa5ffa6908e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtTelefonoContactoUOA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtTelefonoContactoUOA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f0c2855f-8307-42fe-a239-1bd23cecd677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtTelefonoContactoUOA</value>
      <webElementGuid>b2bf09e0-3085-48fd-b5f3-b332b62ec5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>523202cc-60d3-465f-9468-0cd20fcac1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b5989b1c-18f5-40d9-8c64-0ff3a04594f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtTelefonoContactoUOA</value>
      <webElementGuid>c83ac99a-35d1-4371-b600-a502a3b77b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>cortaLargoMaximo('ctl00_CPH1_txtTelefonoContactoUOA',255)</value>
      <webElementGuid>3c6e8cbe-7018-4261-9f27-9502169b7a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtTelefonoContactoUOA&quot;)</value>
      <webElementGuid>6c1b90ad-90fd-4c2a-ac6e-8c30c6c7fe6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtTelefonoContactoUOA']</value>
      <webElementGuid>c3f9fc95-aac2-4b87-b09b-5d9457fe0803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upInformacionBasica']/div[3]/table/tbody/tr[15]/td[2]/div/textarea</value>
      <webElementGuid>276d4f00-0452-4d6a-873a-5fa384ed9f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/div/textarea</value>
      <webElementGuid>9508eead-179f-40c1-9ef0-aeb0e1649bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtTelefonoContactoUOA' and @id = 'ctl00_CPH1_txtTelefonoContactoUOA']</value>
      <webElementGuid>e12859c6-7e4e-4deb-a24e-c1e90b849b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
