<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAgregarSocio</name>
   <tag></tag>
   <elementGuidId>c6fc9ead-d009-49a0-b62d-f26c4324fc77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_datosSocio_lnkAgregar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosSocio_lnkAgregar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>199e95e5-ae0b-4f8d-b747-d3f89580e9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:openModalPersonasLegales('ctl00_CPH1_datosSocio_myModalPersonasLegales'); return false;</value>
      <webElementGuid>9207c4f9-5578-44e5-8bb9-f6416c7aad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosSocio_lnkAgregar</value>
      <webElementGuid>9112b443-ae92-4ee2-b6c8-78a7688e58a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-block</value>
      <webElementGuid>b9aca1b0-04d1-4832-9a5e-f88c1d0e3275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$datosSocio$lnkAgregar','')</value>
      <webElementGuid>193771ba-da70-4c8b-8100-85eee70198f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar socio</value>
      <webElementGuid>ed480f7b-d159-42ad-96e0-88fc0dbe9390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosSocio_lnkAgregar&quot;)</value>
      <webElementGuid>c03a530d-784c-48cc-9f36-c719c3fd5d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_datosSocio_lnkAgregar']</value>
      <webElementGuid>bb59564a-bafc-4a09-83bd-c38600484496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosSocio_divPersonasleg']/div/div[2]/div/div[3]/div/a</value>
      <webElementGuid>94afcc83-8479-472e-ba5c-b4f05cd26298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agregar socio')]</value>
      <webElementGuid>8a9a8355-9a6c-49df-a057-79eae34f3b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acciones'])[3]/following::a[1]</value>
      <webElementGuid>e03375a2-0f5c-45fb-92b1-66292a465808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUIT / Identificador Tributario'])[1]/following::a[1]</value>
      <webElementGuid>5dce8a8c-9b91-4e8b-bdde-9e36c54d9eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar personas legales'])[1]/preceding::a[1]</value>
      <webElementGuid>0da95224-c200-4963-bb04-b6176f178eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personas legales'])[2]/preceding::a[1]</value>
      <webElementGuid>a5690a3b-af21-45d6-af55-65a7de470ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar socio']/parent::*</value>
      <webElementGuid>4bcc7903-ba42-43dc-948d-4a9901f843b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$datosSocio$lnkAgregar','')&quot;)]</value>
      <webElementGuid>9450a09f-fcac-4d68-8736-0a8bd4d1bb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/a</value>
      <webElementGuid>e5e3f970-b9f4-4213-8214-8a1d7cb1378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_datosSocio_lnkAgregar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$datosSocio$lnkAgregar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Agregar socio' or . = 'Agregar socio')]</value>
      <webElementGuid>1a71d033-889c-4274-89e0-42b1260aca24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
