<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputIdentificacionTributariaSocioJuridico</name>
   <tag></tag>
   <elementGuidId>ef4ee94b-69e3-4689-8969-e653ccd10e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3dad8ff-2388-4d9a-9f41-2a4cbdbe20e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosSocio$txtIdentificacionTributariaSocioJuridico</value>
      <webElementGuid>daa671c8-d3b4-41ee-a82e-bffdcba83bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9014f29d-045b-4be8-b2d1-cb9e793ff93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico</value>
      <webElementGuid>8255b2ce-e92f-482b-846d-9945a5b3277e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a54abd2-7468-4fe0-b420-affb2ac27bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>6b340ea0-50f4-406d-af1e-f0b5caebe530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico&quot;)</value>
      <webElementGuid>a8f2004a-231c-4cf0-8ee1-1a506c8da7a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico']</value>
      <webElementGuid>9cd11d69-3a24-46d8-a86c-b57af4e36196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosSocio_DivIdentificacionTributariaSocioJuridico']/input</value>
      <webElementGuid>f6680919-322f-4281-a2d6-53223e25a813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[4]/input</value>
      <webElementGuid>59684b3d-e60c-4d2b-98f7-e45182555d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosSocio$txtIdentificacionTributariaSocioJuridico' and @type = 'text' and @id = 'ctl00_CPH1_datosSocio_txtIdentificacionTributariaSocioJuridico']</value>
      <webElementGuid>bcbb8f3a-93be-4ff8-bbf3-cf58e9a2dbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
