<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_LoginpnlEmptyLoginButton</name>
   <tag></tag>
   <elementGuidId>8ddbdf07-287b-450d-b9cc-c29332d71710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f0f2465-0ded-4fd6-9796-541b14986308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>af7bf21e-24da-4510-af8a-af9abc57be95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$BodyPlaceHolder$ucLogin$pnlEmpty$LoginButton</value>
      <webElementGuid>56b044d7-ddab-4c26-bdfd-f6fb67c19eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>7c437db9-2409-4214-b136-966b9fc1b21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton</value>
      <webElementGuid>993dbca6-32f1-4e23-9369-bd22b75f55bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signInButton</value>
      <webElementGuid>8c88acda-4088-4309-b1c8-404c466476c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton&quot;)</value>
      <webElementGuid>4094f8ef-30d5-4f92-bc95-963ea5b2edac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton']</value>
      <webElementGuid>a3c79525-31c3-47fa-8224-3d647b3e3676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_RPC']/center/table/tbody/tr/td/table/tbody/tr[4]/td/input</value>
      <webElementGuid>1b7753ca-6294-437e-8c88-e9f75ca36971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>5cd3d8f7-7b2a-40eb-8b36-5cb6c59887ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$BodyPlaceHolder$ucLogin$pnlEmpty$LoginButton' and @id = 'ctl00_BodyPlaceHolder_ucLogin_pnlEmpty_LoginButton']</value>
      <webElementGuid>5db6317a-33a3-462b-a2a8-de6d7286e0fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
