<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Carpeta creada con exito</name>
   <tag></tag>
   <elementGuidId>d5c7ce10-63e6-4962-9955-5efda678cb35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;transition-modal-title&quot;)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='transition-modal-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>42f1b3e8-e713-462e-b9e4-3e19bd1c4c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h6</value>
      <webElementGuid>fb6c3ef0-23de-4fe4-9036-87b8a22fc2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-title</value>
      <webElementGuid>3f0706d9-13ec-4237-beb7-fb49e9c3bfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carpeta creada con exito </value>
      <webElementGuid>a0c75054-87a5-47d2-8707-0a68c7c81fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-title&quot;)</value>
      <webElementGuid>4739c0ee-34d4-4a46-b3ca-928c52fb3c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='transition-modal-title']</value>
      <webElementGuid>73c69e19-09df-424c-a539-7ddbf4c3b9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'transition-modal-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>6822fe8c-d90b-412d-bae2-37e6dfe83a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h2[1]</value>
      <webElementGuid>15aa3c4a-8168-4c94-adee-22e44dc7b051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carpeta creada con exito']/parent::*</value>
      <webElementGuid>f7903940-06fd-4663-bda3-178208b66639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c2a386c7-9eaa-41c4-a56e-a89db2cb26b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'transition-modal-title' and (text() = 'Carpeta creada con exito ' or . = 'Carpeta creada con exito ')]</value>
      <webElementGuid>f02737cd-0da6-48dc-90bb-e341caa45522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
