<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pagos Varios</name>
   <tag></tag>
   <elementGuidId>eb4885ed-feb3-474b-a3ff-6dd5ee87daf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-75309-option-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-75309-option-4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'Pagos Varios' or . = 'Pagos Varios')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>466254ae-dc2b-4912-83d4-d5dc0b24c5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ebc5b0ed-6d2f-4616-a46e-413c263b0e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8adddd1b-96ef-434e-acba-3d32a312cb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-75309-option-4</value>
      <webElementGuid>c3349c72-9028-4be0-9b31-e9a4f709b539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e18eb4b9-7111-43c7-8082-e73f8a518f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c047a696-1420-4c84-a875-12715068b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e91f7920-362d-4350-a186-8e91b06599d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>d9978a24-1b38-4ab7-b630-41d7dbb42680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pagos Varios</value>
      <webElementGuid>8915e45e-dd3a-468b-9e20-d5b9f15cc63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-75309-option-4&quot;)</value>
      <webElementGuid>9492cdce-4b44-4fc8-abdc-092d5c59e008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-75309-option-4']</value>
      <webElementGuid>e7220188-b485-4455-a914-4c2e57fb00b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-75309-popup']/li[5]</value>
      <webElementGuid>ff285dbd-4a7a-43ce-9997-b6f815321814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F Con Cargos A Rend.'])[1]/following::li[1]</value>
      <webElementGuid>cf34a3da-69e2-40b3-b77f-8eb920c52744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondos Permanentes'])[1]/following::li[2]</value>
      <webElementGuid>88f70204-c2a8-441c-8228-7fae43730213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prestador Común'])[1]/preceding::li[1]</value>
      <webElementGuid>1b220860-ab02-49f1-87c1-a97c51ce84f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reintegro'])[1]/preceding::li[2]</value>
      <webElementGuid>4300238c-31a4-464f-9c11-72716138bc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pagos Varios']/parent::*</value>
      <webElementGuid>d77ea940-212c-4e04-9c7b-c0833f01d787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>1ecccf25-433c-4d62-8b2d-a9c29ea9ae1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-75309-option-4' and (text() = 'Pagos Varios' or . = 'Pagos Varios')]</value>
      <webElementGuid>f5a0b34b-adfa-4e95-a953-46abe7892d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
