<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Carpeta creada con exito</name>
   <tag></tag>
   <elementGuidId>1246595f-9982-41df-a7de-6503236f85f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;transition-modal-description&quot;)[count(. | //p[@class = 'MuiTypography-root MuiTypography-body1' and @id = 'transition-modal-description']) = count(//p[@class = 'MuiTypography-root MuiTypography-body1' and @id = 'transition-modal-description'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='transition-modal-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bc9f42d3-9846-468a-ba0a-d9f4a9f8075d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1</value>
      <webElementGuid>5a2383eb-1f97-451d-b4dc-8038fe1669be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-description</value>
      <webElementGuid>fd384c0e-ebe0-46ab-817c-68f9de368d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sx</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>934705ea-9ced-425e-8449-3fa5a755209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carpeta creada con exito </value>
      <webElementGuid>d3ad4f0d-5018-4b75-84fa-1f31c7a728bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-description&quot;)</value>
      <webElementGuid>5267a859-58fc-4c78-955c-f5d9be30071f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='transition-modal-description']</value>
      <webElementGuid>6b00ac04-2c3c-49d7-ae21-290d59a92834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carpeta creada con exito'])[1]/following::p[1]</value>
      <webElementGuid>585a93dc-fdf7-4feb-88a3-64d9bfa33fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'transition-modal-description', '&quot;', ')')])[1]/following::p[1]</value>
      <webElementGuid>b6c2af4a-e297-47a1-8054-1b437e578676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>e8e28ad4-c132-4b67-b149-03223aa51c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'transition-modal-description' and (text() = 'Carpeta creada con exito ' or . = 'Carpeta creada con exito ')]</value>
      <webElementGuid>afc0191b-2c42-4384-8aed-da0e12b0307b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
