<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CarpetaCreadaExito</name>
   <tag></tag>
   <elementGuidId>68165a98-306b-42eb-962a-d34dfe4137c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;transition-modal-description&quot;)[count(. | //p[@class = 'MuiTypography-root MuiTypography-body1' and @id = 'transition-modal-description' and (text() = 'Carpeta creada con exito ' or . = 'Carpeta creada con exito ')]) = count(//p[@class = 'MuiTypography-root MuiTypography-body1' and @id = 'transition-modal-description' and (text() = 'Carpeta creada con exito ' or . = 'Carpeta creada con exito ')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='transition-modal-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cc061501-7590-43e6-8fe5-ae5cc168bf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1</value>
      <webElementGuid>36c282f6-5760-40bd-9b41-2e14d770fee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-description</value>
      <webElementGuid>a6cf0fbf-8571-4712-ab83-9d761061a527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sx</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f5e292b8-6ef4-4151-8fd8-3e874e62ab2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carpeta creada con exito </value>
      <webElementGuid>1bfecaa5-b882-4187-afde-0c4c28a96045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-description&quot;)</value>
      <webElementGuid>cfe57120-8075-4bd9-b6c2-c4c5ae8746eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='transition-modal-description']</value>
      <webElementGuid>e786ce92-6a30-4e21-a1de-aba95a4a1387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carpeta creada con exito'])[1]/following::p[1]</value>
      <webElementGuid>d1d2324f-0d95-42f5-87fb-572f62d58ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'transition-modal-description', '&quot;', ')')])[1]/following::p[1]</value>
      <webElementGuid>e3b13251-ba1f-4641-917b-bde4c4c9cb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>3cc7de30-dd1c-4fd7-8c2f-a02e0b88a832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'transition-modal-description' and (text() = 'Carpeta creada con exito ' or . = 'Carpeta creada con exito ')]</value>
      <webElementGuid>cb25eded-4f00-4936-bcb6-7cf7c200b803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
