<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_primeraLPU</name>
   <tag></tag>
   <elementGuidId>4fc796c0-46a8-42ee-8080-3b3d2baa07bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$UC_TareasEscritorio$TablaTareaSolicitudActualizacionPrecios$gvTareasEscritorio$ctl02$lnkVistaPrevia&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '401-0352-LPU25' or . = '401-0352-LPU25')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdc4a569-56fc-43b3-9b72-fa5b357b1325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia</value>
      <webElementGuid>1d10d6c4-e88f-4e3d-a405-2365c862c366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$UC_TareasEscritorio$TablaTareaSolicitudActualizacionPrecios$gvTareasEscritorio$ctl02$lnkVistaPrevia','')</value>
      <webElementGuid>aaef1480-d0d3-4ed8-b271-48e54fff764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>401-0352-LPU25</value>
      <webElementGuid>2bd90c80-4261-410c-8b7b-2fdf5152a6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia&quot;)</value>
      <webElementGuid>3d8e6bb2-f3c8-48b3-9430-5aaf46f716df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia']</value>
      <webElementGuid>1ae8fba9-12a9-44b3-96d5-986225201613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>389623a8-e82f-4f99-9ead-021e7fbfcb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'401-0352-LPU25')]</value>
      <webElementGuid>639148d7-213b-4905-9591-7adeb611db45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acción'])[5]/following::a[2]</value>
      <webElementGuid>a3b047a4-ab26-4144-9661-aaeb9f2dc5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Días transcurridos'])[1]/following::a[2]</value>
      <webElementGuid>7735e8c1-b33f-41ed-94ac-cde7f3d1bf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Gise'])[6]/preceding::a[1]</value>
      <webElementGuid>16ceb826-23a3-451a-9962-ea4f1f2e57da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitar Actualización de Precios'])[1]/preceding::a[1]</value>
      <webElementGuid>6d043ffc-9578-48c4-9d56-d3b425fad667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='401-0352-LPU25']/parent::*</value>
      <webElementGuid>2753c8d1-36a2-475d-930f-8181c00ccdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$UC_TareasEscritorio$TablaTareaSolicitudActualizacionPrecios$gvTareasEscritorio$ctl02$lnkVistaPrevia','')&quot;)]</value>
      <webElementGuid>3affe676-5188-4d2f-8082-09a6c3638510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>35c1f620-8716-4380-b27a-96fac6e246b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UC_TareasEscritorio_TablaTareaSolicitudActualizacionPrecios_gvTareasEscritorio_ctl02_lnkVistaPrevia' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$UC_TareasEscritorio$TablaTareaSolicitudActualizacionPrecios$gvTareasEscritorio$ctl02$lnkVistaPrevia&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '401-0352-LPU25' or . = '401-0352-LPU25')]</value>
      <webElementGuid>1a22d1af-17c1-45fd-b3b6-0f29ac2da788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
