<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PrecioSolicitadoItem1</name>
   <tag></tag>
   <elementGuidId>27abbc4c-b6e1-4c52-9f82-cb6843cf32a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a654f96-0ec7-4ef6-8f09-376396de4020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$GrillaActualizacionPrecios$gvItemsDocContractualActDePrecios$ctl02$txtPrecioSolicitadoItem</value>
      <webElementGuid>d17e0fd9-aad4-4e45-a24b-9ec03caf30cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22468d70-e36b-4bbf-b360-51dab465543c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2,00</value>
      <webElementGuid>84c156dd-4a16-4437-ab24-700c7af16f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$GrillaActualizacionPrecios$gvItemsDocContractualActDePrecios$ctl02$txtPrecioSolicitadoItem\',\'\')', 0)</value>
      <webElementGuid>a2cb13f0-dcc7-4129-927c-24ff6493f2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validacionesTxtPrecioSolicitadoItem(event)</value>
      <webElementGuid>e5d59865-f41c-4f4d-b852-878546577699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem</value>
      <webElementGuid>4a48afe0-8500-436e-b2e0-1d14769561ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cantidad-prorrogada</value>
      <webElementGuid>b669aeff-4a91-45ab-a5b2-352db134acb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return moverSiguiente(this, event);</value>
      <webElementGuid>22c8a058-c467-43a1-a4fe-03285c55c644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem&quot;)</value>
      <webElementGuid>9c8ec0b0-c3d5-4201-93f4-f72600c84f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem']</value>
      <webElementGuid>945b780b-8530-4579-9ad5-03e319291380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios']/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>c282161c-5d69-47ff-8387-6496d82e8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>0801ae45-faab-49c2-8d3c-2d1b82b0396d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$GrillaActualizacionPrecios$gvItemsDocContractualActDePrecios$ctl02$txtPrecioSolicitadoItem' and @type = 'text' and @id = 'ctl00_CPH1_GrillaActualizacionPrecios_gvItemsDocContractualActDePrecios_ctl02_txtPrecioSolicitadoItem']</value>
      <webElementGuid>b44329df-f9b6-4081-91cd-4fcbe65069fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
