<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEditarDetalle</name>
   <tag></tag>
   <elementGuidId>40ef3104-95e4-4d01-a4b2-5597da1a8e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_cell0_5_imgEditarSolicitud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@title=&quot;Editar Detalle&quot;])[${renglon}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4d4df00-c33c-4a79-88b3-568127bba0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c738b532-0612-4c84-9f29-644182b7ee85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptDetalleItem$ctl01$UCDetelleEntregaItemSolicitud$gvEntregas$cell0_5$imgEditarSolicitud</value>
      <webElementGuid>d3a1a337-c1cf-4564-a2f3-5161a96fa414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_cell0_5_imgEditarSolicitud</value>
      <webElementGuid>fef7765e-28d1-4fa7-868b-e8ae1467adc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Editar Detalle</value>
      <webElementGuid>c7b436ce-c3ae-4c6b-a1bf-d71c9a50914f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_editar.gif</value>
      <webElementGuid>7a5b6ca9-0733-4841-8772-ffe17b4ab476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Editar Solicitud</value>
      <webElementGuid>f99fdab9-ca2b-46b4-9521-44f5f8f5d07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_cell0_5_imgEditarSolicitud&quot;)</value>
      <webElementGuid>3992fe83-282d-40bb-b5b5-f47094350f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_cell0_5_imgEditarSolicitud']</value>
      <webElementGuid>f2ecd157-05d7-4001-b39a-b1c7e40ccb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_tccell0_5']/input</value>
      <webElementGuid>238820a8-cf50-4d56-9e60-e021a6b29729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>47b3bc32-0d91-4499-8875-c8867b7e5c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$rptDetalleItem$ctl01$UCDetelleEntregaItemSolicitud$gvEntregas$cell0_5$imgEditarSolicitud' and @id = 'ctl00_CPH1_rptDetalleItem_ctl01_UCDetelleEntregaItemSolicitud_gvEntregas_cell0_5_imgEditarSolicitud' and @title = 'Editar Detalle' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_editar.gif' and @alt = 'Editar Solicitud']</value>
      <webElementGuid>8d896f9b-e941-4390-bb61-db5ee2220931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
