<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CuitCuil Invlido</name>
   <tag></tag>
   <elementGuidId>cdb73bcc-bdcc-4c55-af51-40eaf86d5983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='username-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#username-helper-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>db02a2b0-24ab-40f9-ae35-085cb9989a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root MuiFormHelperText-contained Mui-error MuiFormHelperText-filled Mui-required</value>
      <webElementGuid>65dd49e1-afe9-44d0-9157-7ac39dd76001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username-helper-text</value>
      <webElementGuid>39f4f0af-cc3e-4495-b7d3-5b4b000cc1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuit/Cuil Inválido</value>
      <webElementGuid>b8c108a6-537b-4427-a86a-a2a1cdf67d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username-helper-text&quot;)</value>
      <webElementGuid>7d35f539-f155-4853-8968-0b48844f973c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='username-helper-text']</value>
      <webElementGuid>d2ae2514-5205-4ff8-bd3d-cb0dea045c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[2]/div/p</value>
      <webElementGuid>6168221b-a0db-4178-af2c-fc68f2be442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cuit/Cuil Inválido']/parent::*</value>
      <webElementGuid>be0d29de-20a2-4c0c-8469-e41f08d52cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>ebf7e02d-5852-4a17-b2e2-bf497c2bc948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'username-helper-text' and (text() = 'Cuit/Cuil Inválido' or . = 'Cuit/Cuil Inválido')]</value>
      <webElementGuid>1c3e3726-fe24-4f82-94f6-68a3e295959f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
