<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Titulo_fileTitle_documento</name>
   <tag></tag>
   <elementGuidId>114c1b38-e9c9-4012-a153-2798842ae145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f750b87-2e69-41c3-9e3a-e520f7add8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e318c58-392a-4781-9532-1884bd9ec656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>fileTitle</value>
      <webElementGuid>43efef36-8292-4def-ba6e-2765e7e979b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileTitle</value>
      <webElementGuid>59a9611e-9241-4fed-b375-7988c9eb96c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fileTitle</value>
      <webElementGuid>5b46849b-93df-4ffc-bf18-eb3bf812a840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa8eb63e-ce06-4f73-b855-6f0c80ed4785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>7b3de1d4-41ae-46c0-85fb-b836d2624f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileTitle&quot;)</value>
      <webElementGuid>e56b41dc-8594-4300-875d-fde0d4ca02e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileTitle']</value>
      <webElementGuid>fa8c0e33-d5df-4691-ab87-e8fbf02e73cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/form[2]/div/div[4]/div/div/input</value>
      <webElementGuid>795dadea-5317-490a-b02e-161f2aa74b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>c6560a8c-3cc3-4aa3-a020-2861ccc0f47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fileTitle' and @name = 'fileTitle' and @type = 'text']</value>
      <webElementGuid>65b25f3f-3196-4fab-947b-b33b3f5781de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
