<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_TipoDocumentoListado</name>
   <tag></tag>
   <elementGuidId>c341dcce-564d-45ca-ad3b-6b23015246b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mui-40862-popup']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//ul[@role = 'listbox' and (text() = 'AutorizaciónFacturaLiquidaciónOficioOrdenRecetaOtros' or . = 'AutorizaciónFacturaLiquidaciónOficioOrdenRecetaOtros')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-40862-popup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>9ebc9dfe-7279-46e3-bfab-89d1426df9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-listbox</value>
      <webElementGuid>5954662a-f084-4966-a970-ad22caaa9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3aa23d53-c46e-4aa9-aa00-f89a9f1b7a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-40862-popup</value>
      <webElementGuid>bb265030-b172-4b40-93f5-7b24d87a0204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-40862-label</value>
      <webElementGuid>2d7cba05-2da3-4a9c-8e1b-4eb7d7f4d975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutorizaciónFacturaLiquidaciónOficioOrdenRecetaOtros</value>
      <webElementGuid>fccd23d0-96d1-4735-a69c-a37ce9110174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-40862-popup&quot;)</value>
      <webElementGuid>0ec53ea2-0a6a-443a-81c7-41b51527afc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='mui-40862-popup']</value>
      <webElementGuid>88bddc98-bb5d-44f1-8030-488cf2e167bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mui-40862-popup', '&quot;', ')')])[1]/following::ul[1]</value>
      <webElementGuid>dd3510e2-9e35-44ef-8ead-f24118cdff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::ul[1]</value>
      <webElementGuid>ec502cd8-b0c0-48db-b227-c0f4f9f3c8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>e7a89de5-ce7c-44ed-b3ce-bed02618b2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'mui-40862-popup' and (text() = 'AutorizaciónFacturaLiquidaciónOficioOrdenRecetaOtros' or . = 'AutorizaciónFacturaLiquidaciónOficioOrdenRecetaOtros')]</value>
      <webElementGuid>695d7cdc-dd98-4dba-92a4-212712bef20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
