<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_validacion4Lugar y fecha de entrega</name>
   <tag></tag>
   <elementGuidId>5e388634-e9b8-4335-b4db-0fee4304949a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>344e1d67-5780-4f0e-9a02-da18609b8422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado</value>
      <webElementGuid>2966a72c-511c-40d5-b25a-23e3ddf16263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_alerta_exito.gif</value>
      <webElementGuid>04bc8bcb-3d5f-406c-a178-1ae6e18801e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Alerta Exito</value>
      <webElementGuid>334fb9b6-22e1-4bf2-87fc-50c6234028aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado&quot;)</value>
      <webElementGuid>a675c4db-3172-43d3-88c9-43dfb1af7c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado']</value>
      <webElementGuid>407948cf-9134-46fc-8424-83e6640f0b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[3]/table/tbody/tr[4]/td/img</value>
      <webElementGuid>6f110639-6dd1-484b-acea-1970b1782bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Alerta Exito'])[4]</value>
      <webElementGuid>9c853f38-6c7a-4c3c-8fb1-93a7ea8d7eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/img</value>
      <webElementGuid>c9130aa0-9115-4e39-9c84-20d9f7f5e57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_CPH1_SeccionPartidasPresupuestarias_imEstado' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_alerta_exito.gif' and @alt = 'Alerta Exito']</value>
      <webElementGuid>3f8d5b9e-8ccd-4953-95b3-0cecd210fd9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
