<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monto importe</name>
   <tag></tag>
   <elementGuidId>858ae65e-c1fe-4c41-8824-f9a4ca1a77ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion_I</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id, '_txtImputacion_I') and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c833e35e-d0ab-4df1-b574-9f4f20d82179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>0ef4362d-24d1-4aa2-9e8b-e731f3d58219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9$txtImputacion</value>
      <webElementGuid>1a1c2a64-84f8-4dca-9db0-401ee8f51811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion', event)</value>
      <webElementGuid>ec9d9e18-a3dd-47fb-8dde-72b02502245d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5,00</value>
      <webElementGuid>16e36a31-c966-4b14-b920-2c3c36b0adc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>a846be30-c19f-482c-b04b-907f5691a421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_txtImputacion_I</value>
      <webElementGuid>57efd341-8724-4f31-a8e5-7b24641fbf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion')</value>
      <webElementGuid>422ef836-83d8-49fb-9408-435b25466fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion')</value>
      <webElementGuid>2984de27-6bf2-49be-aaf5-2eac3ee37283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion')</value>
      <webElementGuid>962838ad-983d-4cc2-aaf4-e802fb7d754e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4321f96e-9b38-4483-85f4-aee742da5a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>aspxEKeyPress('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion', event)</value>
      <webElementGuid>200bcc32-11be-4f30-a8c0-23a518958ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion', event)</value>
      <webElementGuid>0df000f2-d1e9-4ef1-a994-c74d0161756c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c62df2b-0814-4ff4-b2d7-81a8a93e1ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e025361f-f53c-45a1-98be-6c1f3e490584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion_I&quot;)</value>
      <webElementGuid>89663707-c62f-46ec-a94b-b7f839f88ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion_I']</value>
      <webElementGuid>b654252c-6b9a-42ce-8890-31d6c4f9692b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion']/tbody/tr/td/input</value>
      <webElementGuid>999a5e22-45a8-40b4-aa3c-9303999ca584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>e808fc28-2933-4850-a6fd-9b44ddc69918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9$txtImputacion' and @id = 'ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_txtImputacion_I' and @type = 'text']</value>
      <webElementGuid>652a7713-9529-423d-9eb2-88d659c29771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
