<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IngresarDetalleImputacion</name>
   <tag></tag>
   <elementGuidId>bbc8f73a-48e2-49cb-ba7d-b87742aebc55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b32296-f2bd-4ce7-b7cf-f1f657f13a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>41b4e776-ebc4-402d-a329-b3ede3c8a7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$partidasImputadas$gvPartidas$cell0_13$btnIngresarDetalle</value>
      <webElementGuid>fe7f004e-dc0b-4a8a-96b2-845ea5b19f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle</value>
      <webElementGuid>df621655-4eb3-4a8d-ae75-0e8b5b34043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingresar Detalle Imputación</value>
      <webElementGuid>7d5c8972-ff56-4303-9bc4-5e06239bea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_editar.gif</value>
      <webElementGuid>f2271c96-e64b-458f-9be8-5e819982842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ingresar Detalle Imputación</value>
      <webElementGuid>90ba6e9c-6e4f-44fc-8f2e-5f43d08092d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle&quot;)</value>
      <webElementGuid>da8bcf46-5039-4966-aecb-cfcd27fc589a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle']</value>
      <webElementGuid>48e39260-20b6-4536-8456-2a03b44bd0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_partidasImputadas_gvPartidas_tccell0_13']/input[2]</value>
      <webElementGuid>b94025a4-9337-47ea-8de6-eb3a2fb3d0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input[2]</value>
      <webElementGuid>d33ce369-9ea4-4044-8a4a-7daf9ec05b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$partidasImputadas$gvPartidas$cell0_13$btnIngresarDetalle' and @id = 'ctl00_CPH1_partidasImputadas_gvPartidas_cell0_13_btnIngresarDetalle' and @title = 'Ingresar Detalle Imputación' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_editar.gif' and @alt = 'Ingresar Detalle Imputación']</value>
      <webElementGuid>90ebe954-69cf-45b4-be16-4c39d8bc26fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
