<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkPartidas</name>
   <tag></tag>
   <elementGuidId>1be64286-8ba9-49c8-8739-dc429cf75095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13cb89c9-ab09-4768-bdf8-e7fba907898f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0</value>
      <webElementGuid>53812ce6-671c-43cb-b6d8-3b288aa2a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgvCommandColumnItem</value>
      <webElementGuid>7d70b89d-c945-4068-b0b7-73956b6e8f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bbee0272-3526-4e57-a7a0-4bf5c7b2bdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>aspxGVSelectRow('ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas',0,this);</value>
      <webElementGuid>7d4e1279-fecb-4b5f-bec7-d86714500253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0&quot;)</value>
      <webElementGuid>b3679985-7545-4a17-badc-893733289fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0']</value>
      <webElementGuid>bf29c39f-4855-4ffb-a543-750f873d04d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXDataRow0']/td[11]/input</value>
      <webElementGuid>f0418184-ea88-49f8-b8ec-04f8de5263a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>5a83cd68-7375-4ccf-ab5c-039c3e00a358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0' and @type = 'checkbox']</value>
      <webElementGuid>1cc927ed-d5c0-4220-ac75-021cb3696183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
