<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha imputacin</name>
   <tag></tag>
   <elementGuidId>d6c3b758-56c7-41aa-a3c6-85997e49090e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion_I</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id, '_dxedteFechaImputacion_I') and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion_I']

//*[@id=&quot;ctl00_CPH1_7a608fc7-41ef-4016-8814-51b49c65bf06_dxedteFechaImputacion_I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6480a215-3c61-4c50-a5c4-40ac4377e1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>128d4208-75b5-45d8-befc-9e6cc70e03c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9$dxedteFechaImputacion</value>
      <webElementGuid>4cf852d7-853a-4a9d-82a4-6e24d7cada4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion', event)</value>
      <webElementGuid>982c0839-ebba-4525-a531-612445059a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2/6/2025</value>
      <webElementGuid>93cb76ea-b4a3-4c55-ad87-df54c9e33e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_dxedteFechaImputacion_I</value>
      <webElementGuid>112a293f-c029-4784-ab4a-4ef648c85fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion')</value>
      <webElementGuid>22b988c3-e042-42b7-ab5e-230c4bb665ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion')</value>
      <webElementGuid>3405d87b-2b22-4af4-a774-91e8e87a772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion')</value>
      <webElementGuid>973d57be-fa55-443d-9847-0b96fdeff35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7895435a-5d65-49d5-9aee-222a4b89f965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d9efe42-c5a1-4954-97db-0419fb778554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a2669f49-3064-431a-b5db-883f84c8f970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion_I&quot;)</value>
      <webElementGuid>8bbfc9b9-563b-4fd5-bd69-6733492be876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion_I']</value>
      <webElementGuid>146381ee-1a95-4330-b5f6-0613b7979466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion']/tbody/tr/td/input</value>
      <webElementGuid>bd012ae7-95e9-4eff-ac49-77afa5a55d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>193ba591-f944-4325-bfb2-d64a61b74af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9$dxedteFechaImputacion' and @id = 'ctl00_CPH1_ca5ecabe-44ff-4aae-84d3-3c0709d7b7b9_dxedteFechaImputacion_I' and @type = 'text']</value>
      <webElementGuid>a32b2389-99ec-4ff7-ae24-6bfd86a0b236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
