<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Confirmada_consulta</name>
   <tag></tag>
   <elementGuidId>b236dedc-71f6-4673-b090-1606696b11cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'Confirmada' or . = 'Confirmada')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='folderStateAutocomplete-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderStateAutocomplete-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0f12cc9d-1f50-4fc9-874d-6a6892c00ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>65f36e54-d75b-4809-9948-5798681f4c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e8446d72-e12c-4659-b405-7537f1ffcbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderStateAutocomplete-option-2</value>
      <webElementGuid>dafef838-4207-40a0-a0d9-8cb06095fb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>068d2e4a-5150-4dd0-aae1-084653f7d97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b4767b1-cc14-4acb-8dda-cc6c6e374dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d00a907-b045-485c-af37-0acb17cf42f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>8c77984c-984b-45b6-bb96-27b29fad6e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9adb69e0-f70a-4cc6-b7a1-2b1f5daf9be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmada</value>
      <webElementGuid>43748780-e9c7-4229-ab1b-ff7e9cdff1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderStateAutocomplete-option-2&quot;)</value>
      <webElementGuid>fef3d5cf-eb0e-40c7-a1d9-cde8043ff456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='folderStateAutocomplete-option-2']</value>
      <webElementGuid>c82faab3-c149-4d7d-b2fc-da03ae8a73e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='folderStateAutocomplete-popup']/li[3]</value>
      <webElementGuid>df8ef23b-b1a1-4d09-826c-59e9df2a34f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aprobada'])[1]/following::li[1]</value>
      <webElementGuid>040d381e-25f4-41d4-926c-4ee61e0d548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En Liquidacion'])[1]/following::li[2]</value>
      <webElementGuid>877815cd-98c7-430f-954f-3ecb5487fffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En Ingreso'])[1]/preceding::li[1]</value>
      <webElementGuid>9c81f573-4575-468b-85d5-58a378036b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagada'])[1]/preceding::li[2]</value>
      <webElementGuid>3de08b7f-37c1-452a-ba5e-f0c673d1a09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmada']/parent::*</value>
      <webElementGuid>6507f90c-5e1f-4107-b91f-f1556cf5af65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>452d5aff-ada1-4fe3-aa96-a2040aa4972f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'folderStateAutocomplete-option-2' and (text() = 'Confirmada' or . = 'Confirmada')]</value>
      <webElementGuid>6e7aa717-e4c3-43f3-8094-5af01c313606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
