<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Fondo Compensador_consulta</name>
   <tag></tag>
   <elementGuidId>fe426c8c-d382-46ad-b5bd-b45c7b83e039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='folderTypeAutocomplete-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderTypeAutocomplete-option-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'Fondo Compensador' or . = 'Fondo Compensador')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e7d30a40-e359-4661-ad3c-2f70712133d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3b2e6c40-9ab4-40f0-965e-76f2264d03a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d3911191-478d-4086-86d6-8fa1bb738844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderTypeAutocomplete-option-2</value>
      <webElementGuid>5cfe7dcf-72e4-426c-880a-1014a515b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>60882228-ab04-452e-9866-c20a20c5dcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5ad1881-23ce-4a69-8956-1b441952ebda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf8deb4b-a5b9-49df-9179-9239e1ed7de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>15e77355-99a3-4ef1-a7a6-fd2b555c7a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f9037ef4-6f17-40d8-a6ce-1e7ffeac76ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fondo Compensador</value>
      <webElementGuid>aff109b0-a333-4d50-9164-72b1962bc1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderTypeAutocomplete-option-2&quot;)</value>
      <webElementGuid>6bb56c11-3698-476e-9123-a6c098a40128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='folderTypeAutocomplete-option-2']</value>
      <webElementGuid>c680753d-a7d3-4a31-b506-da28bd79ca26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='folderTypeAutocomplete-popup']/li[3]</value>
      <webElementGuid>7e7d8012-23a1-46cf-a249-1aa345254fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deuda Flotante'])[1]/following::li[1]</value>
      <webElementGuid>e83d4033-72c5-4356-a2fd-516b2287b638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direccion Accion Soc'])[1]/following::li[2]</value>
      <webElementGuid>e723ddf9-66c9-4fe9-b94f-825613bdaf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondos Permanentes'])[1]/preceding::li[1]</value>
      <webElementGuid>9f7d4469-2465-46f1-ad07-34541adf1ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F Con Cargos A Rend.'])[1]/preceding::li[2]</value>
      <webElementGuid>5f9c0929-5439-43e7-aef4-3bc63bce762c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fondo Compensador']/parent::*</value>
      <webElementGuid>f9d1bbaa-4561-4161-a794-ba0aaaa69ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>8efa1c8e-b15c-4d2a-95ac-673a4d5edf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'folderTypeAutocomplete-option-2' and (text() = 'Fondo Compensador' or . = 'Fondo Compensador')]</value>
      <webElementGuid>59ad6000-962f-47de-bce3-2879260be4a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
