<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_F Con Cargos A Rend_consulta</name>
   <tag></tag>
   <elementGuidId>a5cf6383-8fe7-4150-a140-02cc9231ca1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='folderTypeAutocomplete-option-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderTypeAutocomplete-option-4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'F Con Cargos A Rend.' or . = 'F Con Cargos A Rend.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bd5bb418-db89-4359-86ed-ed3571544bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>969aa951-6186-4d3b-8e1c-bdb866e56c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>96ebdb28-06f9-4719-9a5f-361705c11731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderTypeAutocomplete-option-4</value>
      <webElementGuid>63cd4f7a-b8c9-481c-88b0-61a8eb58077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0ea0a385-8bc8-45f4-bf07-0c4962b387c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9618c9d9-6c90-43a4-a37e-9bfff1dc8ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7cd5a9f-2f36-4ccb-9d25-197f32b39f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>aaf80d83-5400-4dae-a9ca-302517c01c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32905454-8d94-4ff5-96f0-e452c232fb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>F Con Cargos A Rend.</value>
      <webElementGuid>2a1aa12e-6ab0-4762-a203-70e6df4d0278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderTypeAutocomplete-option-4&quot;)</value>
      <webElementGuid>4e37764c-0113-4fb4-b2e2-ee2f6bfe320a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='folderTypeAutocomplete-option-4']</value>
      <webElementGuid>cb1f4682-719d-4503-b5ea-bed0a4ab0db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='folderTypeAutocomplete-popup']/li[5]</value>
      <webElementGuid>51439d57-c4ff-4d12-871a-4e92653c4d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondos Permanentes'])[1]/following::li[1]</value>
      <webElementGuid>1cbc82bf-120c-43c7-82b0-3c9ef57e07b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondo Compensador'])[1]/following::li[2]</value>
      <webElementGuid>1e7fbdf9-5788-4638-b77e-a4cc4db7085d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G.A. Legales'])[1]/preceding::li[1]</value>
      <webElementGuid>1cb3e323-8fe5-4b05-ab1b-a719bb1c959e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos Varios'])[1]/preceding::li[2]</value>
      <webElementGuid>99f7b527-50e2-405f-ab5f-7b18eeb5b088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='F Con Cargos A Rend.']/parent::*</value>
      <webElementGuid>5a9ab5b3-a85d-4f61-a543-d54d04508e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]</value>
      <webElementGuid>1e4987f1-116b-4c74-8008-ee052ee6398d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'folderTypeAutocomplete-option-4' and (text() = 'F Con Cargos A Rend.' or . = 'F Con Cargos A Rend.')]</value>
      <webElementGuid>280d4d0b-a512-4c79-8872-1b843c312297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
