<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_G.A. Legales_consulta</name>
   <tag></tag>
   <elementGuidId>64b8e06b-0143-417e-b5f6-f6a0f73fa70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='folderTypeAutocomplete-option-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderTypeAutocomplete-option-5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'G.A. Legales' or . = 'G.A. Legales')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>695cfc4f-e9e6-4fd6-8452-b494b9b1b8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>14f883de-7e36-4e49-b1f8-be84dbcf8b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ca1ad459-ab1a-4695-af39-c1651847652a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderTypeAutocomplete-option-5</value>
      <webElementGuid>10d27bdd-9c90-4059-b2ba-9a86ecb4a23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bbe6299a-eeed-4a63-bcb7-4e2ab13d2b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0ea0ca5-be01-435b-aee6-debaed8f408f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0bdd0c2-eda0-4a2a-9f72-f565596e8812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>17af9997-a99a-4d5f-8f4d-1a067efc7037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3bc26018-fafd-447a-85e8-47740603544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>G.A. Legales</value>
      <webElementGuid>814e33ab-f5a5-46f3-8a60-4838fd4deca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderTypeAutocomplete-option-5&quot;)</value>
      <webElementGuid>3271e261-7cbb-4a01-b71e-285adcce2303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='folderTypeAutocomplete-option-5']</value>
      <webElementGuid>2a1b69e9-8f4f-48c0-964d-190b2bba5635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='folderTypeAutocomplete-popup']/li[6]</value>
      <webElementGuid>f692790c-8769-483c-b1a9-9792c0543167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F Con Cargos A Rend.'])[1]/following::li[1]</value>
      <webElementGuid>93583660-202c-4032-9c10-5e57cad83916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondos Permanentes'])[1]/following::li[2]</value>
      <webElementGuid>d77af8d6-966b-459b-873b-3cb51bed3b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos Varios'])[1]/preceding::li[1]</value>
      <webElementGuid>5e5e8250-b38f-46b2-b269-87ead3dd9eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prestador Común'])[1]/preceding::li[2]</value>
      <webElementGuid>519e6f03-dd0d-46f3-8e27-6eaafef9f464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='G.A. Legales']/parent::*</value>
      <webElementGuid>b991367d-0956-4069-8c58-5cd126b2f14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]</value>
      <webElementGuid>c45b2056-289c-4402-a663-d3e473b1dc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'folderTypeAutocomplete-option-5' and (text() = 'G.A. Legales' or . = 'G.A. Legales')]</value>
      <webElementGuid>4dc2036d-c1f2-4a45-beb1-b9e0f0cf4a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
