<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Ingresada_consulta</name>
   <tag></tag>
   <elementGuidId>b570df16-7f40-4cae-bce5-9152b295220c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'option' and (text() = 'Ingresada' or . = 'Ingresada')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='folderStateAutocomplete-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderStateAutocomplete-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0675de06-f53c-41e0-bf03-8798488d3205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a91f64c6-839d-487b-a908-302ce7b6ec43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>34281ba0-a5ff-4b62-be00-2219d8ce6e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderStateAutocomplete-option-6</value>
      <webElementGuid>bff959c3-dd49-4ba8-8d8e-916025fb92af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2a220fc3-a4b2-4924-ac33-c66c6f822bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d21e12a4-a666-455b-8437-e8f0bde34ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6f5b312-7c45-4837-9dd7-b5479bc2291b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>03be6429-8f0a-4122-a469-e9291ed4c0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a8d5d25-89e5-404f-b175-824f8c4bb3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresada</value>
      <webElementGuid>6b99ac68-a8c2-467d-93e1-e6b121eca0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderStateAutocomplete-option-6&quot;)</value>
      <webElementGuid>f6a1c843-881a-423b-9e32-a5a91222e9b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='folderStateAutocomplete-option-6']</value>
      <webElementGuid>cc45fef2-a83c-4c23-8ea0-032e11c66b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='folderStateAutocomplete-popup']/li[7]</value>
      <webElementGuid>d292abc2-9174-4b5f-91f2-a1a48c556f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archivada'])[1]/following::li[1]</value>
      <webElementGuid>af899a3b-6b9b-4233-8b33-f4421313c1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagada'])[1]/following::li[2]</value>
      <webElementGuid>db49426d-2a2e-466f-939f-9bf03e8a7d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verificada Legales'])[1]/preceding::li[1]</value>
      <webElementGuid>ee22ec11-8731-4f05-a410-042979d075fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendiente Auditoría'])[1]/preceding::li[2]</value>
      <webElementGuid>8ffd4ba7-50e0-4d39-9fb0-eae6ccf926f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresada']/parent::*</value>
      <webElementGuid>7bcc460a-8e48-4225-9aa0-318196aa405f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>b6ae0c85-0d8c-42a3-bb82-6807ee0eb06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'folderStateAutocomplete-option-6' and (text() = 'Ingresada' or . = 'Ingresada')]</value>
      <webElementGuid>04eccfec-fe91-4e7d-854e-badafb53de69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
