<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Buscar</name>
   <tag></tag>
   <elementGuidId>6aabc2a5-9f49-48fe-9588-4485127333bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6d6dbea-77c2-4f99-83a5-9664553168b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu</value>
      <webElementGuid>241539cb-53c5-4f39-9f00-6157875c1f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>69262dfd-698f-43ad-9993-e9f97c3da737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu&quot;)</value>
      <webElementGuid>cf8ecb77-fd7f-4d4d-a2de-2a4b99c4c6ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu']</value>
      <webElementGuid>6f88d6b6-98f5-4573-84b0-2bbcfb58ec0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_liMenu']/a/strong/span</value>
      <webElementGuid>50d8a002-9e59-409f-afcf-8393b2ec58cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear Proceso de Compra'])[1]/following::span[1]</value>
      <webElementGuid>dc125ffe-51b8-4e7d-b852-753980cbb83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear'])[1]/following::span[1]</value>
      <webElementGuid>9cfee828-4ef0-4f51-9e58-e7cc6a62d5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Proceso de Compra'])[1]/preceding::span[1]</value>
      <webElementGuid>53dd6b8b-3cba-49ed-98ff-1a5fd756262d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Documento Contractual'])[1]/preceding::span[1]</value>
      <webElementGuid>3adf7855-b98b-441d-99ee-96bd0163bcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>ff624d51-3af0-4fe0-8145-4878ad4e2f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/strong/span</value>
      <webElementGuid>e24c6c53-820f-4145-9f78-3ddaddf902dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_NavBar_CtrlmenubaseBastrap_rptMenu_ctl01_lblMenu' and (text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>e49f57e2-cfff-449e-87a5-d788e92dbc2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
