<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAnticipoFinancieroPorc</name>
   <tag></tag>
   <elementGuidId>c2e6ee74-e13c-460c-a654-2008d8efcea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0396555a-2206-4e8f-8f01-004faf6aca70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$gvObrasFisicas$ctl02$txtAnticipo</value>
      <webElementGuid>0b9b7332-33d4-4890-80d6-99019ebfe0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e87b1691-016a-486c-a167-beecfe8a62e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$gvObrasFisicas$ctl02$txtAnticipo&quot;, &quot;&quot;, true, &quot;validarPorc&quot;, &quot;&quot;, false, true))', 0)</value>
      <webElementGuid>5fd91191-5aae-4fce-9a6f-d903e4fa9157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>b40919de-bf6e-473d-8bde-931e9f57b44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo</value>
      <webElementGuid>9dbd6263-cadb-4367-89ae-f0aeb23858e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataformatstring</name>
      <type>Main</type>
      <value>{0:F2}</value>
      <webElementGuid>84eec426-6aa3-4f08-b175-b37b1a8d52a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39e4221b-d140-4942-ad4b-2fb89999f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo&quot;)</value>
      <webElementGuid>3d9a2fc7-c64d-4701-9306-eac9bbf07d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo']</value>
      <webElementGuid>47672f03-1b9b-474a-a95d-2ffc7a30040e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_gvObrasFisicas']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>171b6fd9-1c0e-4d34-a2a8-65d978f6ad3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>9e60736b-613f-4b9c-9859-6be9607e73d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$gvObrasFisicas$ctl02$txtAnticipo' and @type = 'text' and @id = 'ctl00_CPH1_gvObrasFisicas_ctl02_txtAnticipo']</value>
      <webElementGuid>0799c3d9-b80e-472c-b302-9a13b8ea3d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
