<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_SinConsultaTipoCircular</name>
   <tag></tag>
   <elementGuidId>ca556840-4eeb-4d33-ba8c-39f432582752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rdaSinConsulta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rdaSinConsulta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>044eb8bd-627e-4069-89d9-ec097fd7d059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rdaSinConsulta</value>
      <webElementGuid>d8d6e863-099a-4684-97cb-6cd4979746b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f8bee3a-378c-4ff1-a6c9-2d79085fd67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$TipoCircular</value>
      <webElementGuid>ca2e497e-7fed-4274-8818-40412cbee386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdaSinConsulta</value>
      <webElementGuid>489a26f7-3f14-4aa8-a411-ee43e564c794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rdaSinConsulta&quot;)</value>
      <webElementGuid>0879fa5e-7d14-46bc-9297-1f119976d8f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rdaSinConsulta']</value>
      <webElementGuid>a33ad358-9581-4172-b5a3-c3021908390c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[7]/table/tbody/tr[2]/td/input[2]</value>
      <webElementGuid>ac92d517-199e-4251-9b2b-bfefba21c3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input[2]</value>
      <webElementGuid>8677f923-01c2-48dd-bef2-a984b595a3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rdaSinConsulta' and @type = 'radio' and @name = 'ctl00$CPH1$TipoCircular']</value>
      <webElementGuid>7f09a0da-3764-47d3-865b-d5287bc5bc8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
