<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnBuscarRazonSocial</name>
   <tag></tag>
   <elementGuidId>7f8ba4da-9db4-43e8-9eb0-56f55b8bd9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_btnBuscarRazonSocial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_btnBuscarRazonSocial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98db1581-3f46-42b8-be31-3f34e5ef6207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidarRazonSocial();</value>
      <webElementGuid>39ee8bd6-0caf-4c1d-9a60-9f582decbfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_btnBuscarRazonSocial</value>
      <webElementGuid>0014e33c-1929-454a-a4e4-a56a04472218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>0d6d6637-fc07-4d7e-9833-ae6e8c667474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$btnBuscarRazonSocial','')</value>
      <webElementGuid>99263428-4f2c-482e-901e-e47faa44c26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_btnBuscarRazonSocial&quot;)</value>
      <webElementGuid>aa16603c-94eb-448b-94f6-7d7d25a79dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_btnBuscarRazonSocial']</value>
      <webElementGuid>9a0b2998-775c-4ef5-9007-7f2845ca06e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivBuscarRazonSocial']/span/a</value>
      <webElementGuid>f9a9b48e-4ce6-4d8b-b73b-c88c6b1b2379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar integrantes de la unión transitoria (UT)'])[1]/following::a[1]</value>
      <webElementGuid>b29df645-fb6a-49b8-9651-07caa319397b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La fecha de vigencia debe ser posterior a la fecha actual'])[1]/following::a[1]</value>
      <webElementGuid>132d2ec2-d094-4400-904f-280555b3f3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores ingresados'])[1]/preceding::a[2]</value>
      <webElementGuid>d9cd10d6-8ecf-4fc6-b2e1-c3b30c283ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se han encontrado proveedores ingresados'])[1]/preceding::a[2]</value>
      <webElementGuid>06e2d13f-e50b-4d32-b04a-59295ef10d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$btnBuscarRazonSocial','')&quot;)]</value>
      <webElementGuid>8dcfc103-246b-42ac-83c7-e67abded6847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>8fb086d4-a0fe-4e52-aa82-ff383bfe89b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_btnBuscarRazonSocial' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$btnBuscarRazonSocial&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>7658cf42-7683-4fa7-bc8a-fb259ba67989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
