<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputfechaConstitucion</name>
   <tag></tag>
   <elementGuidId>cf213825-98b6-4ecd-a54e-8babc4251a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_fechaConstitucion_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_fechaConstitucion_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a44b54ae-f9dc-48c5-9099-dabf097714f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>b4a4c50f-310f-4a8a-8a74-e250a76a4fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$fechaConstitucion</value>
      <webElementGuid>392a9e00-e915-4da1-b3d9-0de02ad36b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_fechaConstitucion', event)</value>
      <webElementGuid>b55e484d-6d21-4adc-8630-2cd92a0b1600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>26/07/2023</value>
      <webElementGuid>95e4e22a-88db-41e8-9320-a4c32c11eb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_fechaConstitucion_I</value>
      <webElementGuid>89bcbb75-ce82-42c1-a44c-cca1bb034ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_fechaConstitucion')</value>
      <webElementGuid>d50d0b97-2e83-4cce-a8a5-7a0be2855325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_fechaConstitucion')</value>
      <webElementGuid>cad232df-5130-44a8-aa48-ea9ed02304ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_fechaConstitucion')</value>
      <webElementGuid>b0a6e44a-4e79-493b-a5d8-e7c875eba453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4812632-f61e-495b-a40d-8df39f5db583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a979b4a-84cd-44ad-976e-a8adba9d5147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91ce5d1b-d5b1-4c3c-9985-bcdb6295a8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_fechaConstitucion_I&quot;)</value>
      <webElementGuid>5504e124-4507-4e18-893e-a99def4bfcc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_fechaConstitucion_I']</value>
      <webElementGuid>114dbfa7-6234-4165-bd71-82c55dd3d95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_fechaConstitucion']/tbody/tr/td/input</value>
      <webElementGuid>ffe5b671-d9ed-4ada-80ff-a046c25d8c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>515caf36-db21-456c-82bc-88aed2cb4852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$fechaConstitucion' and @id = 'ctl00_CPH1_fechaConstitucion_I' and @type = 'text']</value>
      <webElementGuid>6bc35b4e-301b-41f8-8d72-2a113d827cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
