<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnFormularioDePre-Inscripcin</name>
   <tag></tag>
   <elementGuidId>35d82c6e-e8c4-4e4b-a760-685538417f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_lnkPreInscripcion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkPreInscripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ce8b27e-c1e1-4b3b-b09d-1118a870f31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkPreInscripcion</value>
      <webElementGuid>4df9ab50-b2c4-40ca-b889-903909e6cfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1bedb58c-bd24-4bca-9fbd-23a35295d812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$lnkPreInscripcion','')</value>
      <webElementGuid>2385e0d7-fa4f-4b50-a831-94b7b16c0637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulario de Pre-Inscripción</value>
      <webElementGuid>ea1bd912-8fcc-422e-8678-75dac79944fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkPreInscripcion&quot;)</value>
      <webElementGuid>eb4007dd-b32d-41cf-a33b-77a8d3649ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkPreInscripcion']</value>
      <webElementGuid>a5a55346-848a-49a8-93f5-18f49ed26aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPreInscripcion']/div/div/a</value>
      <webElementGuid>22d79cec-4ab7-49cb-b518-928b9f1a6d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Formulario de Pre-Inscripción')]</value>
      <webElementGuid>3f9720aa-e685-434f-8709-09fcde29c536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentación a presentar'])[1]/following::a[1]</value>
      <webElementGuid>5b189e3b-e8ab-4034-a8db-9250f2178282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedimiento de Inscripción y Actualización'])[1]/preceding::a[1]</value>
      <webElementGuid>bf3064b8-5ec4-4c3d-922c-5fd71ae43527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Formulario de Pre-Inscripción']/parent::*</value>
      <webElementGuid>2de3e598-2a61-48fd-8c6d-342807914b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$lnkPreInscripcion','')&quot;)]</value>
      <webElementGuid>13a307c3-c7e6-4512-b6a9-ef60e141683e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>39b11e0b-4ffb-4499-9dff-6af848d98c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkPreInscripcion' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$lnkPreInscripcion&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Formulario de Pre-Inscripción' or . = 'Formulario de Pre-Inscripción')]</value>
      <webElementGuid>fce88277-e53b-4cc7-ab7f-ffb36fee882f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
