<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputRazonSocial</name>
   <tag></tag>
   <elementGuidId>86a46b57-cf87-4945-8f8c-eacb1d11a5d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_GenerarProveedor_txtRazonSocial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_GenerarProveedor_txtRazonSocial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1860665e-d423-4272-87e1-a2acee7f464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$GenerarProveedor$txtRazonSocial</value>
      <webElementGuid>339275c8-8907-4293-91b0-e86b5dd67161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3503a674-a829-4aa3-a10d-0f79459a6ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_GenerarProveedor_txtRazonSocial</value>
      <webElementGuid>600cb17b-f57f-4c70-b993-0a5abaae7ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16c100fb-d062-439d-bebc-83a878916174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_GenerarProveedor_txtRazonSocial&quot;)</value>
      <webElementGuid>b6b2a044-606b-4414-8f16-60c0b108b48c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_GenerarProveedor_txtRazonSocial']</value>
      <webElementGuid>06871230-57b3-4fc0-b0b5-ee756a807a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivRazonSocial']/input</value>
      <webElementGuid>53a42b40-b87a-4698-9657-4018c6559210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>9cba5ec5-38e5-4c87-b455-5c3017dc6b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$GenerarProveedor$txtRazonSocial' and @type = 'text' and @id = 'ctl00_CPH1_GenerarProveedor_txtRazonSocial']</value>
      <webElementGuid>01a3c96c-b16b-4765-8400-bfdefb2989dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
