<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCUIT</name>
   <tag></tag>
   <elementGuidId>85d51613-ee41-413a-ad40-88b1a24885fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_GenerarProveedor_txtCUITEmpresa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_GenerarProveedor_txtCUITEmpresa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>492a6dbb-14aa-4a20-861a-d847e667ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$GenerarProveedor$txtCUITEmpresa</value>
      <webElementGuid>b65e4d2c-8fa0-4d29-8e77-f3a0eed33c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61d75b6e-5830-4b19-a781-868367c58a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ecaded17-718f-4a45-a15a-8bf13d4733e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_GenerarProveedor_txtCUITEmpresa</value>
      <webElementGuid>1b93d6da-5057-4384-a6cd-1ed8e4fc31c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58fdd8a2-c138-407d-ac7c-530ec18dd9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>mascara(this,'-',patronCUIT,true)</value>
      <webElementGuid>73dca542-b68f-475f-ae5b-983d2ddce102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>4e7a27f2-31dd-4f3f-952e-32d4ae687617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_GenerarProveedor_txtCUITEmpresa&quot;)</value>
      <webElementGuid>a55f6ddf-c8f4-4103-8a1c-8a7a928ce699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_GenerarProveedor_txtCUITEmpresa']</value>
      <webElementGuid>a125e6f5-6d91-4020-b431-7405e8c32285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_GenerarProveedor_DivCUITEmpresa']/input</value>
      <webElementGuid>5d0ae63b-dbc0-4edc-90e4-fab5dd436ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>d0d1d2ab-408b-4601-8efd-b44c1f9ac7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$GenerarProveedor$txtCUITEmpresa' and @type = 'text' and @id = 'ctl00_CPH1_GenerarProveedor_txtCUITEmpresa']</value>
      <webElementGuid>93170f53-95e9-46e2-9c47-8d9e6f6292f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
