<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbTipoProveedorExtranjero</name>
   <tag></tag>
   <elementGuidId>5c60c16f-997d-4ea3-9669-49f7ca158e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80da8ecf-57d1-4888-8fb7-12b9831e0d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal</value>
      <webElementGuid>a6402869-5c5a-4f0c-a409-f0457362850b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4ace5ad5-1c34-41e1-8870-3fd67a507db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$GenerarProveedor$rbTipoProveedor</value>
      <webElementGuid>e35b3706-a4a0-4253-964a-488982bdabe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbExtrajeroSinSucursal</value>
      <webElementGuid>6902a079-4bed-4428-b145-c0ffab6ed2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$GenerarProveedor$rbExtrajeroSinSucursal\',\'\')', 0)</value>
      <webElementGuid>cc743566-f8e4-444e-ad4c-0139bd6ae6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal&quot;)</value>
      <webElementGuid>65dca564-390f-4818-8e19-6cb93ae5c3ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal']</value>
      <webElementGuid>d4aac302-00c7-44ec-b3db-91d20d296689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_GenerarProveedor_divExtranjero']/div[2]/input[2]</value>
      <webElementGuid>ced6aa72-ab8a-452c-ac4b-2608e4f0fabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input[2]</value>
      <webElementGuid>43d49e5d-a54d-452c-93ce-158ddd3663fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_GenerarProveedor_rbExtrajeroSinSucursal' and @type = 'radio' and @name = 'ctl00$CPH1$GenerarProveedor$rbTipoProveedor']</value>
      <webElementGuid>2069c4bd-ac01-402b-b6b5-fc61a2e48e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
