<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CUITCUIL_nDocumento</name>
   <tag></tag>
   <elementGuidId>569909d3-0f52-4a4d-ac37-9805ff6a2f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nDocumento' and @name = 'nDocumento' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nDocumento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nDocumento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1da6cf9-bf23-4c6c-9799-c3b82dfb4cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69cb43f0-989e-44a3-9f6e-e3f7845e69c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nDocumento</value>
      <webElementGuid>071f8847-0b60-4b94-9802-349a6b8b40df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nDocumento</value>
      <webElementGuid>4f712d09-ef47-4f26-ad1c-eb2491a3c6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nDocumento</value>
      <webElementGuid>99d34d8a-3db9-46ee-84f9-2fdac5449861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e7d9d41-cfb1-4057-bab9-b1bf407fd8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>be5e4367-934c-45f3-a7a9-73bdca206a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nDocumento&quot;)</value>
      <webElementGuid>1c14f995-fa8e-4d94-9324-b6269be9f1b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nDocumento']</value>
      <webElementGuid>9a9d5981-9e68-4c9f-beaf-703c41d8d09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/div/div[6]/div/div/input</value>
      <webElementGuid>124275a4-df09-4b78-a10b-8852cef126be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>3f4cc56a-3ebc-4086-a050-70349ddd5d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nDocumento' and @name = 'nDocumento' and @type = 'text']</value>
      <webElementGuid>6c34838a-b208-427f-85d2-8c37d0fa7e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
