<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn__AlcanceYPeriodicidadSPR</name>
   <tag></tag>
   <elementGuidId>7963c488-c686-42fc-b534-c10e898602f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6af1a14a-97d5-4df5-821f-87b9a56f8e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR</value>
      <webElementGuid>1946183e-86ab-45dc-a5a3-9804eeccc72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f5c3419-6685-4169-99e9-15d7c61d0407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-pencil</value>
      <webElementGuid>30fdd393-ae1e-4c2c-8087-e429f15745bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR&quot;)</value>
      <webElementGuid>65521644-f464-40dc-aa2c-93850f8f064d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR']</value>
      <webElementGuid>8249ca55-2814-4f67-b116-e0807711954e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkAlcancePeriodicidadSPR']/span</value>
      <webElementGuid>fdde567b-8bd1-4930-abd1-0eef128a0d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a/span</value>
      <webElementGuid>8f1cf0ee-153a-4c1b-a1cb-2c2e0657db3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_iconoIndiceAlcanceYPeriodicidadSPR']</value>
      <webElementGuid>2c3b50d4-9a4f-4c69-987b-975f85b36593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
