<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Guardada</name>
   <tag></tag>
   <elementGuidId>1c26d462-9339-415c-a7a6-6394a45ead4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_botoneraCabecera_lblEstadoOferta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_botoneraCabecera_lblEstadoOferta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6a5c8f7-7561-41ff-bc1e-7d692a5d764b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_botoneraCabecera_lblEstadoOferta</value>
      <webElementGuid>3644c8c2-5ab2-444a-88fd-608da213707f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardada</value>
      <webElementGuid>c3c5b36f-ce19-4655-a0a4-94c9c47ada4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_botoneraCabecera_lblEstadoOferta&quot;)</value>
      <webElementGuid>a219d792-a91f-47ea-87fb-4ebb53db8279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_botoneraCabecera_lblEstadoOferta']</value>
      <webElementGuid>70015a7e-17df-4b10-b13d-020533fd47d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/section/div[2]/div[4]/div/div[4]/div/span[2]</value>
      <webElementGuid>9ed7dee5-3666-4849-9696-8c8abb811ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado de la oferta:'])[1]/following::span[1]</value>
      <webElementGuid>03e22b9f-af56-4508-b912-f8c1858da2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección General de Compras y Contrataciones'])[1]/following::span[4]</value>
      <webElementGuid>682ad598-bee6-4082-8b48-2ecb4bd61aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cómo realizar una oferta?'])[1]/preceding::span[1]</value>
      <webElementGuid>7ef9566c-b7c0-4f36-ba78-4e2bc03ed7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe ofertar la totalidad de los renglones.'])[1]/preceding::span[1]</value>
      <webElementGuid>eb8b286d-c1f1-42ba-8b63-92bd3a730bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardada']/parent::*</value>
      <webElementGuid>6da399ad-c228-4e86-af2a-07fa2b4146f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span[2]</value>
      <webElementGuid>7ab750af-5281-417c-86ea-136ebc02275e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_botoneraCabecera_lblEstadoOferta' and (text() = 'Guardada' or . = 'Guardada')]</value>
      <webElementGuid>73479c89-f46c-479b-8f98-04cb7f141543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
