<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Guardar y Volver</name>
   <tag></tag>
   <elementGuidId>e19e77e0-7dc3-4ee5-ad6d-ce6e1bed26a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkBtnGuardarYVolver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_lnkBtnGuardarYVolver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66186d44-a7c8-47ec-8a32-53315ca10496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidarPagina();</value>
      <webElementGuid>785e6fb9-7cab-426d-ad64-503e8ff5105d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkBtnGuardarYVolver</value>
      <webElementGuid>cb6545eb-622b-4e97-87e6-bc3292427a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_verde_g_238</value>
      <webElementGuid>cbc0f1a7-cca6-4207-999b-492d0205f0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>d7f75851-21b7-43a6-8af6-42e6e7150c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkBtnGuardarYVolver&quot;, &quot;&quot;, true, &quot;TiposDias&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>d9caab23-4465-4771-85dc-8054dc342f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar y Volver</value>
      <webElementGuid>1a633304-7fa2-412b-b451-0abea30e5d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkBtnGuardarYVolver&quot;)</value>
      <webElementGuid>c21b7bbc-67b5-4368-a3bd-cf90e2cb7414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkBtnGuardarYVolver']</value>
      <webElementGuid>f450032c-ad1a-43e2-a318-c03b647d9e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[7]/div/a</value>
      <webElementGuid>828eaae0-7770-4f5c-b264-2ad2e8fa136d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Guardar y Volver')]</value>
      <webElementGuid>1fedf99f-7662-4de6-9477-3cb5a558f9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad estimada para el Plazo de Mantenimiento.'])[1]/following::a[1]</value>
      <webElementGuid>ba1885c3-1653-4b15-980f-500eb108870b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El valor ingresado no es válido.'])[5]/following::a[1]</value>
      <webElementGuid>499add94-d674-44e7-b907-1f090b4002b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::a[1]</value>
      <webElementGuid>8b1866f9-29bc-422b-994a-9e1ebf70808e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar y Volver']/parent::*</value>
      <webElementGuid>21289a35-3e93-403a-927e-5eb39d6cf64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkBtnGuardarYVolver&quot;, &quot;&quot;, true, &quot;TiposDias&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>e92b249c-78ac-412f-ba31-9c3e83c34838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a</value>
      <webElementGuid>9f237aba-5b2d-4221-9291-c70b6fa7f2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkBtnGuardarYVolver' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkBtnGuardarYVolver&quot;, &quot;&quot;, true, &quot;TiposDias&quot;, &quot;&quot;, false, true))' and (text() = 'Guardar y Volver' or . = 'Guardar y Volver')]</value>
      <webElementGuid>3b8b7b21-2ac4-493a-9d85-522600e69b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
