<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPlazoMantenimiento</name>
   <tag></tag>
   <elementGuidId>1b287226-0bf9-46df-806c-26d4a4561da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtCantidadDiasPlazoMantenimiento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtCantidadDiasPlazoMantenimiento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c005365b-0845-4107-8d5c-510dd4e8b677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtCantidadDiasPlazoMantenimiento</value>
      <webElementGuid>8a4a4121-e933-4ace-9982-0e476a636a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2addd17-83ef-407d-9583-0084d910ff26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$txtCantidadDiasPlazoMantenimiento&quot;, &quot;&quot;, true, &quot;CantidadMaximaDiasMantenimiento&quot;, &quot;&quot;, false, true))', 0)</value>
      <webElementGuid>e461163f-213c-4bff-949c-9c730f8cdb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return SoloNumeros(event);</value>
      <webElementGuid>56f4de2b-b1db-4da4-bea8-920ca12c8853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtCantidadDiasPlazoMantenimiento</value>
      <webElementGuid>05a628ea-66c0-492f-9eaf-ae12243e4ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtCantidadDiasPlazoMantenimiento&quot;)</value>
      <webElementGuid>bd8b5145-8fd8-4161-ab8c-b87412470610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtCantidadDiasPlazoMantenimiento']</value>
      <webElementGuid>177a7a91-bccb-4033-a631-8e1408f1ece8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_div7']/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>758da23b-5487-4533-ac36-9ba0d3945710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>c935de22-27e9-41bb-9d05-85b657f2e268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtCantidadDiasPlazoMantenimiento' and @type = 'text' and @id = 'ctl00_CPH1_txtCantidadDiasPlazoMantenimiento']</value>
      <webElementGuid>4ec99c98-0a23-4744-a036-eab12b1264de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
