<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPlazoEjecucion</name>
   <tag></tag>
   <elementGuidId>a62e42dc-62e5-4e98-88a7-ebd7c7652bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtCantidadDiasPlazoEjecucion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtCantidadDiasPlazoEjecucion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76e6b561-5821-4591-8e39-f0d600f59b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtCantidadDiasPlazoEjecucion</value>
      <webElementGuid>4ae04e45-40aa-471e-a270-e034ac9d5fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>839fceec-213f-4ee5-b01a-ae9173972ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$txtCantidadDiasPlazoEjecucion&quot;, &quot;&quot;, true, &quot;CantidadMaximaDiasEjecucion&quot;, &quot;&quot;, false, true))', 0)</value>
      <webElementGuid>8b498263-6175-4492-96f6-8e556d950ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return SoloNumeros(event);</value>
      <webElementGuid>4f0ec550-17eb-4586-ba09-a3e45c384d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtCantidadDiasPlazoEjecucion</value>
      <webElementGuid>9603754b-4e5c-42c3-a8f4-722594d089f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtCantidadDiasPlazoEjecucion&quot;)</value>
      <webElementGuid>8fb90bc4-359b-4276-8bf9-1de8072512ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtCantidadDiasPlazoEjecucion']</value>
      <webElementGuid>893b2efb-3857-43d8-a9eb-7cb68dd27ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_div1']/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>6b0d5368-ff3c-42c8-90d8-77235c864c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>c00fd947-653f-4427-8638-d74de6e5af18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtCantidadDiasPlazoEjecucion' and @type = 'text' and @id = 'ctl00_CPH1_txtCantidadDiasPlazoEjecucion']</value>
      <webElementGuid>f86beb0a-ddaa-4a07-a809-3b044793b067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
