<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPlazoCertificacion</name>
   <tag></tag>
   <elementGuidId>2d60ca8e-0d39-4c3c-ac5c-84fbfc11af7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_CantidadDiasPlazoCertificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_CantidadDiasPlazoCertificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2343fac9-1fa1-4280-83bc-052a51ead6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$CantidadDiasPlazoCertificacion</value>
      <webElementGuid>cf4e4e3d-5fee-457a-9c35-95daeb324148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5224e87-baa4-45ca-acd7-c790f02bf078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$CantidadDiasPlazoCertificacion&quot;, &quot;&quot;, true, &quot;CantidadMaximaDiasCertificacion&quot;, &quot;&quot;, false, true))', 0)</value>
      <webElementGuid>1c5e33dd-09cc-4fd9-afdc-bc1b15f61beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return SoloNumeros(event);</value>
      <webElementGuid>cc60abdd-bf85-4533-993a-ad2a623add38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_CantidadDiasPlazoCertificacion</value>
      <webElementGuid>1c974e23-eddc-4fa7-b70e-e0548fe63744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_CantidadDiasPlazoCertificacion&quot;)</value>
      <webElementGuid>bc830fa1-d9c1-461c-ac5b-9382c91e824b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_CantidadDiasPlazoCertificacion']</value>
      <webElementGuid>ef05ed8c-79f0-4513-b9e0-b3c45a0a69b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_div4']/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f07a8a3a-515f-4fbf-8209-3b7754c3b575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>80e605db-b1f2-418c-9ebf-34bb51a3d517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$CantidadDiasPlazoCertificacion' and @type = 'text' and @id = 'ctl00_CPH1_CantidadDiasPlazoCertificacion']</value>
      <webElementGuid>8d69044c-2335-4a31-bf35-41b4dfd6199c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
