<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_ProcedimientoDelSeleccionOCA</name>
   <tag></tag>
   <elementGuidId>7d83c9e8-be89-40bc-bc2c-6f81ff10b624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblLicitConcursoCont_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rblLicitConcursoCont_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>587f0c38-bf66-4e23-8b45-4107330755cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rblLicitConcursoCont_2</value>
      <webElementGuid>d02a00a8-716f-4045-8bbb-7185e39910f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0414b2ec-b2bf-4744-9cae-4aaea42c7ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rblLicitConcursoCont</value>
      <webElementGuid>51ba9dfe-a465-4a2d-a836-70ff277f67ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Licitación Pública</value>
      <webElementGuid>4d49da61-44ee-418f-b1cc-6af0a41374bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>bf9431b8-a2b5-41ac-b8ce-b080793d825e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rblLicitConcursoCont_2&quot;)</value>
      <webElementGuid>f54ca958-a6ba-4255-a379-b71a03e1fe94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblLicitConcursoCont_2']</value>
      <webElementGuid>d9efaea2-4412-4ac9-b86a-378c8393b70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblLicitConcursoCont']/tbody/tr[2]/td/input</value>
      <webElementGuid>45dbf455-5865-40e3-87d8-87079216c837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>be0d177d-d25c-4497-8db0-37eb85956350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblLicitConcursoCont_2' and @type = 'radio' and @name = 'ctl00$CPH1$rblLicitConcursoCont' and @checked = 'checked']</value>
      <webElementGuid>a2c174fa-95f6-4382-a314-d43cbf12af69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
