<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_EncuadreLegalOCA</name>
   <tag></tag>
   <elementGuidId>1a4aed3a-b627-4cff-8244-d518b984651e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_lstEncuadreLegal']/option</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;75&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>99849bf1-3c8f-4670-87fc-03f0e45a6594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>ad213a54-8684-4c29-8d6e-a3b44c2c61f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 31 y 40</value>
      <webElementGuid>a5f3f2fa-e36d-40f1-93db-d99766143579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lstEncuadreLegal&quot;)/option[1]</value>
      <webElementGuid>8bd55987-cb1e-409a-88bb-d3ba551c8083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='75']</value>
      <webElementGuid>befb4dee-c2ee-43f3-baff-5ce9631f4edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_lstEncuadreLegal']/option</value>
      <webElementGuid>e5228a2f-8087-41ef-8c47-3e7c84dc87a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encuadres legales seleccionados'])[1]/following::option[1]</value>
      <webElementGuid>a5ca475d-caec-4739-8768-ab9905a12a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listado encuadres legales'])[1]/following::option[1]</value>
      <webElementGuid>b063560b-ffa0-44d1-ab04-3fee7aa2256b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione los encuadres legales que se regirá el Proceso de Contratación.'])[1]/preceding::option[1]</value>
      <webElementGuid>4866ba47-680c-4bef-abf8-caaf5285ab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente Paso'])[1]/preceding::option[1]</value>
      <webElementGuid>f65af40a-f0c8-4426-995e-b19dbb3d5048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 31 y 40']/parent::*</value>
      <webElementGuid>92d9aefb-a303-467c-a728-cc810aeebc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option</value>
      <webElementGuid>5f075995-094b-4d46-b9af-2100918413b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 31 y 40' or . = 'Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 31 y 40')]</value>
      <webElementGuid>0dfed1e3-1dc7-496b-abaa-f3490f0a6e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
