<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_btnAgregarProcesoCompra</name>
   <tag></tag>
   <elementGuidId>ad1aac4d-cfc9-4307-8eef-7bbfed9ca749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_btnVerNroProcesoCompra</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_btnVerNroProcesoCompra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>439dfd86-4e4c-4edd-bab1-032e8ed9f6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1bb57be3-a930-424d-a2a8-6fd0d5cbcb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$btnVerNroProcesoCompra</value>
      <webElementGuid>6ba480f0-6634-4bbd-b42f-95c6e30332ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_btnVerNroProcesoCompra</value>
      <webElementGuid>9b85ffae-cb51-464f-a724-95f0bea2d1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/botones/b_int_agregar.gif</value>
      <webElementGuid>919a3841-09ef-4ed6-aa57-9dcdf791e283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>df08eaac-134e-4e22-96d6-fbc106fec894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:return ValidarNumeroSolicitud();</value>
      <webElementGuid>82b44457-381e-410e-b636-61f6eaf14316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_btnVerNroProcesoCompra&quot;)</value>
      <webElementGuid>220c0892-1c4f-4ff2-98f8-6b287a3448e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_btnVerNroProcesoCompra']</value>
      <webElementGuid>0655bf95-46de-4349-a4c9-cef7569877f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[7]/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>22a00dd2-2deb-44ba-80b2-851adb936c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>94090d38-22e3-49f7-aaf1-1a46ce6a4793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$btnVerNroProcesoCompra' and @id = 'ctl00_CPH1_btnVerNroProcesoCompra' and @src = '/App_Themes/styles-viejo/imagenes/botones/b_int_agregar.gif']</value>
      <webElementGuid>01945536-957a-4612-be17-b999196f0bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
