<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Reporte Cuenta Corriente del Beneficiario</name>
   <tag></tag>
   <elementGuidId>59123785-5ed3-4848-bce3-1507da99f6c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='idInformeCredito']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idInformeCredito</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Reporte Cuenta Corriente del Beneficiario' or . = 'Reporte Cuenta Corriente del Beneficiario')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2ef63f10-2d77-428b-9512-32adea42d882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button</value>
      <webElementGuid>dd89e142-338c-4334-834e-c86bb27efde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>785657a4-a505-4b87-aeb5-0d54a0574ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>957a621c-4b18-48c3-bdb2-53edb0c84aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0eb3b8aa-25e6-419f-af8b-d5f8aefab218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idInformeCredito</value>
      <webElementGuid>5e404cd1-39d1-4ff0-a71f-a47eee471920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reporte Cuenta Corriente del Beneficiario</value>
      <webElementGuid>f333e123-1135-4470-b8e9-b2b438bdf8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idInformeCredito&quot;)</value>
      <webElementGuid>4fbfc8bd-d53b-4baa-ac14-bd237f2a67a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='idInformeCredito']</value>
      <webElementGuid>3434463f-28c7-4188-b4e8-73c5a31898bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account-menu']/div[3]/ul/ul/li[3]</value>
      <webElementGuid>940b679e-2eb2-494d-8368-689f5ed5ff21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::li[1]</value>
      <webElementGuid>7e29bb23-8585-4cd0-afb1-3f7e1b0d0d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi Perfil'])[1]/following::li[2]</value>
      <webElementGuid>3ed1242a-17a8-4e70-aa90-588b48a81328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/preceding::li[1]</value>
      <webElementGuid>4f80353e-c1fb-4423-bbef-4c8edf6456f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>d66126cc-4790-42b2-9670-6c9b7d89aaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'idInformeCredito' and (text() = 'Reporte Cuenta Corriente del Beneficiario' or . = 'Reporte Cuenta Corriente del Beneficiario')]</value>
      <webElementGuid>88f18229-d454-46e4-b70b-14e59fea0d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
