<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Aceptar</name>
   <tag></tag>
   <elementGuidId>beecf211-2446-46ba-924d-a06eb03245d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85cc4774-7266-4aae-ad6b-769cc36fcab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:return ValidacionDePorcentaje();</value>
      <webElementGuid>75d2e687-e0f5-4936-9efe-72d841d0d5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje</value>
      <webElementGuid>72cf2454-960d-48dc-8b62-5e8ec3c7f01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>3dbb3021-ad55-4d6c-b0bf-6d6fb4b6972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$UCItems$UCModalEditarPorcentaje$lnkConfirmarPorcentaje','')</value>
      <webElementGuid>c87b64eb-fb76-4fe7-a8ff-2bfa5baa29f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>38db6c80-18fb-4094-9c92-8e8ec29e2260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje&quot;)</value>
      <webElementGuid>84c83c92-c579-4f44-8051-a602624aa6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje']</value>
      <webElementGuid>7d5008ce-f0bc-43c0-b0f8-c5b5c8559314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_UCItems_UCModalEditarPorcentaje_modalEditarPorcentaje']/div/div/div[3]/div/div/a[2]</value>
      <webElementGuid>d5fa724a-f6a8-43d3-a1dc-29b8a5400fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Aceptar')])[2]</value>
      <webElementGuid>e5005c0f-fbe3-4e2f-94d0-729d739db206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/following::a[1]</value>
      <webElementGuid>ada65a79-b5b8-49e6-8b22-ad9361b3d199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Por favor verifique que todos los datos obligatorios hayan sido ingresados y estén correctos.'])[1]/preceding::a[1]</value>
      <webElementGuid>93eb4734-b429-461b-9f02-a8dff1e2b2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar acción'])[1]/preceding::a[1]</value>
      <webElementGuid>b0c3e284-6b33-4223-8062-715fd3d751b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$UCItems$UCModalEditarPorcentaje$lnkConfirmarPorcentaje','')&quot;)]</value>
      <webElementGuid>5bd8f964-cdae-47fd-b89a-99fffa61b9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[2]</value>
      <webElementGuid>2ead8f82-7e4f-4378-8f7b-375b7cd76f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UCItems_UCModalEditarPorcentaje_lnkConfirmarPorcentaje' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$UCItems$UCModalEditarPorcentaje$lnkConfirmarPorcentaje&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>e7073902-1a65-4b64-a3e3-c8cf0c8b758a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
