<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_iconoIndiceItems</name>
   <tag></tag>
   <elementGuidId>7b806936-b905-4fb6-a8f7-cdca4ee4354b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_iconoIndiceItems']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_iconoIndiceItems</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b18fa08b-6255-4114-8d62-d31025014928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_iconoIndiceItems</value>
      <webElementGuid>16c064c8-f7b2-41ed-8077-02411ee8c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-pencil</value>
      <webElementGuid>68991d12-a9f1-4589-9f1f-cd6afcc1dcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0686ad4-f2ab-4e6e-9a92-ea35677e197a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_iconoIndiceItems&quot;)</value>
      <webElementGuid>86efda61-f4f4-4b1f-8d1b-ba4726e68793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_iconoIndiceItems']</value>
      <webElementGuid>09121bcd-5052-4414-b7b8-f8a32fa7775e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkItems']/span</value>
      <webElementGuid>611d3807-57de-48a8-a75f-a6cb1103370d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a/span</value>
      <webElementGuid>399bc13c-ce5f-4151-a11b-c26617f6068b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_iconoIndiceItems']</value>
      <webElementGuid>cccd0386-ac9f-4090-8fa0-744e1951b26f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
