<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkClase</name>
   <tag></tag>
   <elementGuidId>c66ef5eb-7fec-4117-ab43-84c7f0abbcff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68758a56-2b21-472b-935e-a6c4c9906df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase</value>
      <webElementGuid>82d744fd-9355-4952-8d77-7fb3eec9914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dd248d3f-6e52-4a2e-9b84-aeac896961c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$resultadosBusquedaProductos$rptResultadosBusquedaProductos$ctl01$cbClase</value>
      <webElementGuid>fbe93d91-80f3-4195-b5cf-8b1edddcfcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$resultadosBusquedaProductos$rptResultadosBusquedaProductos$ctl01$cbClase\',\'\')', 0)</value>
      <webElementGuid>c886557e-f70b-4ae4-bc7c-b64d4ec35e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase&quot;)</value>
      <webElementGuid>9e1a148b-36c0-4aab-a849-cc79f28d7aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase']</value>
      <webElementGuid>0345ea61-a603-44bb-ba85-af658e7a1e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_updateGrupo']/div/div/h4/span/input</value>
      <webElementGuid>1dc89ee3-ed29-4080-b973-c579d899d56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b0e2de4c-3599-4d84-9bed-d11b7b822f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_resultadosBusquedaProductos_rptResultadosBusquedaProductos_ctl01_cbClase' and @type = 'checkbox' and @name = 'ctl00$CPH1$resultadosBusquedaProductos$rptResultadosBusquedaProductos$ctl01$cbClase']</value>
      <webElementGuid>3ca4a3ad-4d0d-444f-a242-a4f11e9fae8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
