<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descripcion</name>
   <tag></tag>
   <elementGuidId>609e5378-1e4d-426c-a787-7ebde3cf4f28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_buscadorProductos_txtBuscarProducto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_buscadorProductos_txtBuscarProducto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a6538f6-d6d4-4bde-bfd5-0f7306cf9566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$buscadorProductos$txtBuscarProducto</value>
      <webElementGuid>c8c42986-e076-46d1-8777-5a9a1b161bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b25d17da-eb9c-4a97-8fc0-f95c5b845ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>GEL</value>
      <webElementGuid>ec59d3c9-ad66-4fd0-b87d-0dca4527545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_buscadorProductos_txtBuscarProducto</value>
      <webElementGuid>8e72d346-da9e-4b73-a70c-dea82269dd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead form-control</value>
      <webElementGuid>9a14b2b8-b404-445b-a5aa-8aef0f1473d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_buscadorProductos_txtBuscarProducto&quot;)</value>
      <webElementGuid>c93ad258-f837-499e-b771-8a96a525fb0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_buscadorProductos_txtBuscarProducto']</value>
      <webElementGuid>aa069165-d06d-4ec1-b7e6-469e021dc06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_tabBuscadorProductos']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f9486560-a7f3-40a0-9cd9-3c01a5376260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>f11cd8e7-0188-4cbd-bdd8-5b010a8b5603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$buscadorProductos$txtBuscarProducto' and @type = 'text' and @id = 'ctl00_CPH1_buscadorProductos_txtBuscarProducto']</value>
      <webElementGuid>168ffbbe-82b5-4d08-8398-4c0d19b12c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
