<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectGrupo</name>
   <tag></tag>
   <elementGuidId>77512a29-c6d0-48d9-9656-1eeee2ce7d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cbd94286-cc66-443b-8142-bd7f8f4c48b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$buscadorPorRubroYGrupo$ddlGrupo</value>
      <webElementGuid>14ccea2b-4d54-42ce-8314-11263b07b03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$buscadorPorRubroYGrupo$ddlGrupo\',\'\')', 0)</value>
      <webElementGuid>41f69ad2-be51-427d-9608-0e666aa50321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo</value>
      <webElementGuid>0a3a039c-ddf8-420b-a853-6920dfad79d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc9a7295-38ea-4d4a-9032-9e888521b467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Seleccionar

	</value>
      <webElementGuid>3fe0e70f-9872-4b6a-8c29-140650c8e8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo&quot;)</value>
      <webElementGuid>f2358b97-9cee-4726-8664-42149fe99fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo']</value>
      <webElementGuid>00cfca04-2dab-4212-b26d-8b4fd9e1d024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_tabBuscadorPorRubroYGrupo']/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>2bda5f40-88d8-4542-85df-d0c08e7d5b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo:'])[1]/following::select[1]</value>
      <webElementGuid>8c0019f6-66db-4fe8-a171-3b27e36ddd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rubro:'])[1]/following::select[2]</value>
      <webElementGuid>edf72f8f-6f60-4891-98d8-fef225700bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar producto'])[1]/preceding::select[1]</value>
      <webElementGuid>8a5a55ea-03c1-49d6-b89d-0e3f25d21940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/preceding::select[1]</value>
      <webElementGuid>ffc89d83-5707-48b7-97e2-238f7d425b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7dbf5083-9ece-45c9-a388-dddf82126d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$buscadorPorRubroYGrupo$ddlGrupo' and @id = 'ctl00_CPH1_buscadorPorRubroYGrupo_ddlGrupo' and (text() = '
		Seleccionar

	' or . = '
		Seleccionar

	')]</value>
      <webElementGuid>f9abb22f-6e4c-44a9-a559-3a46c070ae88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
