<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ttulo_folderTitle</name>
   <tag></tag>
   <elementGuidId>1c367720-3d06-4158-a227-8c91422dff40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'folderTitle' and @name = 'folderTitle' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='folderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2545cb44-6d5d-4e85-93ef-ee1f581f259b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f997beb-6a73-435a-8014-e705d0460c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>folderTitle</value>
      <webElementGuid>d6cf75a5-ffc4-458c-a086-14b036c79d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderTitle</value>
      <webElementGuid>bf100d72-df4e-44f5-9262-2d29d4c96ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>folderTitle</value>
      <webElementGuid>32ebf296-987d-4a12-8e1a-c7ceaae4ba4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>176279d7-6399-4cde-9d96-e7b52096413c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>45dd2736-8c12-41cc-85f3-080e232e9dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TituloModificado</value>
      <webElementGuid>19461473-b639-4141-8b7d-90a064cca4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderTitle&quot;)</value>
      <webElementGuid>1e40dec9-f07c-4eb4-bda4-f6bdac01ff0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='folderTitle']</value>
      <webElementGuid>73c0a93c-b0d3-4b68-9342-7a0f4db7bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/form/div/div[15]/div/div/input</value>
      <webElementGuid>df57afea-4397-44ba-8793-dd8feff29097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/input</value>
      <webElementGuid>821f1ef7-d8f4-4173-8e4e-52a582d38a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'folderTitle' and @name = 'folderTitle' and @type = 'text']</value>
      <webElementGuid>dbd00e28-385b-41ad-89cf-6515c8e4038b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
