<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAgregar</name>
   <tag></tag>
   <elementGuidId>6d3a3215-727b-4eaf-a7f5-10ee15833741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9624e3fd-d3ed-415a-82ee-44a9ccc82640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: return ValidarSeccion(this);</value>
      <webElementGuid>6364091a-874a-4e17-844d-611c8ce8d96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona</value>
      <webElementGuid>5a87d07e-2c4c-402a-b665-073570a24277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>d8cc0efb-6625-4a72-9dcb-91d6360a06ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$datosPersonasLegales$lnkAgregarPersona','')</value>
      <webElementGuid>3ae612c0-f723-4cf3-ab6e-4cda2c921281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>3f9c68fb-5baf-48fa-86e9-99b97828a8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona&quot;)</value>
      <webElementGuid>d6d04957-3c4a-4331-974b-86d91a6cc5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona']</value>
      <webElementGuid>1557e57b-38a9-4750-a756-d3acea032ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_div2']/div/div[5]/div/div/div/a</value>
      <webElementGuid>1563aa3f-37eb-4239-a619-6f1aa71b7d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Agregar')])[5]</value>
      <webElementGuid>cb526658-8a51-4fd3-8d44-0d3c64afaa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo electrónico:'])[3]/following::a[1]</value>
      <webElementGuid>cad5ef64-3425-434d-93fe-e4054a503795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personas legales'])[3]/preceding::a[1]</value>
      <webElementGuid>1b2ac4d9-01bf-4050-b7fc-a5ce88dafce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre y apellido'])[3]/preceding::a[1]</value>
      <webElementGuid>69370f6d-dd01-4192-9fbf-144f0895908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$datosPersonasLegales$lnkAgregarPersona','')&quot;)]</value>
      <webElementGuid>b2bb3f64-9fe7-4b44-89d9-2d6e47a5905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[5]/div/div/div/a</value>
      <webElementGuid>d916be27-18f2-4438-9f18-17d83ca8bb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_datosPersonasLegales_lnkAgregarPersona' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$datosPersonasLegales$lnkAgregarPersona&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Agregar' or . = 'Agregar')]</value>
      <webElementGuid>64e5a453-7986-4131-aed2-eced883adf47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
