<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPersonasLegalesNumeroCUIT</name>
   <tag></tag>
   <elementGuidId>3a798e85-9312-45a4-a39c-72b34bad486e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5546ed4f-9dcf-4515-b25e-dc74a4fa16fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosPersonasLegales$txtNumeroCUIT</value>
      <webElementGuid>c3fae055-9dab-47df-946b-96de7e1ae77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05863a39-fbe7-4581-8153-affd8a1dff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT</value>
      <webElementGuid>4b632d67-e233-4367-8d8f-01b65d3afdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b366aa0c-77dd-4dc7-a138-45c89c5a0e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>mascara(this,'-',patronCUIT,true)</value>
      <webElementGuid>c4c4c74a-e539-434e-a607-441b30219bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>0c2599ec-55ba-4861-9b0c-3e2375677c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT&quot;)</value>
      <webElementGuid>862dd63d-0943-4d8a-a1e8-d712e71cad77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT']</value>
      <webElementGuid>45c81c20-1bc4-43ca-9608-2c718edc26a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_DivNumeroCUIT']/input</value>
      <webElementGuid>c652ab45-857d-4167-bf3b-f5638b6ce90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[3]/div/div[3]/input</value>
      <webElementGuid>360cf71f-2bf2-4546-b991-bfcbda5cd87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosPersonasLegales$txtNumeroCUIT' and @type = 'text' and @id = 'ctl00_CPH1_datosPersonasLegales_txtNumeroCUIT']</value>
      <webElementGuid>ce268e7e-42f4-4b8b-bba2-719429c64b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
