<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtApellidoPersonasLegales</name>
   <tag></tag>
   <elementGuidId>75693ca2-0f7a-405f-96ce-93ff2b21ec70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtApellido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_txtApellido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4261bd1-0669-456b-ba38-f3caa4995ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosPersonasLegales$txtApellido</value>
      <webElementGuid>175a6742-6d28-4ff3-9792-47fcf21d26d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83d4a2c5-6013-41fc-a317-e7688130baf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>e387210d-2919-44cd-b175-7e789de28117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_txtApellido</value>
      <webElementGuid>1647b88b-d809-49a0-8a54-4136da94eee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7b379a71-a83a-43c0-be23-4df25eff7b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_txtApellido&quot;)</value>
      <webElementGuid>f0310678-763d-43d3-aeda-b5e709ca7a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtApellido']</value>
      <webElementGuid>1a412a86-8b61-448e-a9a3-030f034d54d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_DivApellido']/input</value>
      <webElementGuid>469c78d8-3943-48fe-ad27-2c6b591a3eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>ac50b5f0-2cfc-4466-b9f2-01c5dee2b431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosPersonasLegales$txtApellido' and @type = 'text' and @id = 'ctl00_CPH1_datosPersonasLegales_txtApellido']</value>
      <webElementGuid>949c2d8b-1f2f-4f9c-8b5b-9f18ef20a0e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
