<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPersonasLegalestNumeroDocumento</name>
   <tag></tag>
   <elementGuidId>adb3b760-08f1-4a5e-ac44-fd58402043bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5593272-247f-45b7-aee2-ff968575126e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosPersonasLegales$txtNumeroDocumento</value>
      <webElementGuid>8a567b65-2b05-4a6e-a620-fd04b7ad6f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02606997-86de-4fb2-979c-c91f45bb82dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9dc5291f-feef-4e7d-be9b-4f54ac7fb9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento</value>
      <webElementGuid>2bddc187-a926-431c-be74-4b38e0ded149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a9a5f36-45a5-4888-b46b-70404a36d09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento&quot;)</value>
      <webElementGuid>dc9bdb5c-4bbc-4ffc-86a0-2f5334b12097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento']</value>
      <webElementGuid>6c984f72-5703-49c4-be8a-7a03e1a1f9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_DivNumeroDocumento']/input</value>
      <webElementGuid>220d3b82-0baf-41a9-8d2d-f377fdaf7c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>a4bb3197-602b-43d5-9ce0-8dfe37260fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$datosPersonasLegales$txtNumeroDocumento' and @type = 'text' and @id = 'ctl00_CPH1_datosPersonasLegales_txtNumeroDocumento']</value>
      <webElementGuid>b04c1e32-13c1-41bc-9408-8044fa06d3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
