<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSexoPersonasLegales</name>
   <tag></tag>
   <elementGuidId>84910b0a-d9bd-4a1e-ba18-bc27d2f5ecef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_datosPersonasLegales_ddlSexo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_ddlSexo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e158ec4-d4d3-4a0d-bc64-a0eba9a97968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosPersonasLegales$ddlSexo</value>
      <webElementGuid>c67f1173-b104-46b1-804f-b68f51254ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_ddlSexo</value>
      <webElementGuid>a7613ab4-46b8-43b7-aa7a-f3542330873a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6679a10d-653b-4160-879d-007e34804265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Seleccionar
		Femenino
		Masculino

	</value>
      <webElementGuid>08f74094-d91c-4348-8ba7-600e7eaff0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_ddlSexo&quot;)</value>
      <webElementGuid>d134787d-9a53-4228-aa15-c083b2d3fece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_datosPersonasLegales_ddlSexo']</value>
      <webElementGuid>1e3154d8-96ab-4937-8f58-b0daedfa30f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_DivSexo']/select</value>
      <webElementGuid>bea9447d-4786-4d72-81fe-a44038166942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexo:'])[3]/following::select[1]</value>
      <webElementGuid>e2d3b1ec-ca36-4fd9-9263-d1caa581d85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completar'])[35]/preceding::select[1]</value>
      <webElementGuid>4668950f-0e8c-4b79-8b8e-5d22272ce8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[2]/div/div[3]/select</value>
      <webElementGuid>d0f562a3-9d0c-4df6-b5a6-17cb1598c5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$datosPersonasLegales$ddlSexo' and @id = 'ctl00_CPH1_datosPersonasLegales_ddlSexo' and (text() = '
		Seleccionar
		Femenino
		Masculino

	' or . = '
		Seleccionar
		Femenino
		Masculino

	')]</value>
      <webElementGuid>26329c1c-2ca1-42ee-8d36-8539a3943210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
