<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PersonasLegalesTipoDoc</name>
   <tag></tag>
   <elementGuidId>927cb567-f12d-4298-8929-2668b9e614d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00f122a8-5913-4976-8ab0-cfbd16894cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$datosPersonasLegales$ddlTipoDocumento</value>
      <webElementGuid>2912b4bd-0a4c-428d-a0b4-bd99bb3afd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento</value>
      <webElementGuid>8cba74c2-014f-4907-a071-481c4075f668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>decf9d89-6fb0-4278-878f-106676513916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	</value>
      <webElementGuid>69020c74-d09e-416d-8b08-f47da66008ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento&quot;)</value>
      <webElementGuid>20b94e05-45cf-4176-9fca-2aca64ae6ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento']</value>
      <webElementGuid>83201434-6dcf-459e-8825-30a944660139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_datosPersonasLegales_DivTipoDocumento']/select</value>
      <webElementGuid>39ad820a-3cde-4592-a592-ba49ed6b479f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo documento:'])[3]/following::select[1]</value>
      <webElementGuid>f6d26978-b1fb-446b-b915-8855a21de1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completar'])[37]/preceding::select[1]</value>
      <webElementGuid>33962886-b204-4717-866f-78f6391a7eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>711e298e-033b-4504-b4fb-afb776df606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$datosPersonasLegales$ddlTipoDocumento' and @id = 'ctl00_CPH1_datosPersonasLegales_ddlTipoDocumento' and (text() = '
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	' or . = '
		Seleccionar
		CI
		DNI
		LC
		LE
		Pasaporte

	')]</value>
      <webElementGuid>4f6efb07-4626-4859-9c77-41675bc64514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
