<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_LeyYDecreto</name>
   <tag></tag>
   <elementGuidId>5346e479-3a36-479b-862b-d3361b89a677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;70&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='70']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>871adf0c-fcde-40b4-8f0b-5e9992dc325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>2eeb5d15-07e7-4264-a204-3ae284f7da0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 28</value>
      <webElementGuid>e139bbd7-97ba-4f8f-99c2-bae5fbe659fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lstEncuadreLegal&quot;)/option[1]</value>
      <webElementGuid>eb11738c-c1d9-43bd-8a51-6530486ead79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='70']</value>
      <webElementGuid>aaf017cb-8a1e-484e-847d-e7b68e130312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_lstEncuadreLegal']/option</value>
      <webElementGuid>8746bc8c-3201-4c18-b613-9bb82812490d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encuadres legales seleccionados'])[1]/following::option[1]</value>
      <webElementGuid>f39cecb6-51fc-41f2-9122-a8fa794a4e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listado encuadres legales'])[1]/following::option[1]</value>
      <webElementGuid>a7195964-036f-47e5-9874-aca8182754a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incisos'])[1]/preceding::option[1]</value>
      <webElementGuid>514a27c4-4b49-4c81-b588-2dc297dbd445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione los encuadres legales que se regirá el Proceso de Contratación.'])[1]/preceding::option[14]</value>
      <webElementGuid>a2150fe4-dd55-4671-9ce4-17252b5bb666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 28']/parent::*</value>
      <webElementGuid>64206b26-2989-4ef7-9a8e-a868609fa614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option</value>
      <webElementGuid>8e5277b3-9e28-47c8-ba6e-3ba859106ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 28' or . = 'Ley N° 2.095 (Texto Consolidado por Ley N° 6.347) y Decreto N° 74/21 Art. 28')]</value>
      <webElementGuid>d18c7ff8-880b-4ef5-a68d-46c5f23ba57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
