<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AgregarMoneda</name>
   <tag></tag>
   <elementGuidId>8a68bf09-3fb7-4e50-af26-2c6c1aeb23b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_imgAgregarMoneda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_imgAgregarMoneda']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26ed22af-d574-4e5c-8368-da017b785644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>faf9b53c-46f2-493a-a7fc-769dc93bd8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$imgAgregarMoneda</value>
      <webElementGuid>d500e711-58f2-4f8c-b40e-2e37e8b52df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_imgAgregarMoneda</value>
      <webElementGuid>1afb62a6-a06a-4210-85d9-81122ef90606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_ok.gif</value>
      <webElementGuid>f320c683-b5f7-44c6-a8d8-78827f387d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agregar Moneda</value>
      <webElementGuid>1ffbcd10-e49f-451d-8c42-d28ab9b594a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_imgAgregarMoneda&quot;)</value>
      <webElementGuid>9b6ec733-e451-4953-a40c-b73554a40bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_imgAgregarMoneda']</value>
      <webElementGuid>b70b9dba-bae0-4531-8602-1111f0f14181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_updpnlSeleccionMoneda']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>11e7c487-1a76-4311-a750-b7267cdf9411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>019a7a04-8198-4b1c-b04e-ae18037144fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$imgAgregarMoneda' and @id = 'ctl00_CPH1_imgAgregarMoneda' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_ok.gif' and @alt = 'Agregar Moneda']</value>
      <webElementGuid>5433b0e8-87bc-4472-b3d8-35a7194d2506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
