<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PorcPreAdjudicacion</name>
   <tag></tag>
   <elementGuidId>9fdde291-ed53-42c1-8185-02ef27770900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtPorcPreAdjudicacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtPorcPreAdjudicacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bb9065d-6e42-4505-9e0f-41691adf9d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtPorcPreAdjudicacion</value>
      <webElementGuid>950def14-aa43-44c6-8161-4bd87b58d93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>420de2f5-ea93-4462-b210-786c9e9f1044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4,00</value>
      <webElementGuid>c2d8bd00-0bdd-4f94-969c-8756b4874b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d39f495f-7153-4dc9-b5a4-3f7433fa8e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4702a730-4820-4bb8-ae87-b3b8253d6063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtPorcPreAdjudicacion</value>
      <webElementGuid>6f43ab03-97ee-4ce6-91ad-de855deaa7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas</value>
      <webElementGuid>074b274f-dc76-4035-92fe-e0ee1df72cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>251b5257-7e1a-4fcc-831f-079978ec6a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>917ea5ce-f0a2-41e6-8f52-cc23cdd016e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtPorcPreAdjudicacion&quot;)</value>
      <webElementGuid>631ecec8-764e-4bc8-8195-47f76b0fb764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtPorcPreAdjudicacion']</value>
      <webElementGuid>637e7876-f6a1-493a-83f7-e6dec9c359a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_divGarImpugPreAdj']/div[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bed8fa32-d1ff-4b35-a936-ac1c5686c376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>9e72386d-9ede-46b9-a7ac-90cfb8d5f6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtPorcPreAdjudicacion' and @type = 'text' and @id = 'ctl00_CPH1_txtPorcPreAdjudicacion']</value>
      <webElementGuid>fc8bf3d9-f86b-4d63-9ccc-8f6e5baded27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
