<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_GarMantOferta</name>
   <tag></tag>
   <elementGuidId>e4f4a4c1-87b0-4af7-9ea0-d5f726505734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rdoGarantiaOfertaCompraMenorSi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@value,'GarantiaOfertaCompraMenor${eleccion}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2135fa4b-afb0-49ec-b3c7-c9c4cad29f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rdoGarantiaOfertaCompraMenorSi</value>
      <webElementGuid>5421225a-b717-45c7-96ac-b93260b292a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>17e9b361-6451-4189-9b41-1574dfa035b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$GarantiaOfertaCompraMenor</value>
      <webElementGuid>1ec46f16-f041-4cd9-b0fb-7be1d1d707f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoGarantiaOfertaCompraMenorSi</value>
      <webElementGuid>f01c5f9a-8638-47aa-b669-d4b9706a4e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rdoGarantiaOfertaCompraMenorSi&quot;)</value>
      <webElementGuid>76e7ba04-32c8-4eb4-bfc8-22dc47434ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rdoGarantiaOfertaCompraMenorSi']</value>
      <webElementGuid>e7f25d8c-edd2-4b19-94aa-e7a8dac713de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGarMantOferta']/div[3]/table/tbody/tr/td/input</value>
      <webElementGuid>135e0f20-389e-4757-8edb-48d24bebe891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[3]/table/tbody/tr/td/input</value>
      <webElementGuid>920fe41f-470b-451f-99d7-61a057201eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rdoGarantiaOfertaCompraMenorSi' and @type = 'radio' and @name = 'ctl00$CPH1$GarantiaOfertaCompraMenor']</value>
      <webElementGuid>8ef775c8-fa2b-4788-82d2-e7c416995f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
