<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_msjPartidasPresupuestariasEnviadas</name>
   <tag></tag>
   <elementGuidId>e2864d33-8f5d-4b0c-b42c-5a1e42bc50e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[@id = 'ctl00_CPH1_msjExitoStrong' and (text() = 'Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.' or . = 'Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_msjExitoStrong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='ctl00_CPH1_msjExitoStrong']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>b740b394-4cf6-4e97-9587-c5c15971a3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_msjExitoStrong</value>
      <webElementGuid>42b91814-c42d-45c5-986c-178bd8b0e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.</value>
      <webElementGuid>efd543b7-df66-4a39-8d5b-66bc6ae305f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_msjExitoStrong&quot;)</value>
      <webElementGuid>9988e2a5-3ba8-4fcf-8d9a-ab9c9069561a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='ctl00_CPH1_msjExitoStrong']</value>
      <webElementGuid>085f7c1c-0d25-4dd1-b82b-0a055da04da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_divExito']/strong</value>
      <webElementGuid>0ab59e45-d904-4607-944d-5d908fd3f773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/following::strong[1]</value>
      <webElementGuid>3f407343-f086-409a-b351-99d021b6a763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='acá'])[1]/preceding::strong[2]</value>
      <webElementGuid>236e62c2-5cea-497a-b95f-ae264b502c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.']/parent::*</value>
      <webElementGuid>534ceaf8-510b-4da8-ba2e-4f83919c620c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/strong</value>
      <webElementGuid>95f3edcf-d909-4227-ab0d-b598562ea63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'ctl00_CPH1_msjExitoStrong' and (text() = 'Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.' or . = 'Las partidas presupuestarias correspondiente las solicitudes de provisión han sido enviadas para afectar el crédito.')]</value>
      <webElementGuid>f8f08069-48d2-4465-a41b-5f5c66108b7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
