<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkTodasSolicitudEstado</name>
   <tag></tag>
   <elementGuidId>f91e7955-0ef0-41df-be40-fc2028942ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rptTablaSPR_ctl00_checkTodos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptTablaSPR_ctl00_checkTodos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>590b024c-bb4d-4945-bc21-0ab281409fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptTablaSPR_ctl00_checkTodos</value>
      <webElementGuid>f7bf5e24-f651-4942-b668-1caf0e6cb6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>45fe1b98-0b36-4e1b-8c19-0b13fb7392a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptTablaSPR$ctl00$checkTodos</value>
      <webElementGuid>6f2523bf-5b61-4a16-a059-fc717496ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:TildarDestildarCheckBoxs(this.id);</value>
      <webElementGuid>f15ba449-bea7-4874-86b3-cb49e98dcfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptTablaSPR_ctl00_checkTodos&quot;)</value>
      <webElementGuid>9849cbd9-2225-4b3e-a229-94f12c6a0d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptTablaSPR_ctl00_checkTodos']</value>
      <webElementGuid>92ff9bbc-2e55-4f7a-85f6-2816f97a515b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr/td[5]/input</value>
      <webElementGuid>f6148781-161f-4f0d-8238-ca0ebf3af225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>167e9af0-8de5-4b05-8c72-dcd3c2d417dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rptTablaSPR_ctl00_checkTodos' and @type = 'checkbox' and @name = 'ctl00$CPH1$rptTablaSPR$ctl00$checkTodos']</value>
      <webElementGuid>0a758c1d-e335-46ef-9111-6ec94c211460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
