<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioSustentabilidad</name>
   <tag></tag>
   <elementGuidId>df29bc15-1961-4255-825f-d025817e9c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'OpcionesPreguntaEncabezado') and ../label[contains(text(),'${option}')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21a066e9-8d70-4469-ac93-3da46d781b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado_1</value>
      <webElementGuid>fd5fbcbb-2379-49e6-a101-d7aeed52c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6cd37da8-6bd6-4cc4-b49d-628434a08a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaEncabezado</value>
      <webElementGuid>7c0621ac-6675-4c2b-8afd-d5cb32938a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5e228033-f7ca-4956-82ff-a965f8fca9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaEncabezado$1\',\'\')', 0)</value>
      <webElementGuid>72913dfb-9d04-493c-8bd1-0bbf6ed45f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado_1&quot;)</value>
      <webElementGuid>e7413329-0cb4-4df2-964a-f99db417d8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado_1']</value>
      <webElementGuid>c5fb2797-a295-4ab0-bb30-6bde5ceafc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado']/tbody/tr[2]/td/input</value>
      <webElementGuid>b4da55e8-0de0-4db8-bd69-782716f1fac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>7e68ad5e-a76e-4481-99a3-99c20fdf3117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaEncabezado_1' and @type = 'radio' and @name = 'ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaEncabezado']</value>
      <webElementGuid>94ec91ab-b116-4938-b1a9-f093b250aa62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
