<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioLogisticaEmbalajeReciclado</name>
   <tag></tag>
   <elementGuidId>793ff8db-d5f0-4ebb-aff0-7b126d4e17d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'OpcionesPreguntaFormulario_1') and ..//label[text()='${option}']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb767910-436b-4d5e-9ccd-c0fcd3f8cc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1_0</value>
      <webElementGuid>98d42ce1-36fe-4ab2-a533-d7fa873fb6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>25d65797-6682-4991-9e9a-85672c1f3689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaFormulario_1</value>
      <webElementGuid>2a026c22-d0c5-4072-a06b-9d07b9d4fdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6bc2b4b7-3866-4faf-9d92-723761d98cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1_0&quot;)</value>
      <webElementGuid>0a266816-6d27-4fde-9b42-19346312b1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1_0']</value>
      <webElementGuid>04fb4fdc-4d51-465f-aa24-3a24052bd233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1']/tbody/tr/td/input</value>
      <webElementGuid>2a1f6a10-66bc-4b44-9822-ac8c3f86cbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td/input</value>
      <webElementGuid>55ab11c5-a435-4b10-82cc-f08fd4207c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_1_0' and @type = 'radio' and @name = 'ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaFormulario_1']</value>
      <webElementGuid>b9246b7b-a00b-4861-9a96-eaba8f8c58c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
