<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_IncluyeLogistica</name>
   <tag></tag>
   <elementGuidId>b480ff17-89cf-4721-bce3-30f45a1a1a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'OpcionesPreguntaFormulario_0') and ..//label[text()='${option}']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae70cbf1-c1c2-4f09-9063-e61de8f2a949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0_0</value>
      <webElementGuid>36d8176f-7efa-4bc0-9219-e074bfa8d641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4e421287-589f-4714-9908-c6124adfa39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaFormulario_0</value>
      <webElementGuid>2f9b5bd6-54b6-484d-907b-293a061c9120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>cd7e97b2-f997-4d2d-8035-7cfa4114a41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0_0&quot;)</value>
      <webElementGuid>464d823f-0433-4af2-ba6a-2ce82e9f79c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0_0']</value>
      <webElementGuid>0775b11a-a000-4481-971a-75c692d16212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0']/tbody/tr/td/input</value>
      <webElementGuid>f5872f02-7631-48bf-ae9e-4d508dd4ad1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>2aa961b8-b597-48fa-84a9-bb425a7608bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_ucFormularioSustentabilidad_rblOpcionesPreguntaFormulario_0_0' and @type = 'radio' and @name = 'ctl00$CPH1$ucFormularioSustentabilidad$rblOpcionesPreguntaFormulario_0']</value>
      <webElementGuid>c6432b9e-222a-4e80-b0cf-377cd22fbe7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
