<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AgregarSeleccionado</name>
   <tag></tag>
   <elementGuidId>bb8f46a0-a587-4867-ba8e-9293b36b7dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_imgAgregarSeleccionado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_imgAgregarSeleccionado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56b5498c-0221-466c-9c74-d18ad3470642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>9e9e51b9-b7e0-4751-a18b-c09e1e6887c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$imgAgregarSeleccionado</value>
      <webElementGuid>855ea1a0-9195-4f9d-8e7f-b61dc26454e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_imgAgregarSeleccionado</value>
      <webElementGuid>ffbad232-3f89-45eb-8818-97dfcebb6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar Encuadre Legal</value>
      <webElementGuid>9605bd8a-bdde-4afc-bbf8-49e7ee39dbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/App_Themes/styles-viejo/imagenes/iconos/ico_ok.gif</value>
      <webElementGuid>99cfa956-00bb-4252-a23d-10bb1a0ad3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agregar Encuadre Legal</value>
      <webElementGuid>3b58fca0-5680-4695-96ed-31c9d0610163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_imgAgregarSeleccionado&quot;)</value>
      <webElementGuid>d5d1e1db-dcc9-486f-af08-24f66a1b17be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_imgAgregarSeleccionado']</value>
      <webElementGuid>bb832836-2333-4f7c-9751-23b9e8bdb06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[5]/table/tbody/tr[7]/td[2]/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>da2d070a-1681-40cb-b89a-f323ef6cfcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>2b8e277c-993e-40eb-ad3e-0adf338fb63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$CPH1$imgAgregarSeleccionado' and @id = 'ctl00_CPH1_imgAgregarSeleccionado' and @title = 'Agregar Encuadre Legal' and @src = '/App_Themes/styles-viejo/imagenes/iconos/ico_ok.gif' and @alt = 'Agregar Encuadre Legal']</value>
      <webElementGuid>ad82b53a-84c4-413e-9b51-156f29161a9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
