<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IncisoAutPliego</name>
   <tag></tag>
   <elementGuidId>e78e75ce-7dd2-4d3d-bd36-0830d5909716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UC_IncisoCD_chkAutPliego</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UC_IncisoCD_chkAutPliego']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be44450-784b-4539-8816-7663f7484438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UC_IncisoCD_chkAutPliego</value>
      <webElementGuid>c86f3161-db14-41d4-9821-371732e1d1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>47d02aec-73e8-4139-ac19-7cca95e62e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UC_IncisoCD$chkAutPliego</value>
      <webElementGuid>7f059910-4b84-46ec-8161-cc81dd84c9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>c839f683-033f-4a29-837a-0351eafd575b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_IncisoCD_chkAutPliego&quot;)</value>
      <webElementGuid>4ac8af54-c809-4ddb-88b0-d3d59cf537b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UC_IncisoCD_chkAutPliego']</value>
      <webElementGuid>6fdb7733-830f-4699-b38a-9d99b52cc1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_UC_IncisoCD_flAutorizacionPliego']/span/input</value>
      <webElementGuid>60199423-2bf1-4285-8f59-39db9fa64ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>4329e3a5-50fc-4a7d-ba89-35f5b9c9ad3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UC_IncisoCD_chkAutPliego' and @type = 'checkbox' and @name = 'ctl00$CPH1$UC_IncisoCD$chkAutPliego' and @checked = 'checked']</value>
      <webElementGuid>8d6a8ccd-aabd-492b-9b62-bfc69ae11867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
