<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ContratacionDirecta</name>
   <tag></tag>
   <elementGuidId>e2305d56-db0e-4171-ba61-d8798d2e208f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblLicitConcursoCont_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rblLicitConcursoCont_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f349866c-7c77-48f5-bc73-9afb8076c074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rblLicitConcursoCont_5</value>
      <webElementGuid>ad46108a-29ac-4386-afa8-87d13ff6aa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8258a4c2-f0f6-474c-a586-bf64fe265fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rblLicitConcursoCont</value>
      <webElementGuid>fdc1bd2a-a991-4ccf-b282-4878266f8651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Contratación Directa</value>
      <webElementGuid>56b7cf1d-5ef7-45c6-9515-2bc08e9d51c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$rblLicitConcursoCont$5\',\'\')', 0)</value>
      <webElementGuid>402fd08b-24cb-415f-ba15-41506d955dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rblLicitConcursoCont_5&quot;)</value>
      <webElementGuid>8ae71425-1698-4463-9c02-1c055a1f6fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblLicitConcursoCont_5']</value>
      <webElementGuid>fed3e78a-bd25-4785-8b91-9d33ea4506e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblLicitConcursoCont']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>750094c6-e897-4ad7-ae3d-d12274e1ac7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>1f3f69df-1737-424e-a299-1b91222da8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblLicitConcursoCont_5' and @type = 'radio' and @name = 'ctl00$CPH1$rblLicitConcursoCont']</value>
      <webElementGuid>d8153c26-0b6f-46c6-8719-87325fcc71f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
