<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Guardar y Volver</name>
   <tag></tag>
   <elementGuidId>b56ad0fd-6ee9-41e6-8e56-7eae17234492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkGuardarYVolver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_lnkGuardarYVolver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4b33db3-c39c-481f-b7af-67fdfcd905a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>JavaScript:ValidarPagina(2,false);return false;</value>
      <webElementGuid>f781e234-157a-462d-ae8c-dbccbb0855a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkGuardarYVolver</value>
      <webElementGuid>e371de6a-2b80-4c85-a79b-f6bb126d1cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_verde_g_238</value>
      <webElementGuid>0fc769a2-b9e2-4c83-9cfe-88016af7832c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>23210851-603e-46e8-8267-0d79114bf2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkGuardarYVolver&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>0d4cd371-bb04-4d75-b250-045fa200eb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar y Volver</value>
      <webElementGuid>6ecbaeae-68d5-442d-a0ae-129d24673d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkGuardarYVolver&quot;)</value>
      <webElementGuid>cc34a17b-d5ae-4fb4-a83e-7ae08609e66c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkGuardarYVolver']</value>
      <webElementGuid>d024a20f-98d5-4456-894c-3e7f791c480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[18]/a</value>
      <webElementGuid>d3aab294-68a6-45a4-8c3d-ba2b1362ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Guardar y Volver')]</value>
      <webElementGuid>588b9772-9844-4314-b2a2-acd6abfcaa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar nuevo medio de difusión'])[1]/following::a[1]</value>
      <webElementGuid>c24846f3-4405-4fd6-b6c1-da14ad2503cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publicación en los medios de difusión'])[1]/following::a[2]</value>
      <webElementGuid>673d1666-bf89-445f-84cb-b8310e545a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/preceding::a[1]</value>
      <webElementGuid>0c6c0f58-c6cc-4d2c-bf98-7a75c5915e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::a[2]</value>
      <webElementGuid>8b30ed29-61e5-4e4b-be0b-7ca5a868b525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar y Volver']/parent::*</value>
      <webElementGuid>9da37a67-2a30-4496-8a88-439d28eac5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkGuardarYVolver&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>0c13591f-efe4-4365-b96a-d1e731abc6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/a</value>
      <webElementGuid>166ee61c-f082-48ec-abf7-842465b1d9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkGuardarYVolver' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkGuardarYVolver&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Guardar y Volver' or . = 'Guardar y Volver')]</value>
      <webElementGuid>7d3e49a7-05eb-4cea-9ca2-15be77621766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
