<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Enviar al Supervisor</name>
   <tag></tag>
   <elementGuidId>554bbc57-0094-4e93-94ec-e9e694c66f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkEnviarSupervisor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Enviar al Supervisor')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9229d369-ef8c-4ab0-9efa-3fa3de6f1111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pantallaEnEspera();</value>
      <webElementGuid>766a4826-0edf-4e2b-9854-3a2f2afe8fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkEnviarSupervisor</value>
      <webElementGuid>2eae6dcb-644a-45e2-8cf7-0f855400f40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_verde_m_238</value>
      <webElementGuid>c1e92e12-e31a-4de2-9065-f55da1fa2aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>9729f1b7-53c2-4652-ae98-4a8861d1c97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$lnkEnviarSupervisor','')</value>
      <webElementGuid>e4e2d5d7-c444-4714-90ae-d2f7bf3423d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar al Supervisor</value>
      <webElementGuid>f94a21d7-bda8-4e19-939a-0ff7f12e9052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkEnviarSupervisor&quot;)</value>
      <webElementGuid>89503af4-807b-43f4-9bd4-107d2dff2ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkEnviarSupervisor']</value>
      <webElementGuid>348fc429-fb65-4e03-bafc-7433de638227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[9]/a</value>
      <webElementGuid>6a082782-ca00-4cad-805c-2199c0b18e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enviar al Supervisor')]</value>
      <webElementGuid>a82325b4-c9fd-4c5a-ab95-98668e25e0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[17]/following::a[1]</value>
      <webElementGuid>8d1d92c5-903d-4ef3-ad93-cd6676e0397b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar datos'])[14]/following::a[1]</value>
      <webElementGuid>96e20e2b-a38b-47b5-93c5-8dd95fccd202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vista Previa Pliego'])[1]/preceding::a[1]</value>
      <webElementGuid>6148d50c-1ede-4bcf-bfae-1dc85bfc91ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::a[2]</value>
      <webElementGuid>6ce0f4a2-c2a8-4214-8318-020887ea7462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enviar al Supervisor']/parent::*</value>
      <webElementGuid>a8e41b3e-12ee-4e59-aba1-c12144782b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$lnkEnviarSupervisor','')&quot;)]</value>
      <webElementGuid>a58d4993-d6a2-4316-890b-45c8d61bb403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>b84e7c79-465f-4a74-9724-2343badbda9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkEnviarSupervisor' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$lnkEnviarSupervisor&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Enviar al Supervisor' or . = 'Enviar al Supervisor')]</value>
      <webElementGuid>1df248ae-ce0a-4a6a-9160-77a8b13f56fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
