<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpFechaActoApertura</name>
   <tag></tag>
   <elementGuidId>d9b5685e-3dc5-407f-b909-018f45ed9a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_dxedteActoApertura_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_dxedteActoApertura_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>837d5a13-154b-463a-b17e-a478dcaf390f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>c8d1a820-9d15-44ce-b4d9-fbd90cd7eae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_dxedteActoApertura_I</value>
      <webElementGuid>0c94adf2-047e-4493-9ff5-f3ab4da92d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$dxedteActoApertura</value>
      <webElementGuid>31d547f7-285f-47fd-a05e-f67f4a0634b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_dxedteActoApertura')</value>
      <webElementGuid>744c2e82-8ec2-4bbb-8322-9cbd16761dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_dxedteActoApertura')</value>
      <webElementGuid>ae048fbc-6c2e-4fe9-acf6-fe8e5c5060e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_dxedteActoApertura')</value>
      <webElementGuid>e12967c3-fc10-4c60-ab18-e8dc88b6fe3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_dxedteActoApertura', event)</value>
      <webElementGuid>26265417-cda6-41c1-ae54-cfae1c117847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c69c99d8-eb60-4d8a-94f2-dba0d209eebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>295a1b8b-dcac-4519-8896-4bd83110f20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62e61131-210b-4fd8-9412-e555507df0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_dxedteActoApertura_I&quot;)</value>
      <webElementGuid>4b934989-1c29-4034-9b22-969a70989d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_dxedteActoApertura_I']</value>
      <webElementGuid>d8046d11-89e5-4be3-a2f3-6642daabe83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_dxedteActoApertura']/tbody/tr/td/input</value>
      <webElementGuid>662aab21-6f14-4f97-84ba-ec624a64fcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7ab44f5b-3bb9-4955-b478-e31176f15eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_dxedteActoApertura_I' and @name = 'ctl00$CPH1$dxedteActoApertura' and @type = 'text']</value>
      <webElementGuid>f96a4540-d2f0-4d39-b173-c70da87f1fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
