<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpFechaFinalSoporte</name>
   <tag></tag>
   <elementGuidId>829e28ea-2e21-463a-86a5-ecd534c581b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_dxedteFinalSoporte_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_dxedteFinalSoporte_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f988b5bb-baed-4b2e-a639-3773b2dd7563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea dxeFocused dxh0</value>
      <webElementGuid>5af42675-040f-4402-895d-0a41fc25b91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_dxedteFinalSoporte_I</value>
      <webElementGuid>47385493-672b-4d56-b9a9-2e0e868ae6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$dxedteFinalSoporte</value>
      <webElementGuid>dd0bdb18-d580-42d4-9552-c70f256bf4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_dxedteFinalSoporte')</value>
      <webElementGuid>1be2a31a-9aba-460f-a4c3-556b66c3b71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_dxedteFinalSoporte')</value>
      <webElementGuid>6d1fc658-e90f-46c0-841f-2b2b1c735ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_dxedteFinalSoporte')</value>
      <webElementGuid>86d492b1-aef3-4026-802f-7ce8cfdd3494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_dxedteFinalSoporte', event)</value>
      <webElementGuid>e6fc1cac-5400-46e2-937d-25cd9b1b29dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eef9786b-c6fc-4a2e-9032-a33a21a0fb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e91054a8-51f6-4f53-80e8-ebc26954f166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78eb2d2f-c7b2-4a1a-8872-3526164b6630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_dxedteFinalSoporte_I&quot;)</value>
      <webElementGuid>8660ee3a-88ac-4338-afa2-75a964eadaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_dxedteFinalSoporte_I']</value>
      <webElementGuid>a906e093-a812-4c62-b802-3600ac7d56b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_dxedteFinalSoporte']/tbody/tr/td/input</value>
      <webElementGuid>920150c1-db83-4b15-bb4a-9324eb8f4aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ca40972c-a8a2-4e0a-be3b-61422b676b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_dxedteFinalSoporte_I' and @name = 'ctl00$CPH1$dxedteFinalSoporte' and @type = 'text']</value>
      <webElementGuid>342957ae-c7bd-4a77-8623-08cd0e81dcee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
