<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpFechaInicioConsultas</name>
   <tag></tag>
   <elementGuidId>9beca58c-0958-4c88-a560-7901f5ee1f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_dxedteInicioConsultas_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_dxedteInicioConsultas_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb4f1967-342a-45e8-8332-10612bd2cbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea </value>
      <webElementGuid>e6afdf4f-23ba-4b72-a5c6-40a42997ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_dxedteInicioConsultas_I</value>
      <webElementGuid>dd4d8ed4-8e44-42eb-bf71-ecfefb384ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$dxedteInicioConsultas</value>
      <webElementGuid>0a54c3f0-1547-468e-8af2-cedf3ad63934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_dxedteInicioConsultas')</value>
      <webElementGuid>43be5101-ef04-4e26-a53a-0a018b67c5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_dxedteInicioConsultas')</value>
      <webElementGuid>b5b7906c-04b4-40cf-998e-52658047ff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_dxedteInicioConsultas')</value>
      <webElementGuid>e449d265-b576-4fa7-bd3e-f98aad9bb52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_dxedteInicioConsultas', event)</value>
      <webElementGuid>926cef38-2fc1-4f90-9ac3-a977c3f89889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72e8a516-4b86-4dac-adc0-9ef9097b2024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1951027f-2414-4535-a673-7bb486adebdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c4b7cc9a-3c7d-4a15-97cb-2f0ab579aa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_dxedteInicioConsultas_I&quot;)</value>
      <webElementGuid>dc54160c-4396-4ca0-9169-92a54cec08da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_dxedteInicioConsultas_I']</value>
      <webElementGuid>08fad96c-99da-4d9f-bd74-cddc58a5c302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_dxedteInicioConsultas']/tbody/tr/td/input</value>
      <webElementGuid>8c832be6-378c-4451-b15b-58b7db053535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>6185caa7-d094-4943-a002-2b74047d451c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_dxedteInicioConsultas_I' and @name = 'ctl00$CPH1$dxedteInicioConsultas' and @type = 'text']</value>
      <webElementGuid>4339b518-38b5-4e68-b2a8-dab166e1c9ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
