<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpHoraFinalSoporte</name>
   <tag></tag>
   <elementGuidId>1e129b20-7961-4835-81e5-571b8e114cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01f552a4-5d69-48ae-a200-1f726f19a4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tmHoraFinalSoporte$txtHoraMinuto</value>
      <webElementGuid>23071465-9172-4fd9-8966-5c3c4229c32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d519264c-dec6-4b3a-a9bf-453f32a5ae38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto</value>
      <webElementGuid>127edf52-a3c4-4dde-8574-835d46ce5f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas timeControl hasTimeEntry</value>
      <webElementGuid>4c9fa369-388a-4221-8ce1-66b541562f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4836c209-7dc4-4f70-b2d0-4e234d46ddee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return OnChange();</value>
      <webElementGuid>8dfd9bba-1f5f-4897-a96a-2a90daa2632b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>cf3db966-d0ab-403e-a7a7-65a34aa66990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto&quot;)</value>
      <webElementGuid>68001fff-58a4-4e26-91f8-45bfa6aef7ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto']</value>
      <webElementGuid>7ba95092-69dd-4d9d-8ff4-42b78757e194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[13]/table/tbody/tr[2]/td[3]/span[2]/input</value>
      <webElementGuid>5ebac9f5-41fd-417b-b28e-fdbca1b906f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[2]/td[3]/span[2]/input</value>
      <webElementGuid>4f372d12-1081-4233-b808-37d1af7823e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$tmHoraFinalSoporte$txtHoraMinuto' and @type = 'text' and @id = 'ctl00_CPH1_tmHoraFinalSoporte_txtHoraMinuto']</value>
      <webElementGuid>7f2c98af-e897-4df9-a0b0-a30def90be6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
