<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpHoraFinalConsultas</name>
   <tag></tag>
   <elementGuidId>aa7a4577-6119-4b56-be7d-b2a5a58b8cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87e5c2e2-2825-4a89-b6e0-9010f4fa5338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tmHoraFinalConsultas$txtHoraMinuto</value>
      <webElementGuid>6f8d9b94-b489-4bbe-9bc1-eec091be6d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5887189-d67a-4f46-98ca-d5aefe439441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto</value>
      <webElementGuid>2691e8ad-26d7-473f-91a5-6254ad346e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas timeControl hasTimeEntry</value>
      <webElementGuid>48e40ad8-e46d-4677-b0db-27b39896f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>427c830e-43b5-4069-8305-3f05263d1be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return OnChange();</value>
      <webElementGuid>d100059e-33f0-4162-a356-43401227df4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>0e2e18ab-08e4-4982-8725-223e66bff8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto&quot;)</value>
      <webElementGuid>3d329569-1a70-4565-9b9d-f84cdd539d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto']</value>
      <webElementGuid>9e23d83d-3512-4500-9976-6119c166e3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[7]/table/tbody/tr[3]/td[3]/span[2]/input</value>
      <webElementGuid>92b44bd4-ca08-44da-b7f5-29ef277ed434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/span[2]/input</value>
      <webElementGuid>c397f4b0-9f5a-4531-840c-569908cba8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$tmHoraFinalConsultas$txtHoraMinuto' and @type = 'text' and @id = 'ctl00_CPH1_tmHoraFinalConsultas_txtHoraMinuto']</value>
      <webElementGuid>0512daf9-3ac3-4e49-950d-c78fc2e6d613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
