<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpHoraInicioConsultas</name>
   <tag></tag>
   <elementGuidId>988cc500-4fb8-440c-a696-a11487208344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4184aff-31cf-420c-8a6e-aaff33a06cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tmHoraInicioConsultas$txtHoraMinuto</value>
      <webElementGuid>35622d2d-9d26-4230-ad64-b768491fdb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b305ec0-8c63-40be-aac1-830599f27961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto</value>
      <webElementGuid>9b6cee52-7b23-4009-ba73-483bfbe6f408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas timeControl hasTimeEntry</value>
      <webElementGuid>db4b455d-a369-4862-8fe7-34913e2cb108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc663775-4d22-4e56-a79e-a7aa2350fed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return OnChange();</value>
      <webElementGuid>d0d755f6-472a-4c3a-8bde-b4c1168e4a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>f2571de3-5188-4eb3-b960-9630a385595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto&quot;)</value>
      <webElementGuid>b2a5e94d-e5f4-40c8-b0b5-0e07692c89e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto']</value>
      <webElementGuid>4b2bd549-0bda-4e68-bd2b-ebed871a7e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[7]/table/tbody/tr[2]/td[3]/span[2]/input</value>
      <webElementGuid>c9c1ac81-7e86-4279-a506-08bc24ad879e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/span[2]/input</value>
      <webElementGuid>b57b3402-7eae-4976-8daf-f24eb395063c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$tmHoraInicioConsultas$txtHoraMinuto' and @type = 'text' and @id = 'ctl00_CPH1_tmHoraInicioConsultas_txtHoraMinuto']</value>
      <webElementGuid>3f1939cf-d9a4-4eac-8e96-0774f0eb5a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
