<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Anio</name>
   <tag></tag>
   <elementGuidId>539b3151-e45b-4147-8cc8-647fa654cc0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[contains(@id,'DropDownAnio')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22f26e2f-a3f3-4026-90db-45d98b81b2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$DropDownAnio</value>
      <webElementGuid>db154085-ff3f-467b-8e64-36b334b1f252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      <webElementGuid>0ae21f74-1a41-4fb7-ab91-265a2d9403d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>73a78316-2375-451b-ac4e-ec2ee590722b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	</value>
      <webElementGuid>dd2a0bbe-3cca-469c-ba49-2c6c681781b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_DropDownAnio&quot;)</value>
      <webElementGuid>626ef819-64f8-4388-bc90-a382ab390c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_ucIngresarActo_DropDownAnio']</value>
      <webElementGuid>c1e30da5-aaa4-4fe2-bc2e-a89c8d4b5203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaAnioDocumento']/select</value>
      <webElementGuid>3891f7d2-7730-4ef3-8b57-c8d860588426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[1]</value>
      <webElementGuid>beea6350-1bb3-4e71-9bf4-fa20b9849cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>70c28254-49dd-4332-a294-3694612eb875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifique que el año haya sido ingresado.'])[1]/preceding::select[1]</value>
      <webElementGuid>6f3143bf-4dad-4e79-bf8e-24e40283c576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>18347c2f-9607-42cd-81a4-eaf68152bafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6da30790-7aad-4de5-a2b6-255d832685d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$ucIngresarActo$DropDownAnio' and @id = 'ctl00_CPH1_ucIngresarActo_DropDownAnio' and (text() = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	' or . = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	')]</value>
      <webElementGuid>76260148-c5af-4958-bab5-9e5199c8c303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
