<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellido  Nombre  Razon Social_fullName</name>
   <tag></tag>
   <elementGuidId>70a57f13-a176-4f43-b675-a300373cb2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fullName' and @name = 'fullName' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>046df94f-84d9-4e1b-a6fa-8ae3508a1ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d005c9b-1350-4d07-86ff-b2c9b1f4ca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>1380e4f3-ac7c-4195-8cce-09c782abcb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>d0b80a46-28bc-46f1-9edf-df85fec7e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8ea713f-4e1f-4c0a-b29c-c8febaccc690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>bdaada9c-8315-4618-8860-4316ab190d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>REGRESION4082</value>
      <webElementGuid>3600a3a4-2b96-4dff-80c7-419d31a73bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullName&quot;)</value>
      <webElementGuid>fdfff3fc-ad96-412c-9b83-1f09c67d96f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullName']</value>
      <webElementGuid>3b40b169-70ef-4c11-8126-4cc2e5e1c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>9e5ec068-e076-43ed-ae2a-2b5b6cd05dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>56543223-868f-45f2-8802-e256156f0d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fullName' and @name = 'fullName' and @type = 'text']</value>
      <webElementGuid>9148816d-5ccb-43f3-9b3f-2995c67dd13e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
