<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N Telfono_nTelefono</name>
   <tag></tag>
   <elementGuidId>868f0211-535e-4ad9-831f-65ce97a16941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nTelefono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nTelefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b0eebdf-a0c3-49a0-a790-ddf9b3bad0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>511a96dd-78f7-43c8-a9e5-19580b9e9c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>db338041-9d68-49a0-ac6a-499324d2f2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>b61c4977-1320-4aca-89e4-27e10ec565b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nTelefono</value>
      <webElementGuid>c2b57d36-3b86-41bc-b702-1cbbbfb1d84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60591b3f-0299-432c-b40b-23a4b275a71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>4d2879bf-2f22-419a-8508-fe5693e83e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>fca861ef-35d3-4b70-b3ef-b74fb01adc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nTelefono&quot;)</value>
      <webElementGuid>3110d2c1-ff01-4dbf-92ef-985510e5456c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nTelefono']</value>
      <webElementGuid>a856685b-e115-42ab-9190-f5a7f340e4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/form/div/div[7]/div/div/input</value>
      <webElementGuid>6e9df8cc-ad60-4957-83c9-733cbb70fe18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>933dfd7a-5bca-4060-8aa3-243370c4bf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nTelefono' and @name = 'nTelefono' and @type = 'text']</value>
      <webElementGuid>7c0caa75-22c1-4b08-9459-269f53fb686f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
