<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_msjOperacionModificadoExitosamente</name>
   <tag></tag>
   <elementGuidId>c00638b6-a41e-4e6c-b0d9-51a58fa596ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='transition-modal-description']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'transition-modal-description' and (text() = 'El usuario ha sido modificado exitosamente.' or . = 'El usuario ha sido modificado exitosamente.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0653f014-c1b9-4bd0-8e60-d77780ca0b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1</value>
      <webElementGuid>a1893a48-d548-45af-8782-5c59a463b69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-description</value>
      <webElementGuid>2620c327-e9fb-4c0c-b269-53639cc7a781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sx</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3b826a43-e4f8-4d68-acd2-c9633d8572ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El usuario ha sido modificado exitosamente.</value>
      <webElementGuid>f220850a-dd0f-428e-b1dc-91ad75f65e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-description&quot;)</value>
      <webElementGuid>32e52447-0f14-4d55-b39e-a9fb4947d99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='transition-modal-description']</value>
      <webElementGuid>8d2fb7e9-ac38-4632-a88c-a6cd15eb6771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación realizada exitosamente'])[1]/following::p[1]</value>
      <webElementGuid>3b23b4f9-cfaf-46b2-95e3-1fc89f507e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[3]/div[@class=', '&quot;', 'MuiBackdrop-root', '&quot;', ']')])[1]/following::p[1]</value>
      <webElementGuid>fac247b9-6aff-42c3-be0e-1679e3971825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El usuario ha sido modificado exitosamente.']/parent::*</value>
      <webElementGuid>5f6b7944-cb7d-4fe2-b022-e2cfa767aa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>437b68b6-1f40-4d93-8136-42232bf5d61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'transition-modal-description' and (text() = 'El usuario ha sido modificado exitosamente.' or . = 'El usuario ha sido modificado exitosamente.')]</value>
      <webElementGuid>f0a07394-2765-49d3-ba21-d9df0bbd5f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
