<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PopUpIngresarEntrega</name>
   <tag></tag>
   <elementGuidId>d7506dd5-4281-4c14-a790-869233bfa260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_PopUpIngresarEntrega_CIF-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_CPH1_PopUpIngresarEntrega_CIF-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2731be3f-6c62-4022-9493-a0eaa228997f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_PopUpIngresarEntrega_CIF-1</value>
      <webElementGuid>4300fffc-dadf-43f1-87d8-fb8e3692862a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/SGA/IngresarDetalleEntrega.aspx</value>
      <webElementGuid>3f6b399b-926a-4f91-9165-6dca5f60b8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>de31577f-60b0-45dd-a124-80825f764cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3da5e696-765c-4bf2-bded-ab6652a9a328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_PopUpIngresarEntrega_CIF-1&quot;)</value>
      <webElementGuid>413cf6d8-19d1-4b3f-9554-f387a06ff58e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ctl00_CPH1_PopUpIngresarEntrega_CIF-1']</value>
      <webElementGuid>65e1daae-c4ad-480e-8385-d439b7f5a994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_PopUpIngresarEntrega_CIFD-1']/iframe</value>
      <webElementGuid>f466f6c1-2c8a-4893-9c39-bf47a8dd449f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/following::iframe[1]</value>
      <webElementGuid>68513895-9608-4efd-ad1d-186f92713ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/following::iframe[1]</value>
      <webElementGuid>a76942d6-d78f-4059-8330-5f8fab6594c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::iframe[1]</value>
      <webElementGuid>f74941e9-87e6-4d96-907a-3bf821f25a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::iframe[1]</value>
      <webElementGuid>eba3330f-7909-4fde-bcee-4be974edaf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4603dfde-4ce5-46dd-af17-16ba2aec53ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ctl00_CPH1_PopUpIngresarEntrega_CIF-1' and @src = '/SGA/IngresarDetalleEntrega.aspx']</value>
      <webElementGuid>b7890579-6dc8-4a0d-8139-9c227d0ff596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
