<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_AdjRenglon</name>
   <tag></tag>
   <elementGuidId>947b1507-8994-4477-94a5-cc77370b91b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@id,'TipoCotizRenglonAdjudicacion')]//label[contains(text(),'${tipo}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rblTipoCotizRenglonAdjudicacion_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7daa5917-89b4-45ac-9358-8b03e363c788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rblTipoCotizRenglonAdjudicacion_1</value>
      <webElementGuid>8d9191bf-96b3-4586-913d-088d82e95e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2c7d1bad-2381-4340-b770-f049e319bb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rblTipoCotizRenglonAdjudicacion</value>
      <webElementGuid>c7fbaa76-5bbd-4aab-85ab-3f47cccf423c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b6839aa9-7757-41ff-b19d-22c04d1eb224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rblTipoCotizRenglonAdjudicacion_1&quot;)</value>
      <webElementGuid>bea36e74-1858-49f9-b97f-5b97b432e049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rblTipoCotizRenglonAdjudicacion_1']</value>
      <webElementGuid>0e4db3ed-5071-4e15-b8c1-1fbee9c4f20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_rblTipoCotizRenglonAdjudicacion']/tbody/tr[2]/td/input</value>
      <webElementGuid>896de689-e157-464e-a184-f1dfe493420e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td/input</value>
      <webElementGuid>daa6d71d-150a-45a1-8abe-5c276ef71cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rblTipoCotizRenglonAdjudicacion_1' and @type = 'radio' and @name = 'ctl00$CPH1$rblTipoCotizRenglonAdjudicacion']</value>
      <webElementGuid>c22853b2-5667-4b0a-a414-cef9ad260bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
