<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaTelefonoUOA</name>
   <tag></tag>
   <elementGuidId>b444efd0-a924-42ad-b1fe-e05a40367eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtTelefonoContactoUOA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtTelefonoContactoUOA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8a605551-8c16-40cc-beac-713092b3b33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtTelefonoContactoUOA</value>
      <webElementGuid>2cdd28dc-3291-4f48-9e3f-357886f4fbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7b442494-941b-45cc-b0ce-1f7165d2a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e320d090-7d62-4a00-a6f5-ab3230ed493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtTelefonoContactoUOA</value>
      <webElementGuid>3f399915-ba58-4611-b8da-f464014f9320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>cortaLargoMaximo('ctl00_CPH1_txtTelefonoContactoUOA',255)</value>
      <webElementGuid>11253a03-6827-42a6-b053-d403617a2cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtTelefonoContactoUOA&quot;)</value>
      <webElementGuid>c98204e7-47a5-4223-a241-6800de728756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtTelefonoContactoUOA']</value>
      <webElementGuid>36af5cbe-c9b4-499e-8109-788040f612f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upInformacionBasica']/div[3]/table/tbody/tr[16]/td[2]/textarea</value>
      <webElementGuid>376babe5-1c18-4517-9311-66a46ecf588a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/textarea</value>
      <webElementGuid>4a58a08b-d50b-46c5-9cde-848187d2753b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtTelefonoContactoUOA' and @id = 'ctl00_CPH1_txtTelefonoContactoUOA']</value>
      <webElementGuid>8d9d2090-b912-4d15-8c66-ef1ceebfcd87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
