<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtObservaciones</name>
   <tag></tag>
   <elementGuidId>9c087393-84b2-4585-b868-7273707b2629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@id,'Observaciones')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4077a203-cc5b-49cb-b3bd-1906dced032e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtObservaciones</value>
      <webElementGuid>6182fe24-ca55-4f8e-8934-e28de7e8bc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtObservaciones</value>
      <webElementGuid>9cac68ff-5f6c-4962-a2a5-601cda518e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>07e26c86-d3f8-485c-9d5f-9a9414457da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>18a858f5-c8f3-4666-ad37-19d620658816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d8ff5ff-bff2-45cc-b0f5-e9f01ef993ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtObservaciones&quot;)</value>
      <webElementGuid>b27210ef-5748-4d32-a9fa-b722ef27e44e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtObservaciones']</value>
      <webElementGuid>95f96223-ff29-47ed-93f9-93b86ef37e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DivObservaciones']/textarea</value>
      <webElementGuid>36e018a2-bc36-44a3-8b88-bfd8ea25a07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/textarea</value>
      <webElementGuid>45404a06-76e9-48a1-ba82-2b6f1c3b1bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtObservaciones' and @id = 'ctl00_CPH1_txtObservaciones']</value>
      <webElementGuid>5ae76706-ec0a-42d7-9de4-e8afd0600df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
