<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbOtraInformacionRechazado</name>
   <tag></tag>
   <elementGuidId>77e55085-163a-4e6c-b8d9-fa2aa564d2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c80474ba-133f-4f2b-9dad-dad5cb32b983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>9355a0dd-ec00-483c-9569-4ba2b7028182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>53195d30-34cf-4841-9cd4-2bdaf8cabf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>15c6731a-b551-4b1c-876a-0dac000432f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>0a7d78bd-7ad6-49a0-ba7c-2a04025d3348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>179f244e-5d90-4886-9ebc-56c416b78947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>73baeaba-6acf-4a2c-9b49-b90e5a38c37a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>c0eb6876-2c95-42ee-9c89-c260a5c098c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[2]</value>
      <webElementGuid>3ed11b15-91c3-416d-9bf8-2f3f609641d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>959ed7a9-d20f-4d90-a4e4-844fc21c4f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>8f191cb3-41c0-4cf6-9595-21bc0e2ca32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
