<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbTamanoEmpresaAprobado</name>
   <tag></tag>
   <elementGuidId>43a769e5-7662-4624-af85-ba4a61deaa39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9b04748-479c-4a20-bc3c-038e53391b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado</value>
      <webElementGuid>aa3e56d1-0098-4d95-87c8-a5c5a2f254b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7a709eab-ecd7-4a89-b21b-14f38d90a8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCTamano_Empresa$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>36ca9861-0ec3-499a-a81f-bb83ea4f4772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtAprobado</value>
      <webElementGuid>08d93d0f-5c59-4021-ba0c-04cc75d3afd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$UCTamano_Empresa$EvaluacionProveedorTramite$rbtAprobado\',\'\')', 0)</value>
      <webElementGuid>ce2f2113-084e-4ecf-a2c2-2468ecfef846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado&quot;)</value>
      <webElementGuid>f1123c3d-62cf-4c9d-a951-0ac1220d8e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado']</value>
      <webElementGuid>8d6f2e2b-0c62-4c8f-b0d8-48afebe9580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input</value>
      <webElementGuid>74ca5f63-7dc5-4ad3-805b-d0b10cb9d3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>b7150c98-1d2e-4625-839f-1dea790b280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCTamano_Empresa_EvaluacionProveedorTramite_rbtAprobado' and @type = 'radio' and @name = 'ctl00$CPH1$UCTamano_Empresa$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>632ff1c6-4b7a-491e-817a-767146d4bcc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
