<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaOtraInformacionObservaciones</name>
   <tag></tag>
   <elementGuidId>dc29602b-b3c8-44a9-acb8-61b9013baa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ecb4bbb8-396e-4805-83ae-22e89c7c184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>51f20621-15a0-48e9-a656-d4a9a6442f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4cff198b-23d2-4586-919b-42d8fd70a620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ba04dc2b-cbad-4124-81b3-752021b5590a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>f0dca7ae-ace6-4d6d-94a3-ba851fdebcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>b2dd10fd-abb4-4029-9146-0f307f38ec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bab0b53-6aaa-4f8f-aee8-c0d0f821858c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>80f80b5c-6106-40a2-b99a-a9e4332bee77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>ea7dcfee-6fcb-46f3-83fd-985db591c59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[2]</value>
      <webElementGuid>544dcdd6-c4bf-4eb2-9457-1f19eddef682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>43538a0c-45b1-415f-af01-bd6e2f58e8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$UCOtra_Informacion$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_UCOtra_Informacion_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>2c44d5de-1add-42bb-9b1d-330a3a958047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
