<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cambiar</name>
   <tag></tag>
   <elementGuidId>642e1002-24f7-4059-9b10-138df39f72a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f800fca6-317e-472e-ab7a-d305cf9fc3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar</value>
      <webElementGuid>d1bfa4fa-e062-445b-a0f2-42f4763069fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>ddee6ade-77da-4bd7-90a2-3718496261b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$NavBar$CtrlUsuario$CtrlCambiarUnidadEjecutora$lnkConfirmar','')</value>
      <webElementGuid>3925ad9f-1926-4918-93c6-5522b09f70ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar</value>
      <webElementGuid>4534a128-cfb9-44f2-bd80-3c3971df1e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar&quot;)</value>
      <webElementGuid>de3b970e-d65d-4285-8e50-8d394794b232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar']</value>
      <webElementGuid>7e7da3af-3c06-454d-b7c0-1cea842a5704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_NavBar_CtrlUsuario_div2']/div[2]/div/a</value>
      <webElementGuid>09e30498-496b-489f-bafc-e5deaf473a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cambiar')]</value>
      <webElementGuid>f0c403d9-c3dc-41f2-8e29-e3aa66008164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unidad Ejecutora:'])[1]/following::a[1]</value>
      <webElementGuid>6739ce6d-4a55-42db-ae78-c6245d1de2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='efilippo'])[1]/preceding::a[1]</value>
      <webElementGuid>1b87090b-f9d9-4d72-b581-d98712ecad0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cambiar']/parent::*</value>
      <webElementGuid>b2498984-539b-4153-beba-ece9ea12bb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$NavBar$CtrlUsuario$CtrlCambiarUnidadEjecutora$lnkConfirmar','')&quot;)]</value>
      <webElementGuid>3c1c959b-0e38-4ef7-8ef0-0cba530e1068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>bced513f-4c08-406e-9237-449d44e3f269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_NavBar_CtrlUsuario_CtrlCambiarUnidadEjecutora_lnkConfirmar' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$NavBar$CtrlUsuario$CtrlCambiarUnidadEjecutora$lnkConfirmar&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Cambiar' or . = 'Cambiar')]</value>
      <webElementGuid>6eadcc89-c2c2-4bec-ba1c-95884e2c072b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
