<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCambiar Unidad Ejecutora</name>
   <tag></tag>
   <elementGuidId>c601028a-4ee1-4901-9109-eff20e83bcb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_NavBar_CtrlUsuario_liUE > p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ctl00_NavBar_CtrlUsuario_liUE']/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22658fa5-acec-4a22-86c6-6a61edd1225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#modalCambiarUnidad</value>
      <webElementGuid>ffb6d8ca-aa0c-4734-b0e0-66973324b764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>98f67795-6e14-4bd1-bf42-faba17436405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar Unidad Ejecutora</value>
      <webElementGuid>1420a43b-b50d-4dc1-b272-85f8f29220fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_NavBar_CtrlUsuario_liUE&quot;)/p[1]/a[1]</value>
      <webElementGuid>e7428fe6-7611-410c-9eff-90b43c2538ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ctl00_NavBar_CtrlUsuario_liUE']/p/a</value>
      <webElementGuid>39ca3193-2240-4a4a-91ac-19a9617c8541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cambiar Unidad Ejecutora')]</value>
      <webElementGuid>ec6ff5b8-80b8-42b8-86c5-092dff90fd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar clave'])[1]/following::a[1]</value>
      <webElementGuid>52bb3f1e-7bc3-4299-b83f-bd8c04143c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración'])[1]/following::a[2]</value>
      <webElementGuid>f4a01712-45f9-48a2-b30f-9cc889e16ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver perfiles'])[1]/preceding::a[1]</value>
      <webElementGuid>c25316d8-33d5-4cfb-8973-25cf0aa2843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/preceding::a[2]</value>
      <webElementGuid>99d7f220-4cee-490e-b868-6881ddf66ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#modalCambiarUnidad')]</value>
      <webElementGuid>b0520fde-e166-4c9c-8e10-94dfbe815dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/p/a</value>
      <webElementGuid>79c6ef90-dd7b-421a-aeee-72bd74132fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#modalCambiarUnidad' and (text() = 'Cambiar Unidad Ejecutora' or . = 'Cambiar Unidad Ejecutora')]</value>
      <webElementGuid>6e3eec93-3c38-4d1e-b060-0a255744639b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
