<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>4a636782-55f1-4c88-9010-f43dfeda39fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1b50295-abbb-4368-a2b4-5d944ca2d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CtrlMenuPortal$logIn$txtPassword$txtTextBox</value>
      <webElementGuid>b6c80468-5d85-457a-80e5-2ed988b89a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7324b339-f532-49ba-9e24-2f2dcb6fae42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox</value>
      <webElementGuid>374b3109-fe8d-4b6e-930d-ede908d15fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fd287c12-71d2-4307-9c60-4e12367a352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>fa4917b5-e490-4d70-90c4-02e39945520b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox&quot;)</value>
      <webElementGuid>ed6fef16-2cea-427c-ab99-ef15f82610db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox']</value>
      <webElementGuid>dcb29763-0688-4cf3-a90a-287a07759466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CtrlMenuPortal_logIn_pnlLogin']/div[2]/div/div/input</value>
      <webElementGuid>75cf1c9e-ac12-4085-848b-c9b5b5ef49a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>17dbdf9f-c610-4513-95bd-5b1dcd41f253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CtrlMenuPortal$logIn$txtPassword$txtTextBox' and @type = 'password' and @id = 'ctl00_CtrlMenuPortal_logIn_txtPassword_txtTextBox' and @placeholder = 'Contraseña']</value>
      <webElementGuid>70f16d32-a73c-45ac-9b4d-df55350f8d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
