<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repita contrasea_internal_repeatPassword3</name>
   <tag></tag>
   <elementGuidId>f371d184-1a93-4b8b-83a6-a8a9ab680d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'idInpRepeatPassword' and @type = 'password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#internal_repeatPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idInpRepeatPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>becee259-e726-4954-92be-eab0f2de573e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f20a1ea9-37d9-42ff-876b-4a40021f23fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd9b3b00-3c81-4afc-8d4a-fee5f8d1cc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idInpRepeatPassword</value>
      <webElementGuid>e5425220-76a0-43f5-810a-8f059dfe6e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>internal_repeatPassword</value>
      <webElementGuid>5020e6b0-dc73-4e21-8092-7af1f86b462e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7dfed7cc-f2f1-4314-8f47-55a505fea37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd</value>
      <webElementGuid>d05c8364-af7a-416a-bb1b-9ec32c135e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;internal_repeatPassword&quot;)</value>
      <webElementGuid>0ebb6d20-712a-45e1-8de2-a0ee291dc345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='internal_repeatPassword']</value>
      <webElementGuid>fbc96f49-7028-4c64-b6d5-0f2aa17aada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>5f023dd4-2ad8-4c95-89d8-e7bf4b1dd233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>df2f3be1-1b74-4b07-9517-612d8202553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'internal_repeatPassword' and @name = 'internal_repeatPassword' and @type = 'password']</value>
      <webElementGuid>bd1a833e-0fba-4c49-b5a8-a8c6bff69033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
