<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNombreTabla</name>
   <tag></tag>
   <elementGuidId>186acc13-6da1-469d-b031-5e0e4e3ebcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCCrearTabla1_tbNombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCCrearTabla1_tbNombre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6a68a60-1815-4d73-bc6b-7ec929a6c2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCCrearTabla1$tbNombre</value>
      <webElementGuid>10d44d01-3166-4415-961d-1ee1b747c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>316f86dc-1236-4571-a191-a8cb0063c316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>557efbe0-0435-45e5-b2f1-52a4db4b7aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCCrearTabla1_tbNombre</value>
      <webElementGuid>6838f6da-e11a-46b8-a0c2-37c6f5da357f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>124e946c-f850-4b87-b882-6f99d1b2fba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCCrearTabla1_tbNombre&quot;)</value>
      <webElementGuid>77895114-a287-4fc0-891c-60fc65a5fd32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCCrearTabla1_tbNombre']</value>
      <webElementGuid>415fcead-21be-4135-87d9-912e216fbe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_UCCrearTabla1_upModalTabla1']/div[2]/div[2]/div/input</value>
      <webElementGuid>c298f94b-ca29-4640-b40a-6dbdb93026f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>155cb2b3-7148-48a9-a1b4-e12fed99297a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$UCCrearTabla1$tbNombre' and @type = 'text' and @id = 'ctl00_CPH1_UCCrearTabla1_tbNombre']</value>
      <webElementGuid>dfcd5640-b870-42f8-adf8-d6784b3fb178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
