<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TipoDeConvenioMarco</name>
   <tag></tag>
   <elementGuidId>38e5010f-6c87-469b-b653-96507243f8f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_chkConvencional</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_chkConvencional']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7bffd4d-697a-4f15-a198-a2c9cf9cbfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_chkConvencional</value>
      <webElementGuid>6fc0ac9e-cecc-4a29-831a-d1ff73122071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>67e2baed-6a07-4c35-be65-02f45a279dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$chkConvencional</value>
      <webElementGuid>0b064d07-0e37-4628-beed-f7cd2a391e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$chkConvencional\',\'\')', 0)</value>
      <webElementGuid>ce67dafa-b35a-4677-a4e0-5664937c8287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_chkConvencional&quot;)</value>
      <webElementGuid>84bedbb3-e57b-44af-b90b-ede37ef19944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_chkConvencional']</value>
      <webElementGuid>295b853b-73db-479f-9b31-737575c47b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[5]/table/tbody/tr[8]/td[2]/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>f6cc0dc1-b98b-4fa7-a8fb-c2dbee7b4175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>7fb89648-aee1-473d-8d64-ebca6e4340ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_chkConvencional' and @type = 'checkbox' and @name = 'ctl00$CPH1$chkConvencional']</value>
      <webElementGuid>0c7b4c64-a263-4096-b0c1-06f2492c32dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
