<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CompletarDatos</name>
   <tag></tag>
   <elementGuidId>2dcdb167-140d-4532-937d-11b006315ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionIndice10_hlDatos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_seccionIndice10_hlDatos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d14d7f2-9f6c-4262-afd8-47a9509b0aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionIndice10_hlDatos</value>
      <webElementGuid>08911d54-a1aa-497d-8ea8-99c48589eaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>2b2730df-3cd4-4f83-915e-4b6f6de275bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>InformacionContrato.aspx?qs=hc9oU876wO12bsKzjBFr/w9XmRvIycLSsq/82NyQTecEzwAYykDgtI|ektcHXnOhoR0p6RwDhS2lHWkeiG9Ss32Fc9DgWQBNC5CJjz6pEnkcYlDO5|Df2g==</value>
      <webElementGuid>ea5dc160-bdfa-4c7d-a61b-1dcd0a42d914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar datos</value>
      <webElementGuid>5568ef68-b369-404d-bbd8-056569a536ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionIndice10_hlDatos&quot;)</value>
      <webElementGuid>a22838ff-29c9-4e8a-a2b8-3c75ad6d31b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_seccionIndice10_hlDatos']</value>
      <webElementGuid>3279028f-7d71-4b4e-b408-6ab7f024d3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr[10]/td[2]/span[2]/a</value>
      <webElementGuid>992cb0a5-c902-4038-ae54-fcf347744bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Completar datos')])[3]</value>
      <webElementGuid>231a4408-0424-4a0b-b656-913f091a8a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos obligatorios'])[5]/following::a[1]</value>
      <webElementGuid>2ccb127d-0546-41fb-8005-7845cdc76f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta completar índice Nº 2'])[2]/preceding::a[1]</value>
      <webElementGuid>ee1fe12b-db47-4bc6-acc4-d97e9c0f991c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[10]/preceding::a[1]</value>
      <webElementGuid>facac19a-af08-46e4-8255-db2b99713288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'InformacionContrato.aspx?qs=hc9oU876wO12bsKzjBFr/w9XmRvIycLSsq/82NyQTecEzwAYykDgtI|ektcHXnOhoR0p6RwDhS2lHWkeiG9Ss32Fc9DgWQBNC5CJjz6pEnkcYlDO5|Df2g==')]</value>
      <webElementGuid>8644e27c-493d-4bed-a252-c83b54233ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/span[2]/a</value>
      <webElementGuid>d467ee3a-3a61-446e-b029-3fc3da19486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_seccionIndice10_hlDatos' and @href = 'InformacionContrato.aspx?qs=hc9oU876wO12bsKzjBFr/w9XmRvIycLSsq/82NyQTecEzwAYykDgtI|ektcHXnOhoR0p6RwDhS2lHWkeiG9Ss32Fc9DgWQBNC5CJjz6pEnkcYlDO5|Df2g==' and (text() = 'Completar datos' or . = 'Completar datos')]</value>
      <webElementGuid>f0857925-c56f-4d24-b034-a5817ce45e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
