<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DiasDuracionContrato</name>
   <tag></tag>
   <elementGuidId>a4f21127-ce7f-49ad-b067-83236896d54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36438ebe-275f-4b53-9fd8-bb6ff02d3130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCDatosInformacionContrato$txtDiasDuracionContrato</value>
      <webElementGuid>372eddf2-8547-4ed8-9209-c4343f4823fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7fe53e3-984d-48d8-865e-3bddd4063f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>23bbb3dc-252b-4be0-bb39-f9fb5bdc3ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b12d0b5c-9c16-4b9b-b504-2d12fa029a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3509724e-8a2e-4dd8-a487-b72f9344888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato</value>
      <webElementGuid>17370f2a-2c71-40a9-8f47-e75be6c75675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas</value>
      <webElementGuid>9e84696b-3356-4b7d-9687-cee9b59c4d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>d92b9037-4727-41b0-9d8e-147c18af10fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validaSoloCaracterNumerico('ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato');</value>
      <webElementGuid>7ccd432c-3fdb-4b97-9c1d-5cbdd4c42d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>1532823b-9e0f-4b6d-8190-072ad0eff438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato&quot;)</value>
      <webElementGuid>fc47c0ca-855b-45d6-ae5b-55bb6ef48fa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato']</value>
      <webElementGuid>de90231b-84f0-49ca-8913-edc6a5e8d887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[17]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8f673926-76c4-4c8e-886b-a98136a33909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c0e4764c-ba32-45ac-8a84-fdfb546b5553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$UCDatosInformacionContrato$txtDiasDuracionContrato' and @type = 'text' and @id = 'ctl00_CPH1_UCDatosInformacionContrato_txtDiasDuracionContrato']</value>
      <webElementGuid>4c0aacd9-6be5-4a9d-8cd7-e6931f5ddfc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
