<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodicidadCadaIncremento</name>
   <tag></tag>
   <elementGuidId>bf3f4e3a-7ad2-4dd2-b3c7-9757e3e9c2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtPeriodicidadCadaIncremento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtPeriodicidadCadaIncremento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d58fd978-c2a7-47cf-9efe-1679eff97f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtPeriodicidadCadaIncremento</value>
      <webElementGuid>4194e014-ac16-4f75-9d1e-dfd8f1212116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89f3d7d8-908c-4b6a-9a02-48f23d935583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>07987bd9-a7ea-4c41-a22f-41c06c749fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ee7eed64-a19c-4e13-8edf-94f9eb466876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtPeriodicidadCadaIncremento</value>
      <webElementGuid>54856425-9af7-4df5-8d51-bf9be0f3f6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas</value>
      <webElementGuid>61aa7fa1-3df7-4f0a-a8c5-d6689db7dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event);</value>
      <webElementGuid>6709cb5e-1531-4c29-8e96-d13d67014dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtPeriodicidadCadaIncremento&quot;)</value>
      <webElementGuid>685674c7-4163-4cc3-9379-2f302cc8a2e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtPeriodicidadCadaIncremento']</value>
      <webElementGuid>9e0c7678-bca6-48ed-9baa-f24c2bb2e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upInformacionBasica']/div[3]/table/tbody/tr[19]/td[2]/div/input</value>
      <webElementGuid>a17ce9db-3971-41cf-95c8-27f3981e487f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/div/input</value>
      <webElementGuid>5ea9360f-85e2-4280-b255-02efd46b30ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtPeriodicidadCadaIncremento' and @type = 'text' and @id = 'ctl00_CPH1_txtPeriodicidadCadaIncremento']</value>
      <webElementGuid>10e0649d-c2c5-4702-a109-8bbb03561ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
