<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DiasPeriodoActualizacion</name>
   <tag></tag>
   <elementGuidId>e9f1a3b5-4fa6-44ae-822b-5272223982b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtDiasPeriodoActualizacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtDiasPeriodoActualizacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0e21e32-10d6-41a9-b87c-631e017d1353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtDiasPeriodoActualizacion</value>
      <webElementGuid>2d118eb0-aa27-40a0-9fd9-ef3f8188d450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>259a1374-e7c7-4b91-a19e-fb896d84ea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>eb8a28de-6bb8-488a-aaa6-f2679e13fcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e7291936-f53d-453e-ae2a-a91fba5cb8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtDiasPeriodoActualizacion</value>
      <webElementGuid>6dc9ebf6-361c-44af-819b-d9061094c276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas</value>
      <webElementGuid>66dae03a-4ba7-4b00-8638-a35343205d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event);</value>
      <webElementGuid>8a3646c3-6a8c-4e4f-b6a2-1f3b7455c1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtDiasPeriodoActualizacion&quot;)</value>
      <webElementGuid>f7fa3726-2285-472c-bc76-1ff66e0160aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtDiasPeriodoActualizacion']</value>
      <webElementGuid>53b27e72-f9db-4ddd-a6f0-e1fa1fd90f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upInformacionBasica']/div[3]/table/tbody/tr[18]/td[2]/div/input[2]</value>
      <webElementGuid>9db88853-a672-435b-8bfd-ccbf6ca24ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input[2]</value>
      <webElementGuid>b51ece15-3c5a-414c-9768-cac0fb7b1abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtDiasPeriodoActualizacion' and @type = 'text' and @id = 'ctl00_CPH1_txtDiasPeriodoActualizacion']</value>
      <webElementGuid>af3dcc28-08a6-4685-b971-2da45f34c40d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
