<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputConstanciaAFIPFechaVencimiento</name>
   <tag></tag>
   <elementGuidId>bb6624f0-90ec-4602-807e-1637cd176bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b0914f-0fa3-47fa-aa72-ea29f7c02331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea</value>
      <webElementGuid>388b5393-ed1a-4581-bde0-3f1549491c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I</value>
      <webElementGuid>160b1adf-5011-469a-af1f-751e4dfa2f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCConstanciaAFIP$EvaluacionProveedorTramite$dxeDteFechaVencimiento</value>
      <webElementGuid>b3ea75d2-6610-4a45-88b6-c6a6d45c1617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>2759ca79-8d0c-4555-b55c-8bbf6b3d5e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>51dba92d-5473-4607-b2ee-01532fc4fc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>e7ed6800-87d9-4fe3-98f1-855aba2c7963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento', event)</value>
      <webElementGuid>0eec1cfa-d4b7-46de-b5d8-0eb7533f6bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08b66dfa-394e-44b9-a621-a70482cc33a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2375f97c-c518-40c4-a85c-0d435fee05a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80fa005b-89b7-45f3-987a-3919a78220a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I&quot;)</value>
      <webElementGuid>e849aa7f-0248-471c-a112-c1b62f858e63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I']</value>
      <webElementGuid>abd082f7-ea68-49d4-85d3-aaaf480e9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento']/tbody/tr/td/input</value>
      <webElementGuid>2043c497-e253-4fcb-9155-184a286fc3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>079e426b-1aad-4c60-b4d3-f53c04395be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCConstanciaAFIP_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I' and @name = 'ctl00$CPH1$UCConstanciaAFIP$EvaluacionProveedorTramite$dxeDteFechaVencimiento' and @type = 'text']</value>
      <webElementGuid>f3301670-2d9e-412e-b0e0-6c4437137a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
