<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputConstanciaIIBBFechaVencimiento</name>
   <tag></tag>
   <elementGuidId>cea2d7b0-cd35-4fc3-b9a0-a58fd993934e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b20308f2-06c8-44df-a481-f52768a5c089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea</value>
      <webElementGuid>844b6715-7f74-435a-9079-f11eb3c61a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I</value>
      <webElementGuid>1b97bdbd-b02b-4f46-8e09-92e3a9127d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCConstanciaIIBB$EvaluacionProveedorTramite$dxeDteFechaVencimiento</value>
      <webElementGuid>475e034e-98fd-4bbd-b073-bbe52c5b67dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>8236cdf2-9b73-446f-a01d-c815a86a9554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>db4088c3-fd91-4ad9-aa59-2702b7faf4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento')</value>
      <webElementGuid>4a17271c-13c9-4e16-81f3-d9c6db2b5e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento', event)</value>
      <webElementGuid>eba5498e-5d4a-4985-bbc3-cfbf90465834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88c2a8de-a935-4e7f-81ab-3e173721e4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1833b98-2165-4441-8af4-14cfb074965e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aaa8d1c3-22b3-4483-a178-6adfdce78e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I&quot;)</value>
      <webElementGuid>1c50b6e9-9645-419f-9805-c4990fd16d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I']</value>
      <webElementGuid>96d31800-7ede-4afe-a058-3dd78e19fadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento']/tbody/tr/td/input</value>
      <webElementGuid>287ac21b-0c77-4967-8c82-2b425956c876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>319be1fe-8a1a-49bf-9512-2f9a43e33d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCConstanciaIIBB_EvaluacionProveedorTramite_dxeDteFechaVencimiento_I' and @name = 'ctl00$CPH1$UCConstanciaIIBB$EvaluacionProveedorTramite$dxeDteFechaVencimiento' and @type = 'text']</value>
      <webElementGuid>9c238f10-21d5-4315-96ad-9649c7b3f65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
