<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbAprobadoPrimerClase</name>
   <tag></tag>
   <elementGuidId>bf025408-fd31-4dab-b2e3-5c07eed6b1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f51e535-ef51-48d0-a481-20cc40313bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado</value>
      <webElementGuid>e1b91049-0640-4bfa-a663-c106a8418726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ba724b31-b275-49ab-9937-fa8c9add8b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion</value>
      <webElementGuid>83065a7b-45bd-4097-b6b3-45f9cf23834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtAprobado</value>
      <webElementGuid>be75bfa1-7208-44b1-be0b-16ed715db28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtAprobado\',\'\')', 0)</value>
      <webElementGuid>262f0c35-dec3-47e0-9b65-7a5952ce44bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado&quot;)</value>
      <webElementGuid>d1cd10c1-2c3d-4d32-9a4f-bd7141e99d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado']</value>
      <webElementGuid>a68728cb-50cc-47f3-b951-e3edd39a0421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input</value>
      <webElementGuid>d48ae4bf-01fc-4ee1-b328-c498963d7dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/input</value>
      <webElementGuid>5e4efd94-a882-45c8-a3d6-8299bc89ba56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtAprobado' and @type = 'radio' and @name = 'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion']</value>
      <webElementGuid>da7cec41-fad4-4801-9ef2-7b104fb30493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
