<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbRechazadoSegundaClase</name>
   <tag></tag>
   <elementGuidId>25714604-7d44-4fe4-b4d9-dd29c72a46d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e03a0ad-2c5d-4523-ad13-f2eb8f21f69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado</value>
      <webElementGuid>a7f7e972-cf6a-4c29-b6a6-8bbacb3b7b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>91ded4ce-de56-4bc2-8f63-39be51132b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl03$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion</value>
      <webElementGuid>ef5dc888-fd88-4ddb-93f6-c2dc4fdf1a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>f0184854-11ec-4f46-8f88-408da679f249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl03$UCEvaluacionProveedorTramiteRubro$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>9b25c485-d900-4fbf-9d91-d9062e916a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado&quot;)</value>
      <webElementGuid>dd61e069-3520-4678-a533-50a56fa41748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado']</value>
      <webElementGuid>1f08f52b-64f1-4966-b449-2b7e05bf4b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[2]</value>
      <webElementGuid>fb5b4e1e-015b-478c-a0f5-6c3d87cce2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/div/div/div/input[2]</value>
      <webElementGuid>14fe0a23-14d2-40f2-9e9c-9f9c343804fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl03_UCEvaluacionProveedorTramiteRubro_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl03$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion']</value>
      <webElementGuid>54494d4c-ca7e-4d5a-a0ec-64418c36e083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
