<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbRechazadoPrimerClase</name>
   <tag></tag>
   <elementGuidId>8f90c89f-1be5-40ef-8284-c1497d0ab76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b529483-8182-401e-ac9d-95441c75c119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado</value>
      <webElementGuid>be214c37-7454-4e14-a364-95528907eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>57fb7955-e885-4661-bae7-6bd6871fd47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion</value>
      <webElementGuid>20b249e2-a82a-493d-b87f-7668b9046f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>022fc255-b5e2-4724-bdb4-8cec55c591b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>c4316324-1045-4782-958d-e669601fc9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado&quot;)</value>
      <webElementGuid>8159c7fe-3f51-40d1-91d7-007c6bc19e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado']</value>
      <webElementGuid>313038e1-b41d-4eb3-b95d-36bd9ce31fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input[2]</value>
      <webElementGuid>3c7f926b-c3e7-4e67-8e15-32195cb5b6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>5fa128cc-8f6f-4efb-9a16-021c5a88ab97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$rbtnEvaluacion']</value>
      <webElementGuid>de198dc4-3cdf-4311-b3bd-678f6d24f876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
