<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaObservacionesCertificadoSalud</name>
   <tag></tag>
   <elementGuidId>fa2c5d97-a3d9-41d4-ab92-099a77576068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9b975137-d73e-4210-ac8f-b2a55bf4b202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCCertificado_Salud$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>a9789bde-751d-4fd3-9ff4-6f7dadd91569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6ab6c015-596b-439a-822c-ad293bdbbe07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f08c1585-06ea-44eb-aa02-f68e3d23a0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$UCCertificado_Salud$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>ad7603a2-4db4-4e57-8199-bf9202faaf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>dcb87873-9d58-4a4f-aac5-f5fac055fddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d152f0a6-1d44-4f32-b78d-b110aa914697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>e10420e4-086d-4c58-a2af-8617f6aa3a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>c51272a2-9aa8-4b42-a8a3-955b2bb685d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[4]</value>
      <webElementGuid>0ba2d557-cde3-4fdb-9a13-260aec553318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/div/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>d642fbec-cea2-4c8d-a960-8328cd575968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$UCCertificado_Salud$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_UCCertificado_Salud_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>c5e7d0ab-d886-462b-9843-cc9ca4576a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
