<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaObservacionesPrimerClase</name>
   <tag></tag>
   <elementGuidId>6df1a40c-7f7e-4188-be45-8076bc7006ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>34ad051e-288a-4ce7-8106-190835ce7479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$txtObservaciones</value>
      <webElementGuid>0e9bac84-021b-492a-b929-e5555d47e86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e01f879f-dc86-4411-a6b3-fbf90579601f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d541de36-c959-4115-992f-7bf8b70d67d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>a3eddab4-4683-448e-8c17-f5e66196e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones</value>
      <webElementGuid>6b47f757-5b24-4de9-a9fa-14d6bfedea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0e4d522-e495-47bf-8748-d63f968af564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones&quot;)</value>
      <webElementGuid>55c966e2-244f-45cd-9234-8e21d24cd26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones']</value>
      <webElementGuid>84ad268a-f38c-4a12-92ac-6edecfeaa1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divObservaciones']/textarea</value>
      <webElementGuid>6e908296-683b-4eb6-9c8d-0cc2f629fbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>c52e586b-b002-4467-ac8f-985b9fdc261b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$tablaRubrosClasesInscriptos$gvRubrosClasesInscriptos$ctl02$UCEvaluacionProveedorTramiteRubro$txtObservaciones' and @id = 'ctl00_CPH1_tablaRubrosClasesInscriptos_gvRubrosClasesInscriptos_ctl02_UCEvaluacionProveedorTramiteRubro_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>6dc48f86-6d13-49af-a75c-f19c6edf6cad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
