<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Anio</name>
   <tag></tag>
   <elementGuidId>60274dbd-d329-4c1a-933e-b8ccb495c681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_ucIngresarActo_DropDownAnio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ecaac999-4cb2-47f9-be59-d4fca6cf8d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$DropDownAnio</value>
      <webElementGuid>a48ab544-37f9-49e4-a51a-72dd8268415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_DropDownAnio</value>
      <webElementGuid>10e9a6b1-34cf-46e3-b906-0b2e20102f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a58aa153-8847-421c-9893-bc897732167f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	</value>
      <webElementGuid>963cd25f-4e81-44c9-9f8e-80edd1e1a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_DropDownAnio&quot;)</value>
      <webElementGuid>d0fa437b-c900-408d-8b2e-79014ed24c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_ucIngresarActo_DropDownAnio']</value>
      <webElementGuid>2eedb77a-675a-4e2d-8d9a-3e8dc5cf6706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaAnioDocumento']/select</value>
      <webElementGuid>1c2dd63f-67c3-4c7b-9b4d-a7f3706a44a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[1]</value>
      <webElementGuid>efc412d9-126b-49df-9194-3cabd984e3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>1ed0455a-e8d0-49e8-9251-f0fdb0b5cdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifique que el año haya sido ingresado.'])[1]/preceding::select[1]</value>
      <webElementGuid>20c7ecc5-4322-4b70-99fa-e3db58adb2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>aab8f375-500e-4c60-978e-f20f22ade04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>c98ecc34-188b-48bb-97e0-a19ffb95aab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$ucIngresarActo$DropDownAnio' and @id = 'ctl00_CPH1_ucIngresarActo_DropDownAnio' and (text() = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	' or . = '
		Año
		2014
		2015
		2016
		2017
		2018
		2019
		2020
		2021
		2022

	')]</value>
      <webElementGuid>46ef6bc1-4aa2-4742-b153-bca1e5faf298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
