<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vincular</name>
   <tag></tag>
   <elementGuidId>c8a0837e-985a-41c6-8c63-c1f3ed4ebf63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6a89c0e-fe36-4bef-abcd-03d13c77ec2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cargandoFondoGris();</value>
      <webElementGuid>7a506661-6ece-461f-b418-2430679ce5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular</value>
      <webElementGuid>8d8ebf49-baba-49fa-becc-28bb01828250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vincular</value>
      <webElementGuid>49b8786b-d076-49e4-851d-92c96a5069ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$ucIngresarActo$rptActoAdministrativo$ctl01$btnVincular','')</value>
      <webElementGuid>343564e7-09d7-4a9a-a3f2-cdc0f8081302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vincular</value>
      <webElementGuid>b6629d7d-de47-41f6-bde1-fe1d7550ef0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular&quot;)</value>
      <webElementGuid>41a35dab-b0c8-4e1f-a958-5e9c7c55529e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular']</value>
      <webElementGuid>b9e70929-a5d6-46da-80ce-716baa03d271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_liVincular']/a</value>
      <webElementGuid>0d393129-036f-4879-bfe9-4081d0e45eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vincular')]</value>
      <webElementGuid>c47dccae-da96-40a6-a3b2-cf71a132272d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DI-2024-3-DGGDOC'])[1]/following::a[1]</value>
      <webElementGuid>60ea76a8-3140-4d28-977a-ac06988c4f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desvincular'])[1]/preceding::a[1]</value>
      <webElementGuid>d65aa88b-0b55-496c-b3bd-2fd54485adc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/preceding::a[2]</value>
      <webElementGuid>23d48a83-3b2d-4d3e-afb5-7f8310d7a455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vincular']/parent::*</value>
      <webElementGuid>5f0785f2-2e32-4fcf-9f6e-5eb1098e37c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$ucIngresarActo$rptActoAdministrativo$ctl01$btnVincular','')&quot;)]</value>
      <webElementGuid>204a9fea-de34-4f16-8eca-32ee9f711d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/ul/li/a</value>
      <webElementGuid>d0082526-70d2-45e1-9944-8d760199f61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_ucIngresarActo_rptActoAdministrativo_ctl01_btnVincular' and @title = 'Vincular' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$ucIngresarActo$rptActoAdministrativo$ctl01$btnVincular&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Vincular' or . = 'Vincular')]</value>
      <webElementGuid>d63deb17-3830-49fc-a9ce-a0854132daa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
