<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numero</name>
   <tag></tag>
   <elementGuidId>0c9defa3-936f-4b16-980f-f24ba387fd5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_txtNumero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ucIngresarActo_txtNumero']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b16c1fc0-ffcb-4b27-a717-431c28797119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$txtNumero</value>
      <webElementGuid>ff5ff74d-8f67-413e-a884-56ec773df721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce979028-aa60-47ae-855f-119341523313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1c97dd42-fc6d-421d-b8ff-3ca493a6cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_txtNumero</value>
      <webElementGuid>02095eae-958c-4792-b892-defb4f46f487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91df3930-3ddf-42dd-a024-5a91810c8204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumerosEnteros(event)</value>
      <webElementGuid>7c4fc42b-337f-4a02-b6b7-bead187c78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_txtNumero&quot;)</value>
      <webElementGuid>ea25c9d7-f28b-4051-b922-e4a9dd1c92e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucIngresarActo_txtNumero']</value>
      <webElementGuid>67c1e30e-553b-4e6a-95de-8bbe36eb3148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaNumero']/input</value>
      <webElementGuid>f942d246-9cb4-45db-b8c1-9c8ff40191a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b495dae7-6c71-4f4e-a5bb-40a5e1114f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ucIngresarActo$txtNumero' and @type = 'text' and @id = 'ctl00_CPH1_ucIngresarActo_txtNumero']</value>
      <webElementGuid>3715fdae-2671-4aeb-ad50-d0b53e532179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
