<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Especial</name>
   <tag></tag>
   <elementGuidId>96dd2cd2-1c71-4c1f-8896-c0b55ed2bca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_rbNumeroEspecial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ucIngresarActo_rbNumeroEspecial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75c8da9f-dfc8-454c-b308-37abc898ec27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbNumeroEspecial</value>
      <webElementGuid>b8686bfa-7622-492e-bba9-d16b53c106ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$rbTipoNumero</value>
      <webElementGuid>72193912-f38c-47ba-b9fe-e01662fee136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1a89699d-f32f-484b-8ae8-5e78d90e7a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_rbNumeroEspecial</value>
      <webElementGuid>bb323565-84b8-474b-b678-f9485e985bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_rbNumeroEspecial&quot;)</value>
      <webElementGuid>695c531d-feb7-45b8-a321-b5fad2093d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucIngresarActo_rbNumeroEspecial']</value>
      <webElementGuid>f8e7448a-69c1-43ee-9088-102c35495e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaTipoNumero']/input</value>
      <webElementGuid>1bb54034-0a42-4603-a49a-0105b51e9231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>eea3b827-aff2-41b1-ba73-eeda64636050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ucIngresarActo$rbTipoNumero' and @type = 'radio' and @id = 'ctl00_CPH1_ucIngresarActo_rbNumeroEspecial']</value>
      <webElementGuid>e0408649-7cc0-4b84-a167-145ebb1c0057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
