<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reparticin</name>
   <tag></tag>
   <elementGuidId>8fed7fd3-d3ad-48bf-8c6d-c6a0287fe8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucIngresarActo_txtReparticion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ucIngresarActo_txtReparticion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43adee65-df74-4352-9006-9f53d6e05a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucIngresarActo$txtReparticion</value>
      <webElementGuid>06d41a12-3452-4491-9502-334cb7124785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b4f0b3d-a6d7-43fd-aa78-f89b822a5b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>863c01c2-194a-42fd-afe9-336b6cfc5bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucIngresarActo_txtReparticion</value>
      <webElementGuid>d48adefb-7aec-4136-9730-c384f461511f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ed8c1097-fd21-4131-8838-cccdbd03a3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>toUpperCase()</value>
      <webElementGuid>1c1ae346-2778-4b4c-ac68-e7cfc8ef45a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucIngresarActo_txtReparticion&quot;)</value>
      <webElementGuid>7da95e47-9397-4ce3-b5c6-4c2e5b9da64f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucIngresarActo_txtReparticion']</value>
      <webElementGuid>47ff6e6c-a309-45ca-bbba-f73a7302e926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaReparticion']/input</value>
      <webElementGuid>c828f23c-0f8d-4fed-adcc-7b4e059ce16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/input</value>
      <webElementGuid>b13b213d-d58b-43c0-99de-fbb625d6e1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ucIngresarActo$txtReparticion' and @type = 'text' and @id = 'ctl00_CPH1_ucIngresarActo_txtReparticion']</value>
      <webElementGuid>0ba6b3a7-16f4-4918-8ba9-9f399e27bf72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
