<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_IngresarImputacion</name>
   <tag></tag>
   <elementGuidId>99c21a1c-4986-4638-8de2-51ae75918c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>267f5ed4-2ff4-413e-b671-5ed091d46c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion</value>
      <webElementGuid>0af6d706-64bf-4479-91ca-38c8212451fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_azul_m_238</value>
      <webElementGuid>a8f36101-7749-40f9-add7-04bfadf6355e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>fec864cb-6176-4b38-b0df-6503cef7ec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UCBuscadorPartidas$lnkIngresarImputacion&quot;, &quot;&quot;, true, &quot;agregarPartidasGroup&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>0c682b14-a882-4537-a037-1d1d1890ddd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar Imputación</value>
      <webElementGuid>510ad24f-b37a-472f-8ca8-f854ea2173c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion&quot;)</value>
      <webElementGuid>24d26578-b7d8-4ce8-a350-1fbadd4cc2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion']</value>
      <webElementGuid>59b09fa4-bcca-45cd-91d9-33a5932454b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[8]/div[9]/a</value>
      <webElementGuid>d9e94092-7f4c-480a-9506-30951bc76145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ingresar Imputación')]</value>
      <webElementGuid>204171df-6818-44fe-ba28-69ad50fc7a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe seleccionar al menos una partida a imputar.'])[1]/following::a[1]</value>
      <webElementGuid>a4658ddc-4e91-4c1d-b68b-c2fd45a0b7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[2]/following::a[1]</value>
      <webElementGuid>fcf2f442-4e20-4860-8a18-856372707cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partidas Presupuestaria Imputadas'])[1]/preceding::a[1]</value>
      <webElementGuid>042d0ee2-9a2e-428d-a91c-22d5225f9771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ejercicio'])[3]/preceding::a[1]</value>
      <webElementGuid>a1c3df0a-4a07-4297-abc0-9d37ded01266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingresar Imputación']/parent::*</value>
      <webElementGuid>e7f6d888-00d7-4332-b574-7804dee579dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UCBuscadorPartidas$lnkIngresarImputacion&quot;, &quot;&quot;, true, &quot;agregarPartidasGroup&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>f805d08e-4d58-4b22-8ce2-e51a3b323cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>a2f498d1-9cbc-4f14-b144-616f430737bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UCBuscadorPartidas_lnkIngresarImputacion' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$UCBuscadorPartidas$lnkIngresarImputacion&quot;, &quot;&quot;, true, &quot;agregarPartidasGroup&quot;, &quot;&quot;, false, true))' and (text() = 'Ingresar Imputación' or . = 'Ingresar Imputación')]</value>
      <webElementGuid>686505f2-1c11-4812-b4e3-8799cf160c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
