<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_SeleccionarPrimerPartida</name>
   <tag></tag>
   <elementGuidId>f94ab556-dc5a-4562-8c70-1ae03fbe9979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>500161a3-c4b7-49be-8895-1735b11bcd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0</value>
      <webElementGuid>162cad39-7b52-415d-835a-688cafba3343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgvCommandColumnItem</value>
      <webElementGuid>e24e9b26-3c9f-4019-9bfe-b7b26a4b66b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2628e2eb-9bfd-43e4-ad92-a0313a18339f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>aspxGVSelectRow('ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas',0,this);</value>
      <webElementGuid>b5022db6-c69c-4b4a-b40a-a4d0f43385d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0&quot;)</value>
      <webElementGuid>470c76e5-c2d9-4aa8-81bd-8fc84badc139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0']</value>
      <webElementGuid>5430240b-bac1-4adc-a212-a012c0a43668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXDataRow0']/td[10]/input</value>
      <webElementGuid>7a48b6c7-92d1-46bc-9cfc-b3e17b53bf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/input</value>
      <webElementGuid>a5fb6047-f32e-4760-b063-229cdcf842ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCBuscadorPartidas_GrillaResultadosPartida_gvPartidas_DXSelBtn0' and @type = 'checkbox']</value>
      <webElementGuid>50ffd89a-9c08-4fa3-b9ff-8af18c8a595e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
