<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Nombre de la solicitud de provisin</name>
   <tag></tag>
   <elementGuidId>dbaf4448-2d5b-4db1-9626-b52a1eaa7ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtNombreSPR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtNombreSPR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6da5bfb9-c8c5-4517-8b60-305bbf1c9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtNombreSPR</value>
      <webElementGuid>a20c6f45-1559-430d-abc5-2591e3ec7241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d2db251e-0ef5-4e99-8739-d27bbff0c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0f04ee4c-f60e-4fbb-8057-5aa8a7fb34dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtNombreSPR</value>
      <webElementGuid>6a2a419a-15f7-4ce6-8e45-1aeeada72a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtNombreSPR&quot;)</value>
      <webElementGuid>7531d43e-7eef-4042-897c-9493545f5404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtNombreSPR']</value>
      <webElementGuid>5cddb44b-a0c6-4b36-8afe-812bcaf1d48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div[2]/div[3]/table/tbody/tr[3]/td[2]/textarea</value>
      <webElementGuid>0bc9077f-21f0-4728-8d09-8cbcf710939d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bf107525-89d7-487a-83b3-2ed2bd1e970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtNombreSPR' and @id = 'ctl00_CPH1_txtNombreSPR']</value>
      <webElementGuid>02fb6637-60c2-4937-a71b-8285d800711f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
