<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnUbicacionGeografica</name>
   <tag></tag>
   <elementGuidId>15c8679c-ca88-4602-917d-e5bae99c3fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicon.glyphicon-globe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UC_ListadoFrentesObra_gvFrentesObra_ctl02_ibGeoInfo']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5c9ae9b-15dd-40df-bea0-3d1a2f69f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-globe</value>
      <webElementGuid>d1966bc4-ddf6-4785-bd15-afcee2a4559c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_ListadoFrentesObra_gvFrentesObra_ctl02_ibGeoInfo&quot;)/span[@class=&quot;glyphicon glyphicon-globe&quot;]</value>
      <webElementGuid>41c34ba6-c8b6-4312-aca4-e6584e7ce540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UC_ListadoFrentesObra_gvFrentesObra_ctl02_ibGeoInfo']/span</value>
      <webElementGuid>2f46fa83-e51d-4dc3-9ab0-9031642ec952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/span</value>
      <webElementGuid>be91e1d5-78ac-4ce9-8b05-7f4a7dae8433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
