<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputObraLongitud</name>
   <tag></tag>
   <elementGuidId>891d73a0-fe77-40a5-917b-7e8623f0b00b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b65c3607-f884-4e4e-99e7-18a8ad386d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UC_ListadoFrentesObra$txtLongitud</value>
      <webElementGuid>8db4ea74-81ea-4a07-b6f4-1bedf3f6425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60cc9aa3-5dc7-47c6-98a2-4b1464dfb1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>671b0b2d-378a-4857-8c6b-250e3ba39d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud</value>
      <webElementGuid>205d6c0d-89af-4beb-86c7-57def9875b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4eea2c7-8a10-49d7-96cd-a274a0a9e5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ejemplo: -54.321327</value>
      <webElementGuid>645ace8f-d550-4bca-8ab3-358f996a5f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud&quot;)</value>
      <webElementGuid>2581eb0b-e6cf-48b4-8f59-773fc6037178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud']</value>
      <webElementGuid>bedf4503-7fa2-454b-bb79-57a472d31b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLongitud']/input</value>
      <webElementGuid>42eea9d4-df40-4931-b719-94cdce5de91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>3f4e118e-a779-483d-b803-560c8e738834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$UC_ListadoFrentesObra$txtLongitud' and @type = 'text' and @id = 'ctl00_CPH1_UC_ListadoFrentesObra_txtLongitud' and @placeholder = 'Ejemplo: -54.321327']</value>
      <webElementGuid>2c81f6fe-6de8-49ab-ad5e-8f87f15df8b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
