<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputObraLatitud</name>
   <tag></tag>
   <elementGuidId>e7a50e8e-64ff-4f52-adc8-2d3db0fde77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adc58ab0-3c85-440f-b605-9a8ced9807a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UC_ListadoFrentesObra$txtLatitud</value>
      <webElementGuid>f741aefe-b4f6-475c-a16d-b5eec2d22e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73b7ae33-e0d8-4110-bbd3-4c41e92b1b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ec30d7a5-aa2e-4a87-a856-1d74830b1981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud</value>
      <webElementGuid>2639d06d-bc84-4c93-a17f-f917b205c1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3fcb1e7a-dae7-4cb6-bb2a-3a0cb7e60d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ejemplo: -54.321327</value>
      <webElementGuid>ed51b3d5-b20d-41b8-8f3f-af8084963875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud&quot;)</value>
      <webElementGuid>1103b150-8712-471b-b5cf-d447efb25378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud']</value>
      <webElementGuid>175d282f-1e0a-46fd-8074-cfea9a1bbf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLatitud']/input</value>
      <webElementGuid>8c4e6773-961b-4e6a-a38a-60332357c15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>11607022-82de-48bf-8257-c44857092116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$UC_ListadoFrentesObra$txtLatitud' and @type = 'text' and @id = 'ctl00_CPH1_UC_ListadoFrentesObra_txtLatitud' and @placeholder = 'Ejemplo: -54.321327']</value>
      <webElementGuid>aff11537-7293-4d4c-9eeb-541b170753f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
