<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ProveedoresInscriptos</name>
   <tag></tag>
   <elementGuidId>927e8f45-3edd-47ba-894f-bb79df439c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6870609d-0646-4ebb-a173-dfa26df05836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0</value>
      <webElementGuid>b76bda97-854e-489d-b882-4369cdaed3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgvCommandColumnItem</value>
      <webElementGuid>ab33f146-6008-4ecc-b047-9d7234fcfb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c22bc82-0ff9-4e44-b5ff-0b9185b1a9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>aspxGVSelectRow('ctl00_CPH1_gvProveedoresInscriptos',0,this);</value>
      <webElementGuid>a8584139-f00a-4ed0-a83e-70985ab4b69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0&quot;)</value>
      <webElementGuid>39e64495-febd-4588-a391-aa90ecf76364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0']</value>
      <webElementGuid>21f8ced7-f4a9-4595-b851-9c3bc42cb25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_CPH1_gvProveedoresInscriptos_DXDataRow0']/td/input</value>
      <webElementGuid>215f46df-b177-4915-b141-03f5094e2992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>d14652c6-58fc-40eb-97a9-e1a452664036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_gvProveedoresInscriptos_DXSelBtn0' and @type = 'checkbox']</value>
      <webElementGuid>5441710d-6d20-4b94-8d9b-48a3148f8015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
