<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbPasaporteRechazado</name>
   <tag></tag>
   <elementGuidId>4ebc8970-0671-438b-877e-2cfa8b3c40d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e23af312-f182-4166-a088-466d85ed6d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>e2bf78cc-3464-4214-9dde-6aaa20972b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>eb3d5753-e93f-4d34-a7ee-134c6b44177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptControlDocumentosExtranjero$ctl00$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>f0788817-ce38-45f7-b21b-dc62617b5c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>814873bb-06a9-42ca-8080-b1f43230e959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$rptControlDocumentosExtranjero$ctl00$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>c6e9ef5c-82de-4422-9d2f-7f65c11adb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>ebf99702-f4f1-41b1-9773-27f4556d5ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>8a806a4e-3bff-415b-ab86-40753d147ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[2]</value>
      <webElementGuid>d69f4f9d-fb48-4ed1-bb38-bdca368ca315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>5589c484-2031-40d7-915e-9dff9f8f9500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rptControlDocumentosExtranjero_ctl00_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$rptControlDocumentosExtranjero$ctl00$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>ea9e3eed-d459-4a68-ae9f-35f108f35089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
