<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbPoderRechazado</name>
   <tag></tag>
   <elementGuidId>8cb1b4e9-60f6-49bd-beda-1aeae9629968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>779dd689-9954-4f5f-9e69-36541f74af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>c86ef40e-c06f-4b63-a7d4-612e5a2e59d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0e50718c-c9ea-440b-a258-17e5559a8eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>ca1a534d-307c-42ca-8819-34ae2238f674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>b4d30b0c-fff6-47ae-8228-303d320aa917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>ddf25fe8-2872-41ea-a6a5-718858ff1e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>7dd2ae4f-fe1a-4259-aa1e-41c39f8ea76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>ca35abfe-aa95-4de3-b632-2305e991f4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[3]</value>
      <webElementGuid>4e954b7d-e499-4706-8301-e969da5cdb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>fc6da86d-eaa1-424e-a2ac-a1f181cc69a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>7eaafbce-dc1c-4f2e-bb2e-7d1db76f20ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
