<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaObservacionesPoder</name>
   <tag></tag>
   <elementGuidId>d653e254-a2ef-485b-a8b1-6af10b7cbd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2974ce1a-0d18-49ab-94b1-4ddfd2def710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>1610896e-f4d0-4410-b0ab-d05a4b390453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>33675236-351a-4f24-aaa5-df94dba19b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fc719492-257b-4275-bff3-04e6a048d17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>65e5f77a-a7a3-403f-b2a5-b59d5efbfab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>fe7ae11a-67fd-46a6-9931-b54349bda34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5c5ce86-9076-4baa-9e56-ca42bddb280d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>a930b0d6-be4a-46f5-ba78-309751866b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>1252741c-000e-4bb7-bab6-07bcf458a7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[3]</value>
      <webElementGuid>29f80949-a418-4484-8933-93ae04780da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>a3136f6c-5c6f-4e6b-b3e6-f9b71cb48600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$rptControlDocumentosExtranjero$ctl01$UCDocumentoExtranjero$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_rptControlDocumentosExtranjero_ctl01_UCDocumentoExtranjero_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>ce16deb7-3d96-421b-af58-85b4612d8036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
