<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaObservaciones</name>
   <tag></tag>
   <elementGuidId>1e68ce03-0bfe-4e73-8f75-cfd2e4b3aec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8df531f8-5dde-456c-af86-4ebce7f44a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>7b323578-cd8f-4563-b38f-57cae144c576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2f9b4d27-3a3c-45d5-a48b-cd365f29e4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>db20d930-51cf-4047-80dc-783b01fd9293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>28b2a4f5-e7af-417d-aeb6-9847b265cc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>7781e942-497a-4fc3-a24d-a3ee050f758d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ccdecef-80b8-4623-b830-1ec6a48b75a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>bc8db5ae-368a-4e18-a0b2-3eb33eab7df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>ef394f40-7b02-4f9b-973e-056033e5e876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divObservaciones']/textarea</value>
      <webElementGuid>2a6f33fd-6ee6-4e37-9443-484655dca354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f5c95c54-c0e2-4327-b5de-47c1508c71e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>7ec15b11-8429-41b4-8ee1-c86bfcbe5c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
