<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TipoAo</name>
   <tag></tag>
   <elementGuidId>a237e1c6-5753-4cb8-bab6-d7fe970daa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_CPH1_DropAno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DropAno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e9e04718-d233-410d-b163-f4c89dd083f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DropAno</value>
      <webElementGuid>5fb9b9f8-41df-4332-aa7e-37a80321ee11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DropAno</value>
      <webElementGuid>2f6d52fc-e1ca-49ef-a3f2-baa61563d859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45c4a355-a097-4cf9-a5c2-9894acbbff97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Año
	2014
	2015
	2016
	2017
	2018
	2019
	2020
	2021
	2022
	2023
	2024
	2025

</value>
      <webElementGuid>7701f00f-a703-4651-b0d0-51782a8eb7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DropAno&quot;)</value>
      <webElementGuid>4927c797-d936-4d29-b357-78aa458e9737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_CPH1_DropAno']</value>
      <webElementGuid>98dfa02d-10aa-4abd-bf80-5a770f6f240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DivAno']/select</value>
      <webElementGuid>f1552094-0815-4ca7-8bfc-7cdcbf75c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>e2fca38f-792b-404e-add4-3f5835dd656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$CPH1$DropAno' and @id = 'ctl00_CPH1_DropAno' and (text() = '
	Año
	2014
	2015
	2016
	2017
	2018
	2019
	2020
	2021
	2022
	2023
	2024
	2025

' or . = '
	Año
	2014
	2015
	2016
	2017
	2018
	2019
	2020
	2021
	2022
	2023
	2024
	2025

')]</value>
      <webElementGuid>0db9deea-22d1-46ff-9174-9bc7a1216b85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
