<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Agregar tem</name>
   <tag></tag>
   <elementGuidId>d086d6f2-2ea4-407d-adc0-3c0c277e1b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkAgregarItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_lnkAgregarItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ba9746d-a39f-48ad-9f8e-654652c1674b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:ocultarExito();</value>
      <webElementGuid>311f6bd3-fe1a-4cd1-9a2d-88f0d1498e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkAgregarItem</value>
      <webElementGuid>4a6bc9a5-5e07-4d76-aef5-890b9c436109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_azul_ch</value>
      <webElementGuid>54eb0518-0590-4ff8-86a2-5b6667c85c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>borderheight</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>7f71d301-d24d-4593-8cca-362621041b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkAgregarItem&quot;, &quot;&quot;, true, &quot;AgregarItem&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>7fd5ed59-7a7f-4280-9bef-f98371b032c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar ítem</value>
      <webElementGuid>f6f59905-fb00-4c8c-96e4-e5cc5c22ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkAgregarItem&quot;)</value>
      <webElementGuid>839bfb35-2bd8-44f7-b8ac-1fcd4a507bd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkAgregarItem']</value>
      <webElementGuid>2a2ecb17-78e1-4156-8d40-0a5ffbfb25c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upBotonesItems']/a</value>
      <webElementGuid>8529f49f-c66e-4495-9533-dfd983fbc2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agregar ítem')]</value>
      <webElementGuid>f400f507-c064-463c-bb80-a08fff59d413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requiere precio de referencia:'])[1]/following::a[1]</value>
      <webElementGuid>305583dd-e1e8-4c7d-b6a1-688a2c01a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifique que el campo precio unitario haya sido ingresado y sea mayor que cero.'])[1]/following::a[1]</value>
      <webElementGuid>2a0a4d63-eeb3-4bf0-a3e8-ffa5effc1d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se ha agregado el ítem exitosamente'])[1]/preceding::a[1]</value>
      <webElementGuid>2ca4d3f3-b72a-4882-a11b-4e97d90a9cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar ítem']/parent::*</value>
      <webElementGuid>ab78fdac-0e04-4b24-aa7c-99379d654bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkAgregarItem&quot;, &quot;&quot;, true, &quot;AgregarItem&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>595751f1-429d-459d-8edb-cb7708c09890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>1f0b7fcd-2f3e-45f0-ab12-cacf5bd54d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkAgregarItem' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$CPH1$lnkAgregarItem&quot;, &quot;&quot;, true, &quot;AgregarItem&quot;, &quot;&quot;, false, true))' and (text() = 'Agregar ítem' or . = 'Agregar ítem')]</value>
      <webElementGuid>3acd5888-c8c5-4baa-b92d-aa6a24670fc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
