<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Precio unitario</name>
   <tag></tag>
   <elementGuidId>d9728019-263b-4009-9ab1-dd654203ce99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_sePrecioUnitario_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_sePrecioUnitario_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>509460ab-4483-4120-b260-c03aeb12ca02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$sePrecioUnitario</value>
      <webElementGuid>9007aac6-6fef-474c-9979-14ad865ed3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_sePrecioUnitario', event)</value>
      <webElementGuid>020486c7-43b6-4bc0-ad50-f58d3c78a09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a249d8c1-19ba-460b-b40b-6cc7bb2e9e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_sePrecioUnitario_I</value>
      <webElementGuid>9a302591-464e-4930-b6fe-3b9c7b2b635f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_sePrecioUnitario')</value>
      <webElementGuid>d921e716-33f5-484e-8958-4013bfaca66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_sePrecioUnitario')</value>
      <webElementGuid>4cf30959-39f9-44cc-b090-1007d2493f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_sePrecioUnitario')</value>
      <webElementGuid>7b13d66e-d885-49ae-b369-afdaf24e89f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57088a22-875f-4f99-8ef6-527aa2bc0fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>aspxEKeyPress('ctl00_CPH1_sePrecioUnitario', event)</value>
      <webElementGuid>369ad226-9a43-42c4-b22f-e7feb0d8e856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('ctl00_CPH1_sePrecioUnitario', event)</value>
      <webElementGuid>e95bf4cc-21e0-4e8b-ac1d-141ffc5a9134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12a755b9-9481-4ff7-b2dd-0df225855bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>866fcf76-b211-439b-bf28-27d8087f29fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_sePrecioUnitario_I&quot;)</value>
      <webElementGuid>4d5f7125-db59-4d63-8cab-6a5874a319e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_sePrecioUnitario_I']</value>
      <webElementGuid>97b74630-d95c-4a67-8100-ce7dfaa6b330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_sePrecioUnitario']/tbody/tr/td/input</value>
      <webElementGuid>97d42c96-024d-4236-ae6b-54f12ba30bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>495f959e-93c8-4b1b-bcd5-055d1bbd8037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$sePrecioUnitario' and @id = 'ctl00_CPH1_sePrecioUnitario_I' and @type = 'text']</value>
      <webElementGuid>b197b670-c42c-4f77-b6f4-7eee7402ae8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
