<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Observaciones</name>
   <tag></tag>
   <elementGuidId>2bb883da-8a21-4bec-ad75-8cf689ea5504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtObservacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtObservacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3579d82e-a331-4776-892a-d8225b40700e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtObservacion</value>
      <webElementGuid>0df85f39-f4fe-444d-ae80-5e353df5b514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>20dfdfe2-2156-4fc8-aa55-39889601ced2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1dbcb568-cf1a-4f46-b2ea-f396b42dc674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtObservacion</value>
      <webElementGuid>6485f9a3-dbc5-4da6-a19d-9b43dafc8a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onlostfocus</name>
      <type>Main</type>
      <value>Page_ClientValidate();</value>
      <webElementGuid>d4722d00-7dd7-4498-9b47-83ba309e4e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:cortaLargoMaximo('ctl00_CPH1_txtObservacion',255);</value>
      <webElementGuid>ca4d69e1-752f-4658-9368-56f36d0ac985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtObservacion&quot;)</value>
      <webElementGuid>5fa9caf2-bb32-48a0-a981-c1b7498aa1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtObservacion']</value>
      <webElementGuid>eb8c7276-d24e-4711-a59f-9888cd20a10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upContenidoPagina']/div[17]/table/tbody/tr[7]/td[2]/textarea</value>
      <webElementGuid>53c3bebe-b8c2-43a3-a58a-95fd74bb2e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/textarea</value>
      <webElementGuid>03b49301-6314-4a7a-92e4-8e8a576fa78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtObservacion' and @id = 'ctl00_CPH1_txtObservacion']</value>
      <webElementGuid>7dd30cf4-2277-4bb4-ab42-2ba89754057f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
