<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Especificaciones tcnicas</name>
   <tag></tag>
   <elementGuidId>3e8f351c-cd14-46cc-9177-1ea6a55624a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtEspecificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_txtEspecificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7ca29adc-b2d6-4c6a-9da3-53378b6456f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtEspecificacion</value>
      <webElementGuid>2cddaf38-b9d3-4ca6-ad7b-be73f783e08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>36268bcb-f606-4ce5-a5dc-cde0a4c78538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2b2cc7f9-6495-4d16-9515-bbb92c294290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtEspecificacion</value>
      <webElementGuid>df6b2578-1260-481b-af14-404b762d27fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onlostfocus</name>
      <type>Main</type>
      <value>Page_ClientValidate();</value>
      <webElementGuid>d90b0c1d-ba38-4ca2-a367-9f65896f377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:cortaLargoMaximo('ctl00_CPH1_txtEspecificacion',255);</value>
      <webElementGuid>89e1fad9-0d88-42bd-84d2-0dfff241d816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtEspecificacion&quot;)</value>
      <webElementGuid>1f1e4f7f-b9f7-41d6-8960-19bbaf8f12e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_txtEspecificacion']</value>
      <webElementGuid>6be32050-c74e-468b-877d-f983b59e8982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upContenidoPagina']/div[17]/table/tbody/tr[8]/td[2]/textarea</value>
      <webElementGuid>6d633d94-f2f3-4a90-813f-e9b060b96818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/textarea</value>
      <webElementGuid>f0783492-c4ba-41cc-bcd6-96d3bcbb81c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$txtEspecificacion' and @id = 'ctl00_CPH1_txtEspecificacion']</value>
      <webElementGuid>fb9fc626-419f-47bc-b98f-2717cc1b4e1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
