<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RegistroCUITCUIL_cuit</name>
   <tag></tag>
   <elementGuidId>11fd0274-a81b-4b4b-8b18-aac6d816ca64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cuit' and @name = 'cuit' and @type = 'text' and @class = 'MuiInputBase-input MuiOutlinedInput-input Mui-disabled Mui-disabled']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cuit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cuit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec69cc6f-e120-4382-8b60-a0ee81cf170f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4476ed48-7e12-4b7f-b039-ea17bbdc1012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>CUIT/CUIL</value>
      <webElementGuid>f12da293-d650-422d-a4f2-67e776c70f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cuit</value>
      <webElementGuid>fb51b0de-6e50-40c3-859f-9448bd447abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cuit</value>
      <webElementGuid>89b0a212-2ba5-45e6-bead-29c49c7bb03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b0767a6-8674-479e-bf3d-844e996b2891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input Mui-disabled Mui-disabled</value>
      <webElementGuid>6c7e4dfe-16f3-44cd-afd2-b7cf472b3947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>27-19544442-6</value>
      <webElementGuid>6e052ce0-0faf-43cc-94a2-e18ab1e4b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cuit&quot;)</value>
      <webElementGuid>08b4205a-725c-45d6-ad86-23a566b328eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cuit']</value>
      <webElementGuid>2cfe2a51-164e-4e92-a298-809d5117034b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/form/div/div/input</value>
      <webElementGuid>500755b8-260a-4eed-a5bf-4b980923b9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b704211d-3f41-417f-80e2-74ba131ab2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cuit' and @name = 'cuit' and @type = 'text']</value>
      <webElementGuid>93250bcb-b6c6-4b9a-898f-edf4c19937c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
