<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_msjConsultarRecibosAtencin</name>
   <tag></tag>
   <elementGuidId>885807a8-bf5c-46e9-97a6-1b0fa42d4b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transition-modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='transition-modal-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>220bb7d5-ad8b-41c8-88b6-974422af67a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h6</value>
      <webElementGuid>71ed2b7e-c816-48e3-b280-dac62d4de424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transition-modal-title</value>
      <webElementGuid>3fe94d25-0563-4d04-b8aa-1e35073d70c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Atención!</value>
      <webElementGuid>8efbc67d-a3e2-401d-bb4b-ed4370c33c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transition-modal-title&quot;)</value>
      <webElementGuid>6d78f305-7310-480e-a90a-8e1ab6c14ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='transition-modal-title']</value>
      <webElementGuid>c2a7bc50-d2de-46b6-961b-38456b1253e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalObsba']/h2</value>
      <webElementGuid>73ceef94-4db3-4a61-bcbf-f0e642691858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'transition-modal-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>2790b728-58ee-43c1-b7b8-32696a4ba2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h2[1]</value>
      <webElementGuid>9f61ea1f-3fe8-4bab-9b94-1e9e13251499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Atención!']/parent::*</value>
      <webElementGuid>9b9cdbf1-c21c-4f47-acef-e8eaa491d829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>958fadc9-d0e4-4e08-9568-737191eb2a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'transition-modal-title' and (text() = '¡Atención!' or . = '¡Atención!')]</value>
      <webElementGuid>d5557920-4e88-4709-bad6-3ee38608c063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
