<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbDatosBasicosAprobado</name>
   <tag></tag>
   <elementGuidId>f53d98b9-1440-4f04-8e33-5f2c1a971d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7001445-455e-4f51-b27e-849f11df092f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado</value>
      <webElementGuid>bb5ced22-a229-4946-96c4-1c14e9e355ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d4df5d53-68db-4d6f-a4d1-66b905bfb808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>bc0e3d3c-87e1-4858-8173-4a1abc11b93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtAprobado</value>
      <webElementGuid>b7e0e046-4534-45a9-9081-50ddb6497f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtAprobado\',\'\')', 0)</value>
      <webElementGuid>dc6b456d-7e9a-4c5c-b948-8e0a4e0e2763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado&quot;)</value>
      <webElementGuid>d4207fff-fdbb-4977-a65e-a0b1f0e55c7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado']</value>
      <webElementGuid>cae91861-b355-4589-a93f-672f806908be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input</value>
      <webElementGuid>868ca29e-9c4d-4755-af22-fd389bc1e621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>be73b167-10ef-4978-a2f5-be516555e7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtAprobado' and @type = 'radio' and @name = 'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>5790bf7b-8eac-4d61-8ba1-2149c3b495e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
