<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbDatosBasicosRechazado</name>
   <tag></tag>
   <elementGuidId>0723ac81-24bd-419e-ac74-5f9898eff560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c89c7861-a51c-486b-ab77-0b8d2dd06d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>4434f927-ca82-4d0d-a465-e5ca9b4da8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>83be2a74-56e9-4f3e-87b4-c96e0c435667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>cc8b72a0-12be-481a-aa52-dcffff05b053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>6d582f24-25ba-4b05-b5b7-3b7650ee728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>b022a6b3-1813-4c67-bfb2-7a4a945ff643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>2b969d01-9da1-4862-bf2f-0fe6e1828e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>c1eca1c5-4c69-4cd7-b97c-8059cd870f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input[2]</value>
      <webElementGuid>8a775540-f080-4428-909d-0e52971c12fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>15984fd8-c3a4-4847-8fec-ba0a302c1f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>f83ea308-00a2-44e6-b4db-1dfc37ce8ed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
