<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbDireccionCABAAprobado</name>
   <tag></tag>
   <elementGuidId>da3e58d5-7571-454e-b1e4-4559d5275456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13561bcd-661b-4a0f-adb7-c8742e0ccc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado</value>
      <webElementGuid>87423e03-a0cd-419b-9a0a-05abede5d368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e45856b4-9fa7-4f72-a5c9-ca060e433ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionCABA$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>6497cac5-b1c4-4f5e-8352-eb49c79344a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtAprobado</value>
      <webElementGuid>f50d044e-711f-4795-9085-aab941b8e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DireccionCABA$EvaluacionProveedorTramite$rbtAprobado\',\'\')', 0)</value>
      <webElementGuid>56e83133-7494-434a-8784-363c2c4f1b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado&quot;)</value>
      <webElementGuid>023e4fdf-6a4f-40c7-8079-5c640f7bc858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado']</value>
      <webElementGuid>0de3455f-7c9b-44ce-89ca-315c8a77a8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input)[9]</value>
      <webElementGuid>31b0cee5-6106-45cd-8545-4efa6074d7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>6dcb0bb6-3405-4667-958d-0e68cb2ac829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_DireccionCABA_EvaluacionProveedorTramite_rbtAprobado' and @type = 'radio' and @name = 'ctl00$CPH1$DireccionCABA$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>d1d0b3dd-505e-49d4-8542-eb48e638174f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
