<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbDireccionLegalRechazado</name>
   <tag></tag>
   <elementGuidId>4b621ded-51e1-4a73-b5f1-2da74554e6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ea33d7d-756f-40fd-8452-21fe3448dc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>243e869a-1c1a-4cb1-8dde-da63fbd19234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>05637925-7239-4362-9d60-2146c720d575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>e3b5d31d-2013-47f0-879c-eef70b0f4f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>2ad95cf2-b807-4d68-897b-7148f1067b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>d93671b3-c909-4e64-96f1-83e032101395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>0950d238-f78d-4464-b062-7c9acdca59c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>5a1e56fa-bb9d-4097-8a0d-3c5b610892b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[4]</value>
      <webElementGuid>8fbb2d5a-1c84-4191-b94b-1b4f26f4c6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>d54e9023-d13e-4afc-a04b-c92a5d290a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>79c13f12-51b9-4342-9dab-859a2188abdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
