<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbIngresoBrutoAprobado</name>
   <tag></tag>
   <elementGuidId>e2acc37b-1d31-4c54-b54c-04582abd36c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>729547c7-7191-446f-bca3-1465bd3951ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado</value>
      <webElementGuid>a7c7a0b3-ddc3-49d6-a9aa-80a7edc6fc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>de40dcbb-2fdc-4d3d-bfc7-bbc2f3ed187e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>71049ed9-a10c-4ae0-8eaa-1efb35feb4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtAprobado</value>
      <webElementGuid>1b024f33-10f3-4c5c-a614-94b4e8240380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$rbtAprobado\',\'\')', 0)</value>
      <webElementGuid>ecd52a97-0d94-44ae-9a0c-2dcfef61327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado&quot;)</value>
      <webElementGuid>54c11470-5a5e-455b-b411-cf96b8459edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado']</value>
      <webElementGuid>d82adadb-2f98-46b7-a00d-3e501abd8344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divEvaluacion']/input</value>
      <webElementGuid>73ccf02a-4065-4272-a039-bca064f7f68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>686f2d15-99b2-4c39-8820-10fe7d942aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_rbtAprobado' and @type = 'radio' and @name = 'ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>36e01d69-1f4e-40dd-84ad-d90e9f9cc53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
