<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbInteradministrativasRechazado</name>
   <tag></tag>
   <elementGuidId>936b5e0a-d2d7-440c-9460-e3c8eb067e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2a3a1bd-31ff-4108-be73-017f9866b77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado</value>
      <webElementGuid>8eda58d5-d857-4f0c-bf9f-d50ce4aa1144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3dce1e6b-e471-4231-9303-b91716a059d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$Interadministrativas$EvaluacionProveedorTramite$rbtnEvaluacion</value>
      <webElementGuid>05b08077-cf4d-4e29-8780-72f27db81d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtRechazado</value>
      <webElementGuid>7fe40ec2-1179-4aec-bfb6-4b68a1cd96ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$Interadministrativas$EvaluacionProveedorTramite$rbtRechazado\',\'\')', 0)</value>
      <webElementGuid>89a91194-4a72-4d51-b81a-e30eda678b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado&quot;)</value>
      <webElementGuid>2ca3116c-06cf-4147-8862-b9f019b06696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado']</value>
      <webElementGuid>3fb6c87d-625c-4f5a-a6de-6494b4bbcd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divEvaluacion']/input[2])[6]</value>
      <webElementGuid>93bf7756-305e-4b44-8452-655c73719983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>f4b683ed-19d6-425c-a8c2-7b7ad5a0428d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_Interadministrativas_EvaluacionProveedorTramite_rbtRechazado' and @type = 'radio' and @name = 'ctl00$CPH1$Interadministrativas$EvaluacionProveedorTramite$rbtnEvaluacion']</value>
      <webElementGuid>cf96da6c-a611-4b97-9742-80f696ee3ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
