<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaDatosBasicosObservaciones</name>
   <tag></tag>
   <elementGuidId>ed34a5da-2a57-4e0d-b27c-f72646f4ab12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b5385ca8-c304-4289-aa20-23196893a123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>3785a948-c5d5-4540-b3d7-750f59ccc201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>26686b38-d13a-4af3-a5ef-e991913517d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a6399e52-f3bc-4a85-8693-3dced16e997a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>00ae1321-3864-47b9-a16e-7493443bf2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>1bea4617-4903-4565-8880-13cd0c3b6f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9685bf9c-8a38-4070-ba92-25b0c15d1900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>4433ff02-5da7-410b-b696-5469c0352ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>4980e63e-e9b8-4152-9976-e35e46b43049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divObservaciones']/textarea</value>
      <webElementGuid>7092eb50-3e1f-4e49-852c-4418bfd66018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3702cb2c-a45b-4f37-a245-663e75d7333c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$DatosBasicosProveedor$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_DatosBasicosProveedor_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>0b3057e6-0e62-43a8-8ea8-286fa743d4fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
