<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaConstitucionObservaciones</name>
   <tag></tag>
   <elementGuidId>ef49234b-3d59-4727-b2ce-f134825972e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>52d025a9-30ff-43c9-ae4a-d19c9469d73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>fb4a0e35-2a1f-4cfc-8138-64d1e2db7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>71d40f81-138c-43a8-8a12-808cafe63afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>bc870e41-b3c8-432c-a962-6f2fcfc5dec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>c475fbcd-4030-40e3-a682-967ccf4343eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>2c542660-705e-410e-bda7-f813c6e7b31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>010d8578-01c6-4d95-bf47-0a08658e30fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>a8a22591-82b2-4cd6-8313-feb08b42c5be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>91fbd2a0-19e5-4ce8-b043-9d7a7b671170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[2]</value>
      <webElementGuid>13696604-d47a-4a2a-8f39-1bf7e7a18076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>7016a0cc-0ad4-47c9-b74d-ac38b39f9f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>1d45521c-f8d1-452d-b27b-f110ca39afba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
