<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaOrgPublicoInscriptoObservaciones</name>
   <tag></tag>
   <elementGuidId>c350a8ba-84e4-42de-b9d9-16b11d224f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d473cfb-7bce-4e04-907e-7698e71e9d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>f07fa82e-552b-4aef-9203-0c1a350d0a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a3bd8dd2-d358-4819-9cf7-191557cb2713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8432b74c-a435-4c11-8a5a-c2035f2a97d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>8df4cd6a-9a02-4f27-ae0b-79e17d0a6ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>565eb0f7-0a36-47ca-980a-12fc78f534a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c2c72de-3efe-4194-bfd4-a17dfc34eb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>0b9255de-3c1c-45e6-8e0e-98647c9ae492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>d014e190-a233-4a2f-b651-4bafd6b9dd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[3]</value>
      <webElementGuid>b50ea4e7-b6ee-44cf-aece-8fbe71485449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>6887e96c-59c9-4dee-8b2f-915e45cbed4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>3c0a6e0a-376b-441f-93a8-890b54b01d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
