<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaDireccionLegalObservaciones</name>
   <tag></tag>
   <elementGuidId>e6c4e514-5947-4a47-ac86-29490dce1be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a37beb97-f912-47cf-b04d-0bee7a5baef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>4198c536-4aa6-43e8-96b8-c01788c8efaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a03cf447-a0cc-4e68-934d-1bde7ab79592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5aedeea7-68ff-461a-8159-89c50becafd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>5b3f8a0b-f042-4207-8325-37fdb02fbca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>284acb9b-7b78-44a7-858a-156025facce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32a059af-f883-4076-87c0-91cdf993f91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>fdf8a903-429c-4ede-964c-ddfbb8ce2150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>c848bcbb-21eb-4cfc-8e54-2b9d04afa46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[4]</value>
      <webElementGuid>13f9fe05-ad22-4d10-9c40-c59c81044c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>9fe2fce1-77ed-420d-87d7-3e055b29e33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$DireccionLegal$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_DireccionLegal_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>0600579a-27d0-4763-b0ef-cb275e26d277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
