<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modificar</name>
   <tag></tag>
   <elementGuidId>5f0aa049-41b6-40d3-9d4e-6e310c3fb8b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b2148f4-64e2-4d64-8307-57d368cbb723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir</value>
      <webElementGuid>a819e1c9-d527-4f90-b88e-95cd3f97b5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>3b388b78-516d-476a-a012-02824659c2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$UCPanelTodosLosTramites$lnkAceptarSalir','')</value>
      <webElementGuid>11e8b466-e5ee-4fcd-820e-2c51aca93be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificar</value>
      <webElementGuid>aba3dd89-ecff-4cd0-be04-fd1f13379ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir&quot;)</value>
      <webElementGuid>95b88622-0336-4a0a-8624-29979ddaee4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir']</value>
      <webElementGuid>9f160ee3-4b9d-48e0-833f-8165f408a3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_UCPanelTodosLosTramites_UPAsignarUsuarioModal']/div[2]/div[4]/div/a</value>
      <webElementGuid>fe1896c6-6fa0-4b1a-88a2-8490a48423ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Modificar')])[2]</value>
      <webElementGuid>83757260-5ff2-496b-89cf-a43e947f2841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignar usuario'])[2]/following::a[1]</value>
      <webElementGuid>4c94b94c-9b57-4c86-b3c1-07c954f84cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir a página:'])[1]/following::a[2]</value>
      <webElementGuid>04d60280-cd51-4808-83da-8dfb7c3ced97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/preceding::a[1]</value>
      <webElementGuid>54accb4d-3fd6-422e-9e1a-e8fe7ac237c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir al escritorio'])[1]/preceding::a[2]</value>
      <webElementGuid>83e40d61-f196-41f9-a001-c58906a718ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$UCPanelTodosLosTramites$lnkAceptarSalir','')&quot;)]</value>
      <webElementGuid>bfd72797-34e2-40dc-9d06-0936854bd241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>9a1e8848-6e35-487e-9d11-43e99924dad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_UCPanelTodosLosTramites_lnkAceptarSalir' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$UCPanelTodosLosTramites$lnkAceptarSalir&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Modificar' or . = 'Modificar')]</value>
      <webElementGuid>e4a64f76-9982-409d-a70b-cf9d9c083d80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
