<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SiguientePaso2</name>
   <tag></tag>
   <elementGuidId>cc6f71ca-218c-490f-a767-a8e21e28f530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ctl00_CPH1_lnkSiguientePaso2&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lnkSiguientePaso1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ctl00_CPH1_lnkSiguientePaso1' and (text() = 'Siguiente' or . = 'Siguiente')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a6cfeed-51a9-4f06-9abd-8af9704e0b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hyperClick();</value>
      <webElementGuid>66a29bcc-ce79-407b-8c82-7627142765d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lnkSiguientePaso1</value>
      <webElementGuid>e67293ef-8e18-4004-9af6-ace38a37226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>d55605e1-fc59-47e7-9652-639d5c51b0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$lnkSiguientePaso1','')</value>
      <webElementGuid>940923b4-1f21-474c-b4a3-276636919b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siguiente</value>
      <webElementGuid>c046300b-603a-4823-89d4-5203f05a0991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lnkSiguientePaso1&quot;)</value>
      <webElementGuid>cbb88984-e57e-4880-b45a-63a9a71dbff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_lnkSiguientePaso1']</value>
      <webElementGuid>748ca8e1-fe77-44d0-b972-f234ec922c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/section/div/div[12]/div/a[3]</value>
      <webElementGuid>beacde22-5300-40fe-88ab-4a32abc44229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Siguiente')]</value>
      <webElementGuid>5fbedb00-2278-4a44-8858-91b0a7ee6b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver al buscador'])[1]/following::a[2]</value>
      <webElementGuid>1cb7fba5-1c70-4409-bc46-2a50f5981384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones:'])[7]/following::a[3]</value>
      <webElementGuid>fd9a0d38-743d-46c6-9deb-544520974171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas'])[1]/preceding::a[1]</value>
      <webElementGuid>194989b2-451e-499c-ac22-75590ab3e357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máximo 8000 caracteres'])[1]/preceding::a[1]</value>
      <webElementGuid>4ed7ba82-da64-4977-b0e0-d97dbcd3a911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siguiente']/parent::*</value>
      <webElementGuid>1392b65f-951a-4221-9eee-000e9f1fa2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$lnkSiguientePaso1','')&quot;)]</value>
      <webElementGuid>0839a58a-eb93-4af8-8fac-5695a87c86a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>f2b4cab4-03c0-4446-afed-d64655479a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_lnkSiguientePaso1' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$lnkSiguientePaso1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Siguiente' or . = 'Siguiente')]</value>
      <webElementGuid>8cf8b9b1-716a-4809-8892-ae81c17849f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
