<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CUIT</name>
   <tag></tag>
   <elementGuidId>e06d5a6e-16cb-4830-9cdb-5f694e9c0a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ctl00$CPH1$UCPanelTodosLosTramites$txtBuscarCUIT' and @type = 'text' and @id = 'ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT' and @placeholder = 'Buscar por CUIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4d2959b-bedb-406a-9d22-0b252ac74649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCPanelTodosLosTramites$txtBuscarCUIT</value>
      <webElementGuid>69601eb8-66eb-41db-b362-8ce687693a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a92540d7-fc9c-4334-ae3e-5fd186137285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT</value>
      <webElementGuid>5dae9a04-4ab8-4f52-aa75-882bcf0272b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8bd6cff3-fa56-45f7-8aca-7087d7b7842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar por CUIT</value>
      <webElementGuid>9b925df8-8072-4a45-9d03-91e9e004b01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT&quot;)</value>
      <webElementGuid>95a9f6cb-0e89-4aec-b2d0-095431333739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT']</value>
      <webElementGuid>79315f90-46a3-4f1f-9d2d-c4e20544a3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_UCPanelTodosLosTramites_upPanelRIUPP']/div/div[2]/div/input</value>
      <webElementGuid>d5f1b42e-a5ab-4b73-8976-1adb380e46ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>61407f83-c315-4e9d-b2c3-fdbbc5fcc8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$UCPanelTodosLosTramites$txtBuscarCUIT' and @type = 'text' and @id = 'ctl00_CPH1_UCPanelTodosLosTramites_txtBuscarCUIT' and @placeholder = 'Buscar por CUIT']</value>
      <webElementGuid>042dbcd5-12a9-42f9-af80-767e85427d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
