<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkAsignar</name>
   <tag></tag>
   <elementGuidId>8de7c1fe-a709-4fa9-b3c9-af0fbd19e5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f266243-4611-4e4e-97d4-11974190db0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect</value>
      <webElementGuid>36db6f13-bdc2-4e93-a4fd-6e41dd35b01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>569aae25-5fac-491d-a55d-97d6974d0242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCPanelTodosLosTramites$gvTramites$ctl02$chkSelect</value>
      <webElementGuid>5e149c44-6098-4fe4-b4a1-5560102d92c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$UCPanelTodosLosTramites$gvTramites$ctl02$chkSelect\',\'\')', 0)</value>
      <webElementGuid>6f0d65a5-c78e-4e0a-b633-ffe354847c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect&quot;)</value>
      <webElementGuid>6d6e80d1-e166-43a5-93d5-2ab3f2b5920f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect']</value>
      <webElementGuid>e8179580-276b-4796-9451-185c90718412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites']/tbody/tr[2]/td[7]/div/input</value>
      <webElementGuid>fe1b7ab4-fe8e-4228-a8ff-c50a73eb3abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/input</value>
      <webElementGuid>dbdd1456-e3d3-4fc5-b852-0052877b3a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_chkSelect' and @type = 'checkbox' and @name = 'ctl00$CPH1$UCPanelTodosLosTramites$gvTramites$ctl02$chkSelect']</value>
      <webElementGuid>b146c5b6-1051-40b3-9a22-71af43b35abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
