<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_msjEvaluacinCAP</name>
   <tag></tag>
   <elementGuidId>852f4827-c360-4805-a7e7-9c0f265d95ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ctl00_CPH1_divMensajeExito&quot;]/div/h4/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_CPH1_lblTitulo' and (text() = 'Evaluación RIUPP finalizada' or . = 'Evaluación RIUPP finalizada')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_lblTitulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9a89646-6de5-4af0-ac7e-27b64344323e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_lblTitulo</value>
      <webElementGuid>77305374-8fe9-455c-b09d-a9d82d18605d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0561ba54-dc92-42cc-b04b-62e0e334425b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Evaluación RIUPP finalizada</value>
      <webElementGuid>35a6a188-fda9-4482-a067-5ce64199dc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_lblTitulo&quot;)</value>
      <webElementGuid>82d210cd-0915-4b08-8cf0-65c3934dcb06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_lblTitulo']</value>
      <webElementGuid>d1622dc9-5dfe-4ea0-aa8a-f203417959b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_divMensajeExito']/div/h4/span</value>
      <webElementGuid>23f4f5d3-b460-4538-98b8-7608155102f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/following::span[3]</value>
      <webElementGuid>b1b536e7-2ff2-4278-9405-22ef395811e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver al escritorio'])[1]/preceding::span[2]</value>
      <webElementGuid>84178081-fa56-41a1-a0b8-1a62b6bb94e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Evaluación RIUPP finalizada']/parent::*</value>
      <webElementGuid>13ca780f-fc0d-4227-b09d-6548e64cbbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/span</value>
      <webElementGuid>064945b7-877d-454f-9776-078ad68e1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_lblTitulo' and (text() = 'Evaluación RIUPP finalizada' or . = 'Evaluación RIUPP finalizada')]</value>
      <webElementGuid>96723911-6de3-43e9-b8ea-3466ed06d19c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
