<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_estadoTramite</name>
   <tag></tag>
   <elementGuidId>52ba001e-4964-4942-ae3f-ff5c5da4b864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50638f19-197c-48c0-b4b1-35911fb85ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado</value>
      <webElementGuid>7f077a18-26ee-4b96-9ae9-a374b9d73bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En evaluación CAP</value>
      <webElementGuid>9eff646a-f526-4c40-9178-b61608fb80a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado&quot;)</value>
      <webElementGuid>c11887f9-163b-4a8c-8b44-32d4ca33e599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado']</value>
      <webElementGuid>aca98606-985c-4f02-8290-f95325b7c939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_UCPanelTodosLosTramites_gvTramites']/tbody/tr[2]/td[6]/span</value>
      <webElementGuid>f70c69da-99d0-4d17-b22a-6b7a1e609b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Francisco Ciorciari'])[2]/following::span[1]</value>
      <webElementGuid>3e4d13bb-62a0-4bff-8ea5-5a167d27b53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIENTIFICA PARQUE CENTENARIO S.R.L.'])[2]/following::span[3]</value>
      <webElementGuid>992e4644-05dc-4690-986a-379ba6785c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignar'])[2]/preceding::span[2]</value>
      <webElementGuid>58bc411d-4e91-44c7-adda-013419a199c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas'])[2]/preceding::span[2]</value>
      <webElementGuid>8d4afa3a-85c1-46f0-ba4d-3eda816b45ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/table/tbody/tr[2]/td[6]/span</value>
      <webElementGuid>63b146de-b338-4b0f-a7f5-94387395e375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_UCPanelTodosLosTramites_gvTramites_ctl02_lblEstado' and (text() = 'En evaluación CAP' or . = 'En evaluación CAP')]</value>
      <webElementGuid>56a32711-d195-4112-966b-4a3dc4d50da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
