<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Agregar</name>
   <tag></tag>
   <elementGuidId>59bcefd1-0257-4acf-a8f8-0809c4740943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_btnAgregarEvaluador</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_btnAgregarEvaluador']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>689e0185-027b-478c-bf37-6167211fd2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:AgregarEvaluador();return false;</value>
      <webElementGuid>6320bd19-038e-49f5-bc0e-a01f86d94936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_btnAgregarEvaluador</value>
      <webElementGuid>698ea90c-0a6a-4f7c-bc8b-68d645b3d0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right</value>
      <webElementGuid>12ab2909-3a27-4192-88ab-10f615efdc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$CPH1$btnAgregarEvaluador','')</value>
      <webElementGuid>f3a55044-2298-43d2-978d-0fd9f1bc4108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>ee5e6f02-bf84-46d8-ab28-50e211606ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_btnAgregarEvaluador&quot;)</value>
      <webElementGuid>ac0e2629-bf0d-41e8-a7c8-fd3c6f614320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_btnAgregarEvaluador']</value>
      <webElementGuid>86b489f1-db7a-4556-9cfb-6d094e7ab9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upEvaluadores']/div[2]/div/a</value>
      <webElementGuid>f43797ab-bf87-4df4-93a0-b2915071342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agregar')]</value>
      <webElementGuid>64593161-32fe-4c81-acb9-1d9552cbcd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANIEL BECERRA MACELLARI'])[1]/following::a[1]</value>
      <webElementGuid>d3067be5-26a2-4447-9960-241d9db4e022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lucia Alvarez Vera'])[1]/following::a[1]</value>
      <webElementGuid>5fd98d2a-ad4d-4447-a35a-360522f8567b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad de evaluadores considerados:'])[1]/preceding::a[1]</value>
      <webElementGuid>78145d05-cdc7-462a-968d-2f0de4348391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifique que la cantidad de evaluadores considerados haya sido seleccionada'])[1]/preceding::a[1]</value>
      <webElementGuid>8acaa907-96ed-4d8c-9e75-c3752e06d80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar']/parent::*</value>
      <webElementGuid>f0740fd6-4a28-42f0-a849-0113f82a916a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$CPH1$btnAgregarEvaluador','')&quot;)]</value>
      <webElementGuid>e20bd8d1-a529-4fd3-9e8c-2bb0030eb3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/a</value>
      <webElementGuid>aa3578de-1e9b-4e0f-90ec-13d36c6b7cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_btnAgregarEvaluador' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$CPH1$btnAgregarEvaluador&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Agregar' or . = 'Agregar')]</value>
      <webElementGuid>2264819f-ef23-4bca-b01d-dbb49afb3bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
