<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CompletarDatos</name>
   <tag></tag>
   <elementGuidId>a81f7317-bff3-40f3-9c8d-35bd375d0411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionIndice17_hlDatos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_seccionIndice17_hlDatos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3263468c-3530-4886-8395-f83aefdb5808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionIndice17_hlDatos</value>
      <webElementGuid>08be2965-9f6c-4a09-9a66-d3221917887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>488c0715-d5f4-4112-8e3b-7cde5d9bc1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>IngresarEvaluadores.aspx?qs=hc9oU876wO310azy7/0PRkr9bsw8jxrV3Z3Fy5CqSIl|LBiqDURd518T6AE5/YAcdYjXKrz|40eatJx9RWiYruxGEknSwyoJELnNZfaJcA7nc|gvW6YqkQ==</value>
      <webElementGuid>ed2ea9c3-0212-46af-bc3f-f414d4d2e637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar datos</value>
      <webElementGuid>43420d7e-1eb1-4970-8cda-580e08fd43fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionIndice17_hlDatos&quot;)</value>
      <webElementGuid>54da271c-b2db-4e96-a216-f2de08fbe1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_seccionIndice17_hlDatos']</value>
      <webElementGuid>1afd1f62-8ee7-40be-84fa-4a623f08a8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr[14]/td[2]/span[2]/a</value>
      <webElementGuid>c0dad851-b67c-4de6-b0d0-1a5f5475ebd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Completar datos')])[3]</value>
      <webElementGuid>2a227625-5402-45e6-92ee-3b5fc3dd93b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos obligatorios'])[3]/following::a[1]</value>
      <webElementGuid>91e94faa-e6e2-4dc1-8972-12791a91f10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[14]/preceding::a[1]</value>
      <webElementGuid>bc0cf570-a5cf-40a4-840d-b29e7df8c05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'IngresarEvaluadores.aspx?qs=hc9oU876wO310azy7/0PRkr9bsw8jxrV3Z3Fy5CqSIl|LBiqDURd518T6AE5/YAcdYjXKrz|40eatJx9RWiYruxGEknSwyoJELnNZfaJcA7nc|gvW6YqkQ==')]</value>
      <webElementGuid>9a431eb1-a067-4c4b-809a-afecfccd4ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/span[2]/a</value>
      <webElementGuid>e06892c1-245b-4be0-9854-ed3a9c259947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_seccionIndice17_hlDatos' and @href = 'IngresarEvaluadores.aspx?qs=hc9oU876wO310azy7/0PRkr9bsw8jxrV3Z3Fy5CqSIl|LBiqDURd518T6AE5/YAcdYjXKrz|40eatJx9RWiYruxGEknSwyoJELnNZfaJcA7nc|gvW6YqkQ==' and (text() = 'Completar datos' or . = 'Completar datos')]</value>
      <webElementGuid>86963e17-3054-45b3-8936-3895922c943b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
