<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reparticion</name>
   <tag></tag>
   <elementGuidId>917b1d73-0311-4bb7-aa68-616447ddbee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a269e1f-e52e-4c96-9fc3-958a2e7dd6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucActoAdministrativoSADE$txtReparticion</value>
      <webElementGuid>323be38c-1cef-41d5-9ad4-23e884e0239d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53f1dd4e-7bc2-429f-9465-e05ff8388417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a095b327-0ea1-4b5c-86f8-a323ae5dae4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion</value>
      <webElementGuid>0a6b3141-dce5-4d71-948b-a71b7fe974c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>12b2b59b-80fa-423e-9dec-fd0b9e1a788c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion&quot;)</value>
      <webElementGuid>77f3bc2d-5c3a-410c-81f2-6f2bdd1fa1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion']</value>
      <webElementGuid>38c784e1-a5fd-4585-acee-b7627fe51380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaReparticion']/div/input</value>
      <webElementGuid>ad39527d-aa2f-424c-8940-ec9cef0a5207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>70b054e9-b483-4fe6-a72d-cc1304b9280d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ucActoAdministrativoSADE$txtReparticion' and @type = 'text' and @id = 'ctl00_CPH1_ucActoAdministrativoSADE_txtReparticion']</value>
      <webElementGuid>a7861b1e-c9f8-4aa8-9678-1b0e57a488dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
