<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numero</name>
   <tag></tag>
   <elementGuidId>5692e977-88e6-4323-b3f0-b4c99139403b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_ucActoAdministrativoSADE_txtNumero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_ucActoAdministrativoSADE_txtNumero']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8f4b2d4-1a6c-48ea-8e84-519ba493a9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$ucActoAdministrativoSADE$txtNumero</value>
      <webElementGuid>5f506bd4-758f-4957-8986-f8464ff8d83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4791c315-4c5b-4437-9b97-d50472d11abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a71da7d9-23fa-4c94-9689-63755d079107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_ucActoAdministrativoSADE_txtNumero</value>
      <webElementGuid>fb12d2e3-3e75-46c1-828f-0082151c42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ade584a7-3f3b-40ab-870d-bf1ed4af5d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return SoloNumeros(event)</value>
      <webElementGuid>052e304a-c729-4dcb-a597-fcb5a5d3a4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_ucActoAdministrativoSADE_txtNumero&quot;)</value>
      <webElementGuid>e9b0edd9-fed0-4485-b892-cfc61d76baf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_ucActoAdministrativoSADE_txtNumero']</value>
      <webElementGuid>d19f24c5-fa7f-48b6-abaa-4a2d850e22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivValidaNumero']/div/input</value>
      <webElementGuid>9639370a-dc7b-4caf-ac6d-eeac4e175a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>ef962696-f32e-4914-afe9-bc2a4c8605ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$ucActoAdministrativoSADE$txtNumero' and @type = 'text' and @id = 'ctl00_CPH1_ucActoAdministrativoSADE_txtNumero']</value>
      <webElementGuid>ffefc405-3431-494e-be11-e989e2f60642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
