<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CompletarDatos</name>
   <tag></tag>
   <elementGuidId>b2571891-d709-4c67-8f4f-95f1652d0610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_seccionIndice7_hlDatos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_CPH1_seccionIndice7_hlDatos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>babe3e42-2b30-43d4-b53a-e6d712438476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_seccionIndice7_hlDatos</value>
      <webElementGuid>9b1a0595-2852-44d7-83b2-e712abfafd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkazul</value>
      <webElementGuid>54c925ac-76d2-488b-a52c-d5984c4b8f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2HcFnEQd1tDpnewh1oJ16aFvuiKUFt|/egxk24sDLm6tw73UU2kve6NT</value>
      <webElementGuid>e8c4135d-24e5-427b-a71f-dbd48be35861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completar datos</value>
      <webElementGuid>1e44fe39-7543-4ab7-8fab-11978f825c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_seccionIndice7_hlDatos&quot;)</value>
      <webElementGuid>20ea515e-6063-4cf4-8108-f98f6ebc363a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_CPH1_seccionIndice7_hlDatos']</value>
      <webElementGuid>4d7d2e42-2c6b-48dd-b8a5-bb169c98b9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[6]/table/tbody/tr[7]/td[2]/span[2]/a</value>
      <webElementGuid>b38a4bc2-c066-4376-8e0a-3567fe44ead7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Completar datos')]</value>
      <webElementGuid>f46fbbc1-a205-4474-afe9-3113382e76bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos obligatorios'])[2]/following::a[1]</value>
      <webElementGuid>3929af18-e6bd-4766-8aa7-f2e7a9a83507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción resumida de la información que se debe completar en este índice.'])[7]/preceding::a[1]</value>
      <webElementGuid>41f5cc7c-3d63-4191-ba80-932682db3b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2HcFnEQd1tDpnewh1oJ16aFvuiKUFt|/egxk24sDLm6tw73UU2kve6NT')]</value>
      <webElementGuid>5e771fb2-2eff-466b-b86d-fb2b4980637d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/span[2]/a</value>
      <webElementGuid>89d2feeb-aca3-4256-9cb3-180ea0c5a7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_CPH1_seccionIndice7_hlDatos' and @href = 'IngresarActoAdministrativoSADE.aspx?qs=BQoBkoMoEhyTN8YcHViQeQrbqnT6W1odvwATuxog2HcFnEQd1tDpnewh1oJ16aFvuiKUFt|/egxk24sDLm6tw73UU2kve6NT' and (text() = 'Completar datos' or . = 'Completar datos')]</value>
      <webElementGuid>9f5b73b6-9701-4948-b545-219530363c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
