<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rarioDesdePerfeccionamientoDocumento</name>
   <tag></tag>
   <elementGuidId>cdc96871-994b-4e65-93a8-c9e2fc00ef98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>784d5d73-90f7-4deb-97ea-aa446b986e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento</value>
      <webElementGuid>8e278e0c-8854-4fb0-8372-e207032e0573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9784987f-888d-4218-a411-4f272d09882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$UCDatosInformacionContrato$rdbGroup</value>
      <webElementGuid>31298562-8b08-4bec-946c-4fef9a67643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdbDesdePerfeccionamiento</value>
      <webElementGuid>b3af802a-7969-4651-8a56-0bf486feef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>68993281-7e04-4386-8ead-deb7443b90cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento&quot;)</value>
      <webElementGuid>eeeec49c-828c-4946-a0fa-daea024673ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento']</value>
      <webElementGuid>6bc40303-03ec-4ff4-9995-3ae00634f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[13]/table/tbody/tr/td/input</value>
      <webElementGuid>701e403d-dc46-4981-82d1-8c94dcbd1b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr/td/input</value>
      <webElementGuid>7eac3c63-b00f-439c-ab0a-9e26c8d115e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_UCDatosInformacionContrato_rdbDesdePerfeccionamiento' and @type = 'radio' and @name = 'ctl00$CPH1$UCDatosInformacionContrato$rdbGroup' and @checked = 'checked']</value>
      <webElementGuid>d008185d-6b75-48ad-ac61-817f0521a265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
