<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fecha</name>
   <tag></tag>
   <elementGuidId>0bb19aaf-3791-4404-8f77-76310c46b791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_CPH1_Constitucion_devDteFecha_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_Constitucion_devDteFecha_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c2d6fc0-0365-4039-ae72-4150a865a076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_Constitucion_devDteFecha_B-1Img</value>
      <webElementGuid>1e0ee9cd-0e33-4f44-a12c-b76e7e4b5066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=2_73</value>
      <webElementGuid>c502ef9d-33e6-4232-8d33-45001b691f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>21722f7c-2a59-442d-86d9-0c4f86cfdddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_Constitucion_devDteFecha_B-1Img&quot;)</value>
      <webElementGuid>5533b7f4-025b-4a02-8286-6b598a4a6d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_CPH1_Constitucion_devDteFecha_B-1Img']</value>
      <webElementGuid>a96d7018-24d2-49f6-9ea4-3f6bcfa28046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ctl00_CPH1_Constitucion_devDteFecha_B-1']/table/tbody/tr/td/img</value>
      <webElementGuid>04aae316-1281-4f48-8f4f-8d37073fb6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>5ce1e63b-6ea2-470b-af4b-f68c4a040b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>6d596108-ebc4-4bcb-8228-2512ee446e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_CPH1_Constitucion_devDteFecha_B-1Img' and @src = '/DXR.axd?r=2_73' and @alt = 'v']</value>
      <webElementGuid>2aa193d6-11ad-4ac7-bc1d-f428748272f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
