<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calle</name>
   <tag></tag>
   <elementGuidId>52a2a64c-81ed-4d48-90ad-630afd74ea10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionLegal_txtCalle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionLegal_txtCalle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>900ec3c8-ae4f-440c-b400-bf1e3f01d701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionLegal$txtCalle</value>
      <webElementGuid>b41a9393-aa51-4ccb-9097-ec2fe7a6bc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>549bca80-dad1-420f-8b2e-1414f9942516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>490ccf80-1a0f-41db-9fbd-7ec48e2cc9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionLegal_txtCalle</value>
      <webElementGuid>49d3f047-fb34-48b9-8eef-7bced739227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>35870dc7-9be6-4afa-968b-3c52499a2ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>onblurDomicilio(this);</value>
      <webElementGuid>b16d455f-c24a-4904-a601-c4bf9f06ab77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionLegal_txtCalle&quot;)</value>
      <webElementGuid>78d8bd90-ca08-46ce-bc2b-c8f4a87d3757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionLegal_txtCalle']</value>
      <webElementGuid>7cd5502e-800f-4143-bc38-5d819f61010e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DireccionLegal_DivCalle']/input</value>
      <webElementGuid>3c9b85bf-0347-4bcb-99bd-6ffe9f26e730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>7537c5ee-dfd7-48b7-84a0-baff03830777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DireccionLegal$txtCalle' and @type = 'text' and @id = 'ctl00_CPH1_DireccionLegal_txtCalle']</value>
      <webElementGuid>a3eae540-4151-4174-af3d-0dab9828b95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
