<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de fax</name>
   <tag></tag>
   <elementGuidId>75cbe60c-3364-4038-9553-ca6388693a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionLegal_txtNumeroFax']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionLegal_txtNumeroFax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17d730f7-41d8-458f-b596-e964b0df3308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionLegal$txtNumeroFax</value>
      <webElementGuid>de149861-3ff3-4797-970e-f9912a4493e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e914b5fc-dc8d-40a1-877e-115f1031558a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1056c1a5-cfec-4c7d-b59d-129414a70563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionLegal_txtNumeroFax</value>
      <webElementGuid>11e194ea-5cf1-4ced-993f-ccae769a547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e6e1469c-b3d3-4073-a6bd-d28efd35b505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NumeroTelefonoFax(event)</value>
      <webElementGuid>a031db28-55c7-4563-bfc8-8a57fead8724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>onblurDomicilio(this);</value>
      <webElementGuid>2a8aec03-546f-4a14-a0d8-d443cedc2276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionLegal_txtNumeroFax&quot;)</value>
      <webElementGuid>7a639663-ed45-435e-92d3-393fe5c375f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionLegal_txtNumeroFax']</value>
      <webElementGuid>774c8e87-027e-4aae-bd97-8512435e8758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DireccionLegal_DivNumeroFax']/input</value>
      <webElementGuid>f6972d50-f934-4695-b2b9-bcdb043b3095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/input</value>
      <webElementGuid>993f6209-f48a-460c-858f-c2679ec71758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DireccionLegal$txtNumeroFax' and @type = 'text' and @id = 'ctl00_CPH1_DireccionLegal_txtNumeroFax']</value>
      <webElementGuid>7f960ea5-a392-45a9-a24b-4659c19fa44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
