<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calle_ctl00CPH1DireccionCABAtxtCalle</name>
   <tag></tag>
   <elementGuidId>13444639-3546-42e2-8a63-1d76107283c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionCABA_txtCalle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionCABA_txtCalle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dcecca6-5ec3-4bbe-b03b-30782b459738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionCABA$txtCalle</value>
      <webElementGuid>459eed37-3558-4766-aca4-76206eec587b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd198ce2-5017-42e3-a9b5-e8ea229afb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>dcaee0cc-b119-4389-b8c1-22696b3f3a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionCABA_txtCalle</value>
      <webElementGuid>c3b75d5b-3b63-47b5-b2f5-8c1a94e1d1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b8bed736-01ff-41ce-b65b-261c6a6c82c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionCABA_txtCalle&quot;)</value>
      <webElementGuid>f08ca4cf-97cb-4612-9d43-93190f39f478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionCABA_txtCalle']</value>
      <webElementGuid>2c0208f6-fe82-46b3-9ca7-d9eb44453c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DireccionCABA_DivCalle']/input</value>
      <webElementGuid>ccb77859-6268-4aa4-b6cd-6735b42b7cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>8eb4232b-c445-4836-b184-79decde95c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DireccionCABA$txtCalle' and @type = 'text' and @id = 'ctl00_CPH1_DireccionCABA_txtCalle']</value>
      <webElementGuid>561bc8d8-ef7f-4442-b1e1-9397dbb11d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
