<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNumero de IIBB</name>
   <tag></tag>
   <elementGuidId>f17ed758-6c91-4528-ae5e-8c54c2886e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_IngresoBruto_txtIIBB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_IngresoBruto_txtIIBB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fb61cd5-8961-46b2-a79c-484322efa2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$IngresoBruto$txtIIBB</value>
      <webElementGuid>bb82b665-47ac-4d6c-a93b-2368df014556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5f7072c-5ff3-40cb-af0c-20c83790ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>20202f68-9052-4633-b854-e870db438d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_IngresoBruto_txtIIBB</value>
      <webElementGuid>3091dc2a-3098-4e37-9e88-105b715abd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5e9c01a-d928-48ea-bad3-46a62c49ba10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_IngresoBruto_txtIIBB&quot;)</value>
      <webElementGuid>624f0bf1-30c5-4fe4-b4ba-5035e5bd6bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_IngresoBruto_txtIIBB']</value>
      <webElementGuid>121de6bc-aafe-4d23-bbf4-16f1ecdd0f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_IngresoBruto_DivIIBB']/input</value>
      <webElementGuid>bc6fb176-1329-4241-be99-3b462476d710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>b566e4bc-1000-46a5-a5d1-4d363bfc0b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$IngresoBruto$txtIIBB' and @type = 'text' and @id = 'ctl00_CPH1_IngresoBruto_txtIIBB']</value>
      <webElementGuid>a13e91ba-6462-490a-a054-efe0726a13be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
