<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numero de inscripcion</name>
   <tag></tag>
   <elementGuidId>aa673bbb-588c-4cc8-97b0-dfdb82d52f51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f0841d3-037f-45fc-bee9-9d0b3cb47ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$OrganismoPublicoInscripto$txtNumeroInscripcion</value>
      <webElementGuid>66b60424-9fa0-4872-99f7-474c44c6a303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c52c4fae-0c5d-48eb-b0d3-f00d9abacc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ba7a400a-4ceb-490f-9124-04281679c2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion</value>
      <webElementGuid>f1e9520d-0f8d-4908-b544-86395ed39932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af965199-6403-4be6-a2e6-27c5f331d8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion&quot;)</value>
      <webElementGuid>9a1eb8f2-c528-48b3-8b08-74e4fd07ebcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion']</value>
      <webElementGuid>e20d4f29-b080-4a37-9b73-4d71acf5558b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_OrganismoPublicoInscripto_DivNumeroInscripcion']/input</value>
      <webElementGuid>91b35bd6-cf2d-4663-ba0f-6669df520582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>428337dc-fae4-42b4-bf85-ffbb428a3703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$OrganismoPublicoInscripto$txtNumeroInscripcion' and @type = 'text' and @id = 'ctl00_CPH1_OrganismoPublicoInscripto_txtNumeroInscripcion']</value>
      <webElementGuid>367d2d4c-c76e-4152-8083-f710cfc600e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
