<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputApellido</name>
   <tag></tag>
   <elementGuidId>e8a24024-19e3-40f3-83e1-95f28bf1fc2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DatosPersonaFisica_txtApellido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DatosPersonaFisica_txtApellido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f9080a1-b2ae-4b61-ad86-3babd2c3d551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DatosPersonaFisica$txtApellido</value>
      <webElementGuid>0918f2a9-bfb6-439f-b266-3be221aebbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>770a1c8f-5962-4eed-a27a-11f170ee7d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ad423399-f85c-4145-a081-a59d88980741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DatosPersonaFisica_txtApellido</value>
      <webElementGuid>41093ee4-cf22-478e-9980-dc8b2a801191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cc71dc4-395d-471f-afd7-8fbd44eaccc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DatosPersonaFisica_txtApellido&quot;)</value>
      <webElementGuid>cf3646ed-ca20-4e53-bc1d-5c7ccfe5b375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DatosPersonaFisica_txtApellido']</value>
      <webElementGuid>0f1287b4-dec1-4de4-8740-87b4bb5b7f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DatosPersonaFisica_DivApellido']/input</value>
      <webElementGuid>1f90f6b8-5680-4800-87d5-cdc041462f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>d3cf884e-9117-4fe6-88cb-56fd29412292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DatosPersonaFisica$txtApellido' and @type = 'text' and @id = 'ctl00_CPH1_DatosPersonaFisica_txtApellido']</value>
      <webElementGuid>66e1bc8a-06ac-479c-8629-942696e453f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
