<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_ctl00CPH1DireccionCABAtxtNumero</name>
   <tag></tag>
   <elementGuidId>743b8b13-7092-48ba-8a2b-e1051c4945d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DireccionCABA_txtNumero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DireccionCABA_txtNumero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>096de0cd-a8a8-49be-9187-27f5854c96da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DireccionCABA$txtNumero</value>
      <webElementGuid>962f2a59-de47-4652-a4c4-48fa2b04560b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>721a5dcd-9dec-4362-9e54-355e7fdd4c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3ef9bdb5-c1e6-4e05-8c7d-249812dcfdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DireccionCABA_txtNumero</value>
      <webElementGuid>4fa647fd-7189-4a0e-8041-de4ca0e57924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4a563a0-6914-4bb2-81e4-3cab775a3217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DireccionCABA_txtNumero&quot;)</value>
      <webElementGuid>168f6af8-08b8-4f99-9d2e-3d8cf1180d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DireccionCABA_txtNumero']</value>
      <webElementGuid>b485e2ed-6c3b-4f48-af40-67a90608f2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_DireccionCABA_DivNumero']/input</value>
      <webElementGuid>f3c1cc5c-7974-46c6-8fbe-0463efcf16d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>28eb8788-512e-4f75-b26e-ae73e388596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DireccionCABA$txtNumero' and @type = 'text' and @id = 'ctl00_CPH1_DireccionCABA_txtNumero']</value>
      <webElementGuid>8335485d-b998-4475-89af-76f5472727c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
