<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeIngresarImputacionPresupuestaria</name>
   <tag></tag>
   <elementGuidId>5353582c-d29e-4e66-9ba8-1858e5134b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_PopUpIngresarImputacion_CIF-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_CPH1_PopUpIngresarImputacion_CIF-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>92109580-7cea-4cf5-9414-a53e21ef3486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_PopUpIngresarImputacion_CIF-1</value>
      <webElementGuid>09387650-d91a-4a2e-9651-19e3b9221c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ADJ/IngresarImputacionPresupuestariaCuotas.aspx</value>
      <webElementGuid>9561dca2-8f4b-4861-8c5a-741ead330e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ae75a9a8-b340-4937-b5ce-8c0ff84b0c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>74f6a3d3-284b-4db8-9520-d6f10f45ad33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_PopUpIngresarImputacion_CIF-1&quot;)</value>
      <webElementGuid>ede126d6-f91f-42e1-90d3-e2bb06cf26c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ctl00_CPH1_PopUpIngresarImputacion_CIF-1']</value>
      <webElementGuid>b7876ce8-f9ae-4a9a-ab0a-2af4dcda3e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_PopUpIngresarImputacion_CIFD-1']/iframe</value>
      <webElementGuid>fca61697-a62a-48f3-997e-074794d0bc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar imputación presupuestaria'])[2]/following::iframe[1]</value>
      <webElementGuid>605c9554-be14-4f8c-b01a-e29cc3755225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/following::iframe[1]</value>
      <webElementGuid>847eb436-fad1-4955-aa26-92d3c8590b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f50f688b-90c0-4b16-98e9-f20c276f7ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ctl00_CPH1_PopUpIngresarImputacion_CIF-1' and @src = '/ADJ/IngresarImputacionPresupuestariaCuotas.aspx']</value>
      <webElementGuid>554317b7-a932-4b8c-8b99-a364fd47269a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
