<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DatosUsuariotxtClave</name>
   <tag></tag>
   <elementGuidId>a2963630-47ae-4940-b589-6c11fe1b2f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_DatosUsuario_txtClave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_DatosUsuario_txtClave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcb29ff7-d5c7-45a7-a485-28e9fa7e4778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$DatosUsuario$txtClave</value>
      <webElementGuid>8b936d13-88ef-49b6-88dd-68b83178c4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fe3e09d6-c1c2-4608-8896-2905287093b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_DatosUsuario_txtClave</value>
      <webElementGuid>74388d19-de07-4d72-946d-5d299187d301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajas</value>
      <webElementGuid>da16df66-9d37-4815-a766-bf72a1c174a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_DatosUsuario_txtClave&quot;)</value>
      <webElementGuid>6a6627f0-a42d-4cac-8c33-654b0829f1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_DatosUsuario_txtClave']</value>
      <webElementGuid>a7036c09-6679-4cb9-aa4e-b04dd3d47000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenido_tablas']/div[17]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>c8371218-6caa-49af-b0ce-dca12389797a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>2b234013-009a-41eb-b5ee-f995ec6bfe62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$DatosUsuario$txtClave' and @type = 'password' and @id = 'ctl00_CPH1_DatosUsuario_txtClave']</value>
      <webElementGuid>9af4bf6b-c53a-4101-8aa6-2be8c8e8eb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
