<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FechaImputacin</name>
   <tag></tag>
   <elementGuidId>cdbb20a0-c675-4e1a-bd98-d785d4231796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'dxedteFechaImputacion_I')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>526b6aee-76f4-4613-a8ab-1bd80a459ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea </value>
      <webElementGuid>1d90cde6-0f08-4b2f-a539-cd0bee69ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion_I</value>
      <webElementGuid>ba9b8aa9-4356-4e37-9934-d0222b468c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$1d3c92a1-1bfe-4700-adb0-d8b58f5e4733$dxedteFechaImputacion</value>
      <webElementGuid>2fd925b6-797e-442d-a77e-e598788f833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion')</value>
      <webElementGuid>b3e2a374-7805-458c-bc49-9b2be53f95dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion')</value>
      <webElementGuid>2bfcd71f-809d-4178-b065-2c249e461e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion')</value>
      <webElementGuid>b7e8424d-5082-44fa-b21d-003a5d0e1041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion', event)</value>
      <webElementGuid>bf9beb8a-aee9-4eb7-8795-a880f9a384f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>649ccefa-4aac-46f4-aab8-af7947bf88ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2e86c2b-1a23-4a3b-90b7-5a1fb0ce85d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c1a551f-1561-43b6-98c8-f438ea073d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion_I&quot;)</value>
      <webElementGuid>144682c6-446a-4b9c-84ab-c3e1a70686aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BAC/Page_BAC - Adjudicación/iframePopUpIngresarImputacion</value>
      <webElementGuid>c8c92b92-953c-413c-a431-5537cf543b76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion_I']</value>
      <webElementGuid>923c82c0-4399-47ad-88d1-2ed96c6a042b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion']/tbody/tr/td/input</value>
      <webElementGuid>83f30c8e-1026-4cf2-8bb0-03a37aa93528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c6c45a17-7a9d-4926-8b2c-fab36254673a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_CPH1_1d3c92a1-1bfe-4700-adb0-d8b58f5e4733_dxedteFechaImputacion_I' and @name = 'ctl00$CPH1$1d3c92a1-1bfe-4700-adb0-d8b58f5e4733$dxedteFechaImputacion' and @type = 'text']</value>
      <webElementGuid>c07b4f20-8df2-42eb-85fc-b2debe4b9f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
