<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SolicitudEnviadaExitosamente</name>
   <tag></tag>
   <elementGuidId>ed694359-0fd1-425b-a262-665e320e2911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_msjExito</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_CPH1_msjExito']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68cf1125-a13f-4298-b447-c9752c54363c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_msjExito</value>
      <webElementGuid>2d783d57-d62f-4a3c-814d-15497d356571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>e794ea5d-1e6a-41ef-8646-efb7465302a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La Solicitud fue Enviada Satisfactoriamente. Se ha notificado a los Analistas. </value>
      <webElementGuid>29905d28-4f62-46c8-936b-965f4ce9bf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_msjExito&quot;)</value>
      <webElementGuid>7c223f54-e455-4a51-9229-2e66fd02a737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_CPH1_msjExito']</value>
      <webElementGuid>0bd775df-fec3-4fce-8b0d-38a444212d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_divExito']/span</value>
      <webElementGuid>201a9560-3a00-47fb-9088-3e6a83580111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/following::span[4]</value>
      <webElementGuid>8c07bbf0-426e-4121-a290-4b0938c20c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi escritorio'])[2]/preceding::span[1]</value>
      <webElementGuid>b7ab41fe-492c-4929-9f4c-2fb6657a026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bandeja personal'])[1]/preceding::span[1]</value>
      <webElementGuid>4f11149f-14ab-4f45-9b1c-16a7f4c8c0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='La Solicitud fue Enviada Satisfactoriamente. Se ha notificado a los Analistas.']/parent::*</value>
      <webElementGuid>dadad58d-c24f-40bd-ac15-e4fd026fa8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/span</value>
      <webElementGuid>2e59f72f-0f5b-4909-8b6e-c74c84781786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_CPH1_msjExito' and (text() = 'La Solicitud fue Enviada Satisfactoriamente. Se ha notificado a los Analistas. ' or . = 'La Solicitud fue Enviada Satisfactoriamente. Se ha notificado a los Analistas. ')]</value>
      <webElementGuid>a63879da-4263-4792-9ee9-86b0a6b795fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
