<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNumeroObraPublica</name>
   <tag></tag>
   <elementGuidId>f6332200-f3e6-4bb7-9867-169aa656acdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_CPH1_txtNumeroObraPublica']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_txtNumeroObraPublica</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b3119f3-318e-444e-a9e3-693e1dcf4604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$txtNumeroObraPublica</value>
      <webElementGuid>7dc5bb8d-010d-415a-b39b-22bc4265d84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d845bbc5-df90-4c04-8244-aa3e9d7aea94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>016d994d-4ce2-4638-8947-88ce21c5d7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_txtNumeroObraPublica</value>
      <webElementGuid>1f49322b-ad54-4af7-b6b4-3fe01dc703ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1ce19fc4-cc91-46ee-ada4-8c38ffc86b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_txtNumeroObraPublica&quot;)</value>
      <webElementGuid>a8557408-8deb-4a03-b5be-9dce6a3ad936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_CPH1_txtNumeroObraPublica']</value>
      <webElementGuid>e721a11e-315f-4a14-bfa7-89e2266d8965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_CPH1_upModal']/div/div[4]/input</value>
      <webElementGuid>79d2e510-b42c-4c56-8807-3f4d331ac8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9b11e19b-03ef-4d28-b896-24725437c1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$CPH1$txtNumeroObraPublica' and @type = 'text' and @id = 'ctl00_CPH1_txtNumeroObraPublica']</value>
      <webElementGuid>0cce0983-e6bb-4593-b6b2-f8121133e152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
