<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrganismoPublicoTxt</name>
   <tag></tag>
   <elementGuidId>929e05ec-5f5d-4be9-831b-0e284fa132df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2c65dc84-040c-426f-b6ab-be36a896cb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>b8b60b26-8e20-492f-9e1b-12db91788133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>da61d152-b1e8-4611-9997-0881869658c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4782eccd-a157-417c-9bbc-8ba78b31cbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>96d9f2ae-e1ab-4b08-bcfa-ee4cfc249e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>1a37b70b-740d-427f-8d5e-70f0a520a2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff2ecad2-70bc-47b9-bfc9-1535d1b773cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>6f4be24c-9a47-4f5b-b8e4-8804be642542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>e52e2d27-0202-457a-8e24-a543dc143999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[4]</value>
      <webElementGuid>157c3aab-bed0-4bb2-bac1-78d6dd59c19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>8f12b9b9-85f9-4e98-914f-cc30f3a43578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$OrganismoPublicoInscripto$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_OrganismoPublicoInscripto_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>68d813da-6e80-461e-ba3f-60bed01d9227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
