<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IngresosBrutosTxt</name>
   <tag></tag>
   <elementGuidId>d59b9bf3-260e-4c1b-92b3-bce4dccfb938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8e7a5e78-7b8a-49a2-8063-6bba25d00dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>17212b64-3ddf-4e2d-945a-fc0499438792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>42c75f11-f39f-40af-817a-df8182070b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>12c986de-162b-4e46-8a79-05fc6698c239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>d70f66a8-4946-4778-8c2f-9e03759e7f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>ca7e8c44-1d8d-4263-8737-a1c61e7f8476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7318199-eb93-417f-8d0a-98a3e397166f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>411b971a-a8d0-4748-8d1f-2447757fd7f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>2fddeee2-33c1-4a7a-aa2e-7dc9a5156fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[2]</value>
      <webElementGuid>c0c798e7-d4d0-4c21-957d-3dca9e972529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>658639f8-45eb-488e-bdfb-8ed4d3bcc481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$IngresoBruto$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_IngresoBruto_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text']</value>
      <webElementGuid>8fdc2247-a1bb-46f5-9b83-c0c34f3c2650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
