<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConstitucionTxt</name>
   <tag></tag>
   <elementGuidId>1824b07f-e05e-48c6-8784-f900a4b16f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f65025d5-9ecf-4b35-a6e6-aac078749739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones</value>
      <webElementGuid>02457b2f-777c-47c7-959a-95673d61f522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3ffbb137-ba1c-4a55-9788-320490ce7bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6b3829a0-52db-4a52-af63-3cde78c331d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones\',\'\')', 0)</value>
      <webElementGuid>646a46d2-9557-4c5d-8ce7-984000c5fef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones</value>
      <webElementGuid>881d195a-0c34-40d2-8e73-e78e461ac9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca2dbcb0-407e-4ef2-860d-a12b3c5f5ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21xxx</value>
      <webElementGuid>0b6c9adb-9f43-41d0-ac31-f809cba7030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones&quot;)</value>
      <webElementGuid>0b4320e6-c095-49f7-bf21-156703880b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones']</value>
      <webElementGuid>ed26896b-f291-487c-8eba-ffa33fc37067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divObservaciones']/textarea)[3]</value>
      <webElementGuid>100cff6a-da14-4561-ba32-9f93a6841924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones:'])[3]/following::textarea[1]</value>
      <webElementGuid>f2b458d6-fd0a-4d08-85d4-afcb3a26ab10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazado'])[3]/following::textarea[1]</value>
      <webElementGuid>75551793-519e-4bd7-b019-5e2acc2976df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organismo público inscripto'])[1]/preceding::textarea[1]</value>
      <webElementGuid>94159599-d908-4578-ad1f-fb9ec06ddb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de inscripción:'])[1]/preceding::textarea[1]</value>
      <webElementGuid>58b24247-5b2a-40b7-a21f-a22d0e514165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21xxx']/parent::*</value>
      <webElementGuid>a28a0f72-c496-4dab-9c11-08e24f5299ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>22d959f8-7fb1-4a31-bdb6-fad363bb2a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$CPH1$Constitucion$EvaluacionProveedorTramite$txtObservaciones' and @id = 'ctl00_CPH1_Constitucion_EvaluacionProveedorTramite_txtObservaciones' and @type = 'text' and (text() = '21xxx' or . = '21xxx')]</value>
      <webElementGuid>8529502d-062a-403e-904d-8c7480a48393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
